package registry

// languages holds all registered language configurations, keyed by language ID.
var languages = map[string]LanguageConfig{
	// ─── Tier 1: Full extraction ─────────────────────────────────────────

	"javascript": {
		ID:         "javascript",
		Tier:       Tier1,
		Extensions: []string{".js", ".mjs", ".cjs"},
		SymbolNodeTypes: map[string]string{
			"function_declaration": "function",
			"arrow_function":      "function",
			"class_declaration":   "class",
			"method_definition":   "method",
			"lexical_declaration": "variable",
			"variable_declaration": "variable",
		},
		DocCommentStyle: DocJSDoc,
		ImportNodeTypes: []string{"import_statement", "call_expression"},
		StdlibModules: toSet(
			"fs", "path", "os", "util", "events", "stream", "http", "https",
			"url", "querystring", "crypto", "zlib", "buffer", "child_process",
			"cluster", "dgram", "dns", "net", "readline", "repl", "tls", "tty",
			"v8", "vm", "worker_threads", "perf_hooks", "async_hooks",
			"diagnostics_channel", "inspector", "trace_events", "wasi",
			"assert", "console", "process", "timers", "module",
		),
		StdlibPrefixes:         []string{"node:"},
		InternalImportPatterns: []string{"./", "../"},
		Export:                 ExportStrategy{Type: "keyword", Keyword: "export"},
		BuiltinTypes: toSet(
			"string", "number", "boolean", "void", "null", "undefined",
			"any", "never", "unknown", "object", "symbol", "bigint",
		),
		TestFilePatterns:   []string{"*.test.*", "*.spec.*", "**/__tests__/**"},
		ConfigFilePatterns: []string{"*.config.*"},
		TestBlockPatterns:  []string{`^\s*(?:describe|it|test)\s*\(`},
		NestingNodeTypes: []string{
			"if_statement", "for_statement", "for_in_statement",
			"while_statement", "do_statement", "try_statement", "switch_statement",
		},
		HasExplicitExports: true,
	},

	"typescript": {
		ID:         "typescript",
		Tier:       Tier1,
		Extensions: []string{".ts"},
		SymbolNodeTypes: map[string]string{
			"function_declaration":    "function",
			"arrow_function":         "function",
			"class_declaration":      "class",
			"method_definition":      "method",
			"interface_declaration":  "interface",
			"type_alias_declaration": "type_alias",
			"enum_declaration":       "enum",
			"lexical_declaration":    "variable",
			"variable_declaration":   "variable",
			"internal_module":        "namespace",
		},
		DocCommentStyle: DocJSDoc,
		ImportNodeTypes: []string{"import_statement", "call_expression"},
		StdlibModules: toSet(
			"fs", "path", "os", "util", "events", "stream", "http", "https",
			"url", "querystring", "crypto", "zlib", "buffer", "child_process",
			"cluster", "dgram", "dns", "net", "readline", "repl", "tls", "tty",
			"v8", "vm", "worker_threads", "perf_hooks", "async_hooks",
			"diagnostics_channel", "inspector", "trace_events", "wasi",
			"assert", "console", "process", "timers", "module",
		),
		StdlibPrefixes:         []string{"node:"},
		InternalImportPatterns: []string{"./", "../"},
		Export:                 ExportStrategy{Type: "keyword", Keyword: "export"},
		BuiltinTypes: toSet(
			"string", "number", "boolean", "void", "null", "undefined",
			"any", "never", "unknown", "object", "symbol", "bigint",
		),
		TestFilePatterns:   []string{"*.test.*", "*.spec.*", "**/__tests__/**"},
		ConfigFilePatterns: []string{"*.config.*"},
		TestBlockPatterns:  []string{`^\s*(?:describe|it|test)\s*\(`},
		NestingNodeTypes: []string{
			"if_statement", "for_statement", "for_in_statement",
			"while_statement", "do_statement", "try_statement", "switch_statement",
		},
		HasExplicitExports: true,
	},

	"jsx": {
		ID:         "jsx",
		Tier:       Tier1,
		Extensions: []string{".jsx"},
		SymbolNodeTypes: map[string]string{
			"function_declaration":  "function",
			"arrow_function":       "function",
			"class_declaration":    "class",
			"method_definition":    "method",
			"lexical_declaration":  "variable",
			"variable_declaration": "variable",
		},
		DocCommentStyle: DocJSDoc,
		ImportNodeTypes: []string{"import_statement", "call_expression"},
		StdlibModules: toSet(
			"fs", "path", "os", "util", "events", "stream", "http", "https",
			"url", "querystring", "crypto", "zlib", "buffer", "child_process",
			"cluster", "dgram", "dns", "net", "readline", "repl", "tls", "tty",
			"v8", "vm", "worker_threads", "perf_hooks", "async_hooks",
			"diagnostics_channel", "inspector", "trace_events", "wasi",
			"assert", "console", "process", "timers", "module",
		),
		StdlibPrefixes:         []string{"node:"},
		InternalImportPatterns: []string{"./", "../"},
		Export:                 ExportStrategy{Type: "keyword", Keyword: "export"},
		BuiltinTypes: toSet(
			"string", "number", "boolean", "void", "null", "undefined",
			"any", "never", "unknown", "object", "symbol", "bigint",
		),
		TestFilePatterns:   []string{"*.test.*", "*.spec.*", "**/__tests__/**"},
		ConfigFilePatterns: []string{"*.config.*"},
		TestBlockPatterns:  []string{`^\s*(?:describe|it|test)\s*\(`},
		NestingNodeTypes: []string{
			"if_statement", "for_statement", "for_in_statement",
			"while_statement", "do_statement", "try_statement", "switch_statement",
		},
		HasExplicitExports: true,
	},

	"tsx": {
		ID:         "tsx",
		Tier:       Tier1,
		Extensions: []string{".tsx"},
		SymbolNodeTypes: map[string]string{
			"function_declaration":    "function",
			"arrow_function":         "function",
			"class_declaration":      "class",
			"method_definition":      "method",
			"interface_declaration":  "interface",
			"type_alias_declaration": "type_alias",
			"enum_declaration":       "enum",
			"lexical_declaration":    "variable",
			"variable_declaration":   "variable",
			"internal_module":        "namespace",
		},
		DocCommentStyle: DocJSDoc,
		ImportNodeTypes: []string{"import_statement", "call_expression"},
		StdlibModules: toSet(
			"fs", "path", "os", "util", "events", "stream", "http", "https",
			"url", "querystring", "crypto", "zlib", "buffer", "child_process",
			"cluster", "dgram", "dns", "net", "readline", "repl", "tls", "tty",
			"v8", "vm", "worker_threads", "perf_hooks", "async_hooks",
			"diagnostics_channel", "inspector", "trace_events", "wasi",
			"assert", "console", "process", "timers", "module",
		),
		StdlibPrefixes:         []string{"node:"},
		InternalImportPatterns: []string{"./", "../"},
		Export:                 ExportStrategy{Type: "keyword", Keyword: "export"},
		BuiltinTypes: toSet(
			"string", "number", "boolean", "void", "null", "undefined",
			"any", "never", "unknown", "object", "symbol", "bigint",
		),
		TestFilePatterns:   []string{"*.test.*", "*.spec.*", "**/__tests__/**"},
		ConfigFilePatterns: []string{"*.config.*"},
		TestBlockPatterns:  []string{`^\s*(?:describe|it|test)\s*\(`},
		NestingNodeTypes: []string{
			"if_statement", "for_statement", "for_in_statement",
			"while_statement", "do_statement", "try_statement", "switch_statement",
		},
		HasExplicitExports: true,
	},

	"python": {
		ID:         "python",
		Tier:       Tier1,
		Extensions: []string{".py", ".pyw", ".pyi"},
		SymbolNodeTypes: map[string]string{
			"function_definition":  "function",
			"class_definition":    "class",
			"decorated_definition": "_unwrap",
			"assignment":          "variable",
		},
		DocCommentStyle: DocDocstring,
		ImportNodeTypes: []string{"import_statement", "import_from_statement"},
		StdlibModules: toSet(
			"sys", "os", "re", "json", "typing", "collections", "pathlib", "io",
			"math", "datetime", "logging", "unittest", "functools", "itertools",
			"abc", "argparse", "asyncio", "base64", "binascii", "bisect",
			"calendar", "codecs", "copy", "csv", "ctypes", "dataclasses",
			"decimal", "difflib", "email", "enum", "errno", "glob", "hashlib",
			"heapq", "hmac", "html", "http", "importlib", "inspect",
			"ipaddress", "locale", "marshal", "mimetypes", "multiprocessing",
			"operator", "pickle", "platform", "pprint", "queue", "random",
			"secrets", "select", "shelve", "shlex", "shutil", "signal",
			"socket", "sqlite3", "ssl", "stat", "string", "struct",
			"subprocess", "tempfile", "textwrap", "threading", "time", "timeit",
			"traceback", "types", "urllib", "uuid", "warnings", "weakref",
			"xml", "zipfile", "zlib",
		),
		InternalImportPatterns: []string{"."},
		Export:                 ExportStrategy{Type: "prefix", PrivatePrefix: "_"},
		BuiltinTypes: toSet(
			"int", "float", "str", "bool", "bytes", "list", "dict", "tuple",
			"set", "frozenset", "None", "object", "type", "complex", "range",
			"memoryview", "bytearray",
		),
		TestFilePatterns:   []string{"test_*.py", "*_test.py", "**/tests/**/*.py"},
		ConfigFilePatterns: []string{"setup.py", "setup.cfg", "pyproject.toml", "requirements*.txt", "Pipfile", "tox.ini"},
		TestBlockPatterns:  []string{`^\s*def\s+test_`, `^\s*class\s+Test`},
		NestingNodeTypes: []string{
			"if_statement", "for_statement", "while_statement",
			"try_statement", "with_statement", "match_statement",
		},
		HasExplicitExports: false,
	},

	"go": {
		ID:         "go",
		Tier:       Tier1,
		Extensions: []string{".go"},
		SymbolNodeTypes: map[string]string{
			"function_declaration": "function",
			"method_declaration":  "method",
			"type_declaration":    "_unwrap",
			"type_spec":           "_type_spec_dispatch",
			"type_alias":          "type_alias",
			"const_declaration":   "variable",
			"var_declaration":     "variable",
		},
		DocCommentStyle: DocTripleSlash,
		ImportNodeTypes: []string{"import_declaration"},
		StdlibModules: toSet(
			// Core I/O and OS
			"fmt", "io", "io/fs", "os", "os/exec", "os/signal", "os/user",
			"bufio", "bytes", "strings", "strconv", "unicode", "unicode/utf8",
			// Data structures and algorithms
			"sort", "slices", "maps", "cmp", "iter", "container/heap",
			"container/list", "container/ring",
			// Encoding
			"encoding", "encoding/json", "encoding/xml", "encoding/base64",
			"encoding/csv", "encoding/hex", "encoding/binary", "encoding/pem",
			"encoding/gob", "encoding/ascii85",
			// Crypto
			"crypto", "crypto/sha256", "crypto/sha512", "crypto/md5",
			"crypto/tls", "crypto/x509", "crypto/rand", "crypto/aes",
			"crypto/hmac", "crypto/ecdsa", "crypto/ed25519", "crypto/rsa",
			"crypto/elliptic", "crypto/subtle",
			// Net
			"net", "net/http", "net/http/httptest", "net/http/httputil",
			"net/url", "net/smtp", "net/rpc", "net/mail", "net/textproto",
			// Sync and concurrency
			"sync", "sync/atomic", "context",
			// Testing and debugging
			"testing", "testing/fstest", "testing/iotest",
			"runtime", "runtime/debug", "runtime/pprof",
			"reflect", "unsafe", "embed",
			// Logging
			"log", "log/slog",
			// Files and paths
			"path", "path/filepath", "flag",
			// Text and regex
			"regexp", "text/template", "html/template",
			"text/scanner", "text/tabwriter",
			// Math and hashing
			"math", "math/big", "math/rand", "hash", "hash/crc32", "hash/fnv",
			// Time
			"time",
			// Errors
			"errors",
			// Compression and archives
			"compress/gzip", "compress/zlib", "compress/flate",
			"archive/zip", "archive/tar",
			// Database
			"database/sql", "database/sql/driver",
			// Go tooling
			"go/ast", "go/parser", "go/token", "go/format", "go/types",
			"go/build", "go/doc", "go/printer",
			// HTML and MIME
			"html", "mime", "mime/multipart",
			// Misc
			"expvar", "image", "image/png", "image/jpeg",
			"plugin", "debug/elf", "debug/dwarf",
		),
		Export:     ExportStrategy{Type: "convention", Convention: "uppercase_first_letter"},
		BuiltinTypes: toSet(
			"int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64", "complex64", "complex128",
			"string", "bool", "byte", "rune", "error", "any", "comparable",
		),
		TestFilePatterns:   []string{"*_test.go"},
		ConfigFilePatterns: []string{"go.mod", "go.sum"},
		TestBlockPatterns:  []string{`^func\s+Test[A-Z]`, `^func\s+Benchmark[A-Z]`},
		NestingNodeTypes: []string{
			"if_statement", "for_statement", "select_statement",
			"switch_statement", "type_switch_statement",
		},
		HasExplicitExports: true,
	},

	"rust": {
		ID:         "rust",
		Tier:       Tier1,
		Extensions: []string{".rs"},
		SymbolNodeTypes: map[string]string{
			"function_item":    "function",
			"struct_item":      "class",
			"enum_item":        "enum",
			"trait_item":       "interface",
			"impl_item":        "_recurse",
			"type_item":        "type_alias",
			"const_item":       "variable",
			"static_item":      "variable",
			"let_declaration":  "variable",
			"mod_item":         "namespace",
			"macro_definition": "function",
		},
		DocCommentStyle:        DocTripleSlash,
		ImportNodeTypes:        []string{"use_declaration"},
		StdlibModules:          toSet("std"),
		StdlibPrefixes:         []string{"std::"},
		InternalImportPatterns: []string{"crate::", "super::", "self::"},
		Export:                 ExportStrategy{Type: "keyword", Keyword: "pub"},
		BuiltinTypes: toSet(
			"i8", "i16", "i32", "i64", "i128", "isize",
			"u8", "u16", "u32", "u64", "u128", "usize",
			"f32", "f64", "bool", "char", "str", "String",
			"Vec", "Option", "Result", "Box", "Self",
		),
		TestFilePatterns:   []string{"**/tests/**/*.rs"},
		ConfigFilePatterns: []string{"Cargo.toml", "Cargo.lock"},
		TestBlockPatterns:  []string{`#\[test\]`, `#\[cfg\(test\)\]`},
		NestingNodeTypes: []string{
			"if_expression", "for_expression", "loop_expression",
			"while_expression", "match_expression",
		},
		HasExplicitExports: true,
	},

	"java": {
		ID:         "java",
		Tier:       Tier1,
		Extensions: []string{".java"},
		SymbolNodeTypes: map[string]string{
			"method_declaration":          "method",
			"constructor_declaration":     "method",
			"class_declaration":           "class",
			"interface_declaration":       "interface",
			"enum_declaration":            "enum",
			"annotation_type_declaration": "interface",
			"field_declaration":           "variable",
			"record_declaration":          "class",
		},
		DocCommentStyle:    DocJSDoc,
		ImportNodeTypes:    []string{"import_declaration"},
		StdlibModules:     map[string]bool{},
		StdlibPrefixes:    []string{"java.", "javax."},
		Export:             ExportStrategy{Type: "keyword", Keyword: "public"},
		BuiltinTypes: toSet(
			"int", "long", "short", "byte", "float", "double", "boolean",
			"char", "void", "String", "Object", "Integer", "Long", "Double",
			"Float", "Boolean", "Byte", "Short", "Character",
		),
		TestFilePatterns:   []string{"*Test.java", "*Tests.java", "**/src/test/**/*.java"},
		ConfigFilePatterns: []string{"pom.xml", "build.gradle", "build.gradle.kts", "settings.gradle", "settings.gradle.kts"},
		TestBlockPatterns:  []string{`@Test`, `@ParameterizedTest`},
		NestingNodeTypes: []string{
			"if_statement", "for_statement", "enhanced_for_statement",
			"while_statement", "do_statement", "try_statement", "switch_expression",
		},
		HasExplicitExports: true,
	},

	"kotlin": {
		ID:         "kotlin",
		Tier:       Tier1,
		Extensions: []string{".kt", ".kts"},
		SymbolNodeTypes: map[string]string{
			"function_declaration":  "function",
			"class_declaration":    "class",
			"object_declaration":   "class",
			"interface_declaration": "interface",
			"property_declaration": "variable",
			"type_alias":           "type_alias",
			"enum_class_body":      "_recurse",
		},
		DocCommentStyle:    DocJSDoc,
		ImportNodeTypes:    []string{"import_header"},
		StdlibModules:     map[string]bool{},
		StdlibPrefixes:    []string{"kotlin.", "kotlinx."},
		Export:             ExportStrategy{Type: "all_public"},
		BuiltinTypes: toSet(
			"Int", "Long", "Short", "Byte", "Float", "Double",
			"Boolean", "Char", "String", "Unit", "Nothing", "Any",
		),
		TestFilePatterns:   []string{"*Test.kt", "*Tests.kt", "**/src/test/**/*.kt"},
		ConfigFilePatterns: []string{"build.gradle.kts", "settings.gradle.kts"},
		TestBlockPatterns:  []string{`@Test`},
		NestingNodeTypes: []string{
			"if_expression", "for_statement", "while_statement",
			"try_expression", "when_expression",
		},
		HasExplicitExports: false,
	},

	"c": {
		ID:         "c",
		Tier:       Tier1,
		Extensions: []string{".c"},
		SymbolNodeTypes: map[string]string{
			"function_definition": "function",
			"declaration":        "_declaration_dispatch",
			"struct_specifier":   "class",
			"enum_specifier":     "enum",
			"union_specifier":    "class",
			"type_definition":    "type_alias",
		},
		DocCommentStyle: DocDoxygen,
		ImportNodeTypes: []string{"preproc_include"},
		StdlibModules: toSet(
			"stdio.h", "stdlib.h", "string.h", "math.h", "ctype.h", "errno.h",
			"float.h", "limits.h", "locale.h", "setjmp.h", "signal.h",
			"stdarg.h", "stddef.h", "time.h", "assert.h", "stdbool.h",
			"stdint.h", "inttypes.h", "complex.h", "fenv.h", "tgmath.h",
			"wchar.h", "wctype.h", "threads.h", "stdatomic.h", "uchar.h",
			"unistd.h", "fcntl.h", "sys/types.h", "sys/stat.h", "pthread.h",
		),
		InternalImportPatterns: []string{`"`},
		Export:                 ExportStrategy{Type: "all_public"},
		BuiltinTypes: toSet(
			"int", "char", "float", "double", "void", "long", "short",
			"unsigned", "signed", "size_t", "ptrdiff_t", "bool", "_Bool",
		),
		TestFilePatterns:   []string{},
		ConfigFilePatterns: []string{"Makefile", "CMakeLists.txt", "configure.ac", "meson.build"},
		NestingNodeTypes: []string{
			"if_statement", "for_statement", "while_statement",
			"do_statement", "switch_statement",
		},
		HasExplicitExports: false,
	},

	"cpp": {
		ID:         "cpp",
		Tier:       Tier1,
		Extensions: []string{".cpp", ".cc", ".cxx", ".hpp", ".hxx", ".h"},
		SymbolNodeTypes: map[string]string{
			"function_definition":    "function",
			"declaration":           "_declaration_dispatch",
			"class_specifier":       "class",
			"struct_specifier":      "class",
			"enum_specifier":        "enum",
			"namespace_definition":  "namespace",
			"template_declaration":  "_unwrap",
			"type_definition":       "type_alias",
			"alias_declaration":     "type_alias",
		},
		DocCommentStyle: DocDoxygen,
		ImportNodeTypes: []string{"preproc_include"},
		StdlibModules: toSet(
			"iostream", "vector", "string", "map", "unordered_map", "set",
			"unordered_set", "algorithm", "memory", "utility", "functional",
			"numeric", "array", "deque", "list", "queue", "stack", "tuple",
			"optional", "variant", "any", "filesystem", "chrono", "thread",
			"mutex", "condition_variable", "future", "regex", "random",
			"cmath", "cstdlib", "cstring", "cstdio", "cassert", "stdexcept",
			"typeinfo", "type_traits", "concepts", "ranges", "format", "span",
			"coroutine",
		),
		InternalImportPatterns: []string{`"`},
		Export:                 ExportStrategy{Type: "all_public"},
		BuiltinTypes: toSet(
			"int", "char", "float", "double", "void", "long", "short",
			"unsigned", "signed", "bool", "auto", "size_t", "nullptr_t",
			"wchar_t", "char8_t", "char16_t", "char32_t",
		),
		TestFilePatterns:   []string{"*_test.cpp", "*_test.cc", "*Test.cpp"},
		ConfigFilePatterns: []string{"CMakeLists.txt", "Makefile", "meson.build", "conanfile.txt", "conanfile.py", "vcpkg.json"},
		NestingNodeTypes: []string{
			"if_statement", "for_statement", "for_range_loop",
			"while_statement", "do_statement", "switch_statement", "try_statement",
		},
		HasExplicitExports: false,
	},

	"csharp": {
		ID:         "csharp",
		Tier:       Tier1,
		Extensions: []string{".cs"},
		SymbolNodeTypes: map[string]string{
			"method_declaration":      "method",
			"constructor_declaration": "method",
			"class_declaration":       "class",
			"struct_declaration":      "class",
			"interface_declaration":   "interface",
			"enum_declaration":        "enum",
			"namespace_declaration":   "namespace",
			"property_declaration":    "variable",
			"field_declaration":       "variable",
			"record_declaration":      "class",
			"delegate_declaration":    "type_alias",
		},
		DocCommentStyle:    DocXMLDoc,
		ImportNodeTypes:    []string{"using_directive"},
		StdlibModules:     map[string]bool{"System": true, "Microsoft": true},
		StdlibPrefixes:    []string{"System.", "Microsoft."},
		Export:             ExportStrategy{Type: "keyword", Keyword: "public"},
		BuiltinTypes: toSet(
			"int", "long", "short", "byte", "float", "double", "decimal",
			"bool", "char", "string", "object", "void", "dynamic", "var",
			"nint", "nuint",
		),
		TestFilePatterns:   []string{"*Test.cs", "*Tests.cs", "**/*Test*/**/*.cs"},
		ConfigFilePatterns: []string{"*.csproj", "*.sln", "Directory.Build.props", "nuget.config"},
		TestBlockPatterns:  []string{`\[Test\]`, `\[Fact\]`, `\[Theory\]`},
		NestingNodeTypes: []string{
			"if_statement", "for_statement", "foreach_statement",
			"while_statement", "do_statement", "try_statement",
			"switch_statement", "switch_expression",
		},
		HasExplicitExports: true,
	},

	"swift": {
		ID:         "swift",
		Tier:       Tier1,
		Extensions: []string{".swift"},
		SymbolNodeTypes: map[string]string{
			"function_declaration":  "function",
			"class_declaration":    "class",
			"struct_declaration":   "class",
			"protocol_declaration": "interface",
			"enum_declaration":     "enum",
			"typealias_declaration": "type_alias",
			"variable_declaration": "variable",
			"init_declaration":     "method",
		},
		DocCommentStyle: DocTripleSlash,
		ImportNodeTypes: []string{"import_declaration"},
		StdlibModules: toSet(
			"Foundation", "UIKit", "SwiftUI", "Combine", "CoreData",
			"CoreGraphics", "CoreLocation", "MapKit", "AVFoundation",
			"XCTest", "os", "Darwin",
		),
		Export: ExportStrategy{Type: "keyword", Keyword: "public"},
		BuiltinTypes: toSet(
			"Int", "Int8", "Int16", "Int32", "Int64",
			"UInt", "UInt8", "UInt16", "UInt32", "UInt64",
			"Float", "Double", "Bool", "String", "Character",
			"Void", "Any", "AnyObject", "Never", "Optional",
			"Array", "Dictionary", "Set",
		),
		TestFilePatterns:   []string{"*Tests.swift", "**/*Tests/**/*.swift"},
		ConfigFilePatterns: []string{"Package.swift"},
		TestBlockPatterns:  []string{`func\s+test[A-Z]`},
		NestingNodeTypes: []string{
			"if_statement", "for_statement", "while_statement",
			"guard_statement", "switch_statement", "do_statement",
		},
		HasExplicitExports: true,
	},

	"ruby": {
		ID:         "ruby",
		Tier:       Tier1,
		Extensions: []string{".rb", ".rake", ".gemspec"},
		Basenames:  []string{"Gemfile", "Rakefile"},
		SymbolNodeTypes: map[string]string{
			"method":           "function",
			"singleton_method": "function",
			"class":            "class",
			"module":           "namespace",
			"assignment":       "variable",
		},
		DocCommentStyle: DocHash,
		ImportNodeTypes: []string{"call"},
		StdlibModules: toSet(
			"json", "net/http", "fileutils", "csv", "yaml", "set", "ostruct",
			"open-uri", "uri", "digest", "base64", "date", "time", "pathname",
			"tempfile", "logger", "socket", "openssl", "erb", "cgi", "webrick",
			"optparse", "benchmark", "singleton", "forwardable", "delegate",
			"observer", "pp", "English", "abbrev", "strscan",
		),
		InternalImportPatterns: []string{"./"},
		Export:                 ExportStrategy{Type: "all_public"},
		BuiltinTypes: toSet(
			"Integer", "Float", "String", "Symbol", "Array", "Hash",
			"NilClass", "TrueClass", "FalseClass", "Object", "BasicObject",
			"Kernel", "Comparable", "Enumerable",
		),
		TestFilePatterns:   []string{"*_spec.rb", "*_test.rb", "**/spec/**/*.rb", "**/test/**/*.rb"},
		ConfigFilePatterns: []string{"Gemfile", "Rakefile", "*.gemspec"},
		TestBlockPatterns:  []string{`^\s*(?:describe|it|context|specify)\s`, `^\s*def\s+test_`},
		NestingNodeTypes:   []string{"if", "unless", "while", "until", "for", "begin", "case"},
		HasExplicitExports: false,
	},

	"php": {
		ID:         "php",
		Tier:       Tier1,
		Extensions: []string{".php"},
		SymbolNodeTypes: map[string]string{
			"function_definition":     "function",
			"method_declaration":      "method",
			"class_declaration":       "class",
			"interface_declaration":   "interface",
			"trait_declaration":       "interface",
			"enum_declaration":        "enum",
			"property_declaration":    "variable",
			"const_declaration":       "variable",
			"namespace_definition":    "namespace",
		},
		DocCommentStyle: DocJSDoc,
		ImportNodeTypes: []string{"namespace_use_declaration", "include_expression", "include_once_expression", "require_expression", "require_once_expression"},
		StdlibModules:  map[string]bool{},
		Export:          ExportStrategy{Type: "keyword", Keyword: "public"},
		BuiltinTypes: toSet(
			"int", "float", "string", "bool", "array", "object", "null",
			"void", "mixed", "never", "callable", "iterable", "self",
			"static", "parent",
		),
		TestFilePatterns:   []string{"*Test.php", "**/tests/**/*.php"},
		ConfigFilePatterns: []string{"composer.json", "composer.lock", "phpunit.xml", "php.ini"},
		TestBlockPatterns:  []string{`@test`, `public\s+function\s+test[A-Z]`},
		NestingNodeTypes: []string{
			"if_statement", "for_statement", "foreach_statement",
			"while_statement", "do_statement", "try_statement", "switch_statement",
		},
		HasExplicitExports: true,
	},

	// ─── Tier 2: Partial extraction ──────────────────────────────────────

	"bash": {
		ID:         "bash",
		Tier:       Tier2,
		Extensions: []string{".sh", ".bash", ".zsh"},
		Basenames:  []string{".bashrc", ".zshrc", ".bash_profile", ".profile"},
		SymbolNodeTypes: map[string]string{
			"function_definition": "function",
			"variable_assignment": "variable",
		},
		DocCommentStyle:        DocHash,
		ImportNodeTypes:        []string{"command"},
		StdlibModules:         map[string]bool{},
		InternalImportPatterns: []string{"./", "../"},
		Export:                 ExportStrategy{Type: "none"},
		BuiltinTypes:          map[string]bool{},
		TestFilePatterns:       []string{"*.bats", "test_*.sh"},
		ConfigFilePatterns:     []string{".bashrc", ".zshrc", ".bash_profile"},
		NestingNodeTypes: []string{
			"if_statement", "for_statement", "while_statement", "case_statement",
		},
		HasExplicitExports: false,
	},

	"sql": {
		ID:         "sql",
		Tier:       Tier2,
		Extensions: []string{".sql"},
		SymbolNodeTypes: map[string]string{
			"create_table_statement":     "class",
			"create_function_statement":  "function",
			"create_procedure_statement": "function",
			"create_view_statement":      "variable",
			"create_index_statement":     "variable",
			"create_type_statement":      "type_alias",
		},
		DocCommentStyle: DocNone,
		StdlibModules:  map[string]bool{},
		Export:          ExportStrategy{Type: "none"},
		BuiltinTypes: toSet(
			"INTEGER", "TEXT", "REAL", "BLOB", "NULL", "VARCHAR", "BOOLEAN",
			"DATE", "TIMESTAMP", "BIGINT", "SMALLINT", "DECIMAL", "NUMERIC",
			"FLOAT", "DOUBLE", "CHAR", "UUID", "SERIAL", "JSON", "JSONB",
			"BYTEA", "ARRAY",
		),
		NestingNodeTypes:   []string{"if_statement", "case_expression"},
		HasExplicitExports: false,
	},

	"graphql": {
		ID:         "graphql",
		Tier:       Tier2,
		Extensions: []string{".graphql", ".gql"},
		SymbolNodeTypes: map[string]string{
			"type_definition":           "class",
			"input_type_definition":     "class",
			"interface_type_definition": "interface",
			"enum_type_definition":      "enum",
			"union_type_definition":     "type_alias",
			"scalar_type_definition":    "type_alias",
			"field_definition":          "variable",
			"operation_definition":      "function",
		},
		DocCommentStyle: DocNone,
		StdlibModules:  map[string]bool{},
		Export:          ExportStrategy{Type: "none"},
		BuiltinTypes:   toSet("String", "Int", "Float", "Boolean", "ID"),
		HasExplicitExports: false,
	},

	"dockerfile": {
		ID:         "dockerfile",
		Tier:       Tier2,
		Extensions: []string{".dockerfile"},
		Basenames:  []string{"Dockerfile"},
		SymbolNodeTypes: map[string]string{
			"from_instruction":  "variable",
			"arg_instruction":   "variable",
			"env_instruction":   "variable",
			"label_instruction": "variable",
		},
		DocCommentStyle:    DocHash,
		ImportNodeTypes:    []string{"from_instruction"},
		StdlibModules:     map[string]bool{},
		Export:             ExportStrategy{Type: "none"},
		BuiltinTypes:      map[string]bool{},
		ConfigFilePatterns: []string{"Dockerfile", "Dockerfile.*", "*.dockerfile"},
		HasExplicitExports: false,
	},

	"hcl": {
		ID:         "hcl",
		Tier:       Tier2,
		Extensions: []string{".tf", ".tfvars", ".tofu"},
		SymbolNodeTypes: map[string]string{
			"block": "variable",
		},
		DocCommentStyle:    DocHash,
		ImportNodeTypes:        []string{"block"},
		StdlibModules:         map[string]bool{},
		InternalImportPatterns: []string{"./", "../"},
		Export:                 ExportStrategy{Type: "none"},
		BuiltinTypes:          map[string]bool{},
		ConfigFilePatterns:     []string{"*.tf", "*.tfvars", "*.tofu", "terraform.tfvars", "*.auto.tfvars"},
		NestingNodeTypes:       []string{"block"},
		HasExplicitExports:    false,
	},

	// ─── Tier 3: Structural only ─────────────────────────────────────────

	"html": {
		ID:         "html",
		Tier:       Tier3,
		Extensions: []string{".html", ".htm"},
		SymbolNodeTypes: map[string]string{
			"element": "_element_dispatch",
		},
		DocCommentStyle:        DocNone,
		ImportNodeTypes:        []string{"element"},
		StdlibModules:         map[string]bool{},
		InternalImportPatterns: []string{"./", "../"},
		Export:                 ExportStrategy{Type: "none"},
		BuiltinTypes:          map[string]bool{},
		HasExplicitExports:    false,
	},

	"css": {
		ID:         "css",
		Tier:       Tier3,
		Extensions: []string{".css"},
		SymbolNodeTypes: map[string]string{
			"rule_set":            "variable",
			"keyframes_statement": "function",
			"media_statement":     "namespace",
		},
		DocCommentStyle:        DocNone,
		ImportNodeTypes:        []string{"import_statement"},
		StdlibModules:         map[string]bool{},
		InternalImportPatterns: []string{"./", "../"},
		Export:                 ExportStrategy{Type: "none"},
		BuiltinTypes:          map[string]bool{},
		NestingNodeTypes:       []string{"media_statement"},
		HasExplicitExports:    false,
	},

	"scss": {
		ID:         "scss",
		Tier:       Tier3,
		Extensions: []string{".scss"},
		SymbolNodeTypes: map[string]string{
			"rule_set":            "variable",
			"keyframes_statement": "function",
			"media_statement":     "namespace",
		},
		DocCommentStyle:        DocNone,
		ImportNodeTypes:        []string{"import_statement"},
		StdlibModules:         map[string]bool{},
		InternalImportPatterns: []string{"./", "../"},
		Export:                 ExportStrategy{Type: "none"},
		BuiltinTypes:          map[string]bool{},
		NestingNodeTypes:       []string{"media_statement"},
		HasExplicitExports:    false,
	},

	"json": {
		ID:         "json",
		Tier:       Tier3,
		Extensions: []string{".json", ".jsonc"},
		SymbolNodeTypes: map[string]string{
			"pair": "variable",
		},
		DocCommentStyle:    DocNone,
		StdlibModules:     map[string]bool{},
		Export:             ExportStrategy{Type: "none"},
		BuiltinTypes:      map[string]bool{},
		ConfigFilePatterns: []string{"package.json", "tsconfig.json", "composer.json", ".eslintrc.json"},
		HasExplicitExports: false,
	},

	"yaml": {
		ID:         "yaml",
		Tier:       Tier3,
		Extensions: []string{".yaml", ".yml"},
		SymbolNodeTypes: map[string]string{
			"block_mapping_pair": "variable",
		},
		DocCommentStyle:    DocNone,
		StdlibModules:     map[string]bool{},
		Export:             ExportStrategy{Type: "none"},
		BuiltinTypes:      map[string]bool{},
		HasExplicitExports: false,
	},

	"toml": {
		ID:         "toml",
		Tier:       Tier3,
		Extensions: []string{".toml"},
		SymbolNodeTypes: map[string]string{
			"pair":  "variable",
			"table": "namespace",
		},
		DocCommentStyle:    DocNone,
		StdlibModules:     map[string]bool{},
		Export:             ExportStrategy{Type: "none"},
		BuiltinTypes:      map[string]bool{},
		HasExplicitExports: false,
	},

	"markdown": {
		ID:         "markdown",
		Tier:       Tier3,
		Extensions: []string{".md", ".markdown", ".mdx"},
		SymbolNodeTypes: map[string]string{
			"atx_heading":   "function",
			"setext_heading": "function",
		},
		DocCommentStyle:        DocNone,
		ImportNodeTypes:        []string{"inline_link"},
		StdlibModules:         map[string]bool{},
		InternalImportPatterns: []string{"./", "../"},
		Export:                 ExportStrategy{Type: "none"},
		BuiltinTypes:          map[string]bool{},
		HasExplicitExports:    false,
	},

	"xml": {
		ID:         "xml",
		Tier:       Tier3,
		Extensions: []string{".xml", ".svg", ".xsl", ".xsd", ".plist"},
		SymbolNodeTypes: map[string]string{
			"element": "variable",
		},
		DocCommentStyle:    DocNone,
		StdlibModules:     map[string]bool{},
		Export:             ExportStrategy{Type: "none"},
		BuiltinTypes:      map[string]bool{},
		ConfigFilePatterns: []string{"pom.xml", "web.xml", "AndroidManifest.xml", "*.csproj"},
		HasExplicitExports: false,
	},
}

// toSet builds a map[string]bool from a variadic string list.
func toSet(items ...string) map[string]bool {
	m := make(map[string]bool, len(items))
	for _, item := range items {
		m[item] = true
	}
	return m
}
