// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateUser = `-- name: ActivateUser :exec
UPDATE users
SET is_active = TRUE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ActivateUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, activateUser, id)
	return err
}

const adminCountUsers = `-- name: AdminCountUsers :one
SELECT COUNT(*)::bigint AS total
FROM users u
WHERE ($1::text = '' OR u.username ILIKE $1 OR u.display_name ILIKE $1)
  AND ($2::boolean IS NULL OR u.is_active = $2::boolean)
`

type AdminCountUsersParams struct {
	Search   string      `json:"search"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) AdminCountUsers(ctx context.Context, arg AdminCountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountUsers, arg.Search, arg.IsActive)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const adminGetUserByID = `-- name: AdminGetUserByID :one
SELECT id, username, email, display_name, avatar_url, is_active, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) AdminGetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, adminGetUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetUserMemberships = `-- name: AdminGetUserMemberships :many
SELECT pm.project_id, p.name AS project_name, pm.role, pm.created_at AS joined_at
FROM project_members pm
JOIN projects p ON p.id = pm.project_id
WHERE pm.user_id = $1
ORDER BY pm.created_at ASC
`

type AdminGetUserMembershipsRow struct {
	ProjectID   pgtype.UUID        `json:"project_id"`
	ProjectName string             `json:"project_name"`
	Role        string             `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) AdminGetUserMemberships(ctx context.Context, userID pgtype.UUID) ([]AdminGetUserMembershipsRow, error) {
	rows, err := q.db.Query(ctx, adminGetUserMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminGetUserMembershipsRow{}
	for rows.Next() {
		var i AdminGetUserMembershipsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ProjectName,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUsers = `-- name: AdminListUsers :many
SELECT
  u.id, u.username, u.email, u.display_name, u.avatar_url,
  u.is_active, u.created_at, u.updated_at,
  (SELECT COUNT(*) FROM project_members pm WHERE pm.user_id = u.id)::bigint AS project_count,
  COALESCE(
    (SELECT array_agg(upr.role ORDER BY upr.role)
     FROM user_platform_roles upr WHERE upr.user_id = u.id),
    ARRAY[]::text[]
  ) AS platform_roles
FROM users u
WHERE ($1::text = '' OR u.username ILIKE $1 OR u.display_name ILIKE $1)
  AND ($2::boolean IS NULL OR u.is_active = $2::boolean)
ORDER BY
  CASE WHEN $3::text = 'username'   THEN u.username END ASC,
  CASE WHEN $3::text = 'created_at' THEN u.created_at END DESC,
  u.created_at DESC,
  u.id ASC
LIMIT $5 OFFSET $4
`

type AdminListUsersParams struct {
	Search    string      `json:"search"`
	IsActive  pgtype.Bool `json:"is_active"`
	Sort      string      `json:"sort"`
	RowOffset int32       `json:"row_offset"`
	RowLimit  int32       `json:"row_limit"`
}

type AdminListUsersRow struct {
	ID            pgtype.UUID        `json:"id"`
	Username      string             `json:"username"`
	Email         string             `json:"email"`
	DisplayName   pgtype.Text        `json:"display_name"`
	AvatarUrl     pgtype.Text        `json:"avatar_url"`
	IsActive      bool               `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ProjectCount  int64              `json:"project_count"`
	PlatformRoles interface{}        `json:"platform_roles"`
}

func (q *Queries) AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error) {
	rows, err := q.db.Query(ctx, adminListUsers,
		arg.Search,
		arg.IsActive,
		arg.Sort,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListUsersRow{}
	for rows.Next() {
		var i AdminListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectCount,
			&i.PlatformRoles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUpdateUser = `-- name: AdminUpdateUser :one
UPDATE users
SET
  display_name = CASE WHEN $2::text IS NOT NULL
                      THEN $2::text
                      ELSE display_name END,
  avatar_url   = CASE WHEN $3::text IS NOT NULL
                      THEN NULLIF($3::text, '')
                      ELSE avatar_url END,
  updated_at = NOW()
WHERE id = $1
RETURNING id, username, email, display_name, avatar_url, is_active, created_at, updated_at
`

type AdminUpdateUserParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName pgtype.Text `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
}

func (q *Queries) AdminUpdateUser(ctx context.Context, arg AdminUpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, adminUpdateUser, arg.ID, arg.DisplayName, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
