// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkAPIKeyProjectAccess = `-- name: CheckAPIKeyProjectAccess :one
SELECT effective_role
FROM api_key_project_access
WHERE key_hash = $1
  AND project_id = $2
LIMIT 1
`

type CheckAPIKeyProjectAccessParams struct {
	KeyHash   string      `json:"key_hash"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) CheckAPIKeyProjectAccess(ctx context.Context, arg CheckAPIKeyProjectAccessParams) (string, error) {
	row := q.db.QueryRow(ctx, checkAPIKeyProjectAccess, arg.KeyHash, arg.ProjectID)
	var effective_role string
	err := row.Scan(&effective_role)
	return effective_role, err
}

const countPersonalKeys = `-- name: CountPersonalKeys :one
SELECT COUNT(*) AS count
FROM api_keys
WHERE created_by = $1
  AND key_type = 'personal'
  AND is_active = TRUE
  AND (expires_at IS NULL OR expires_at > NOW())
`

func (q *Queries) CountPersonalKeys(ctx context.Context, createdBy pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPersonalKeys, createdBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjectKeys = `-- name: CountProjectKeys :one
SELECT COUNT(*) AS count
FROM api_keys
WHERE project_id = $1
  AND key_type = 'project'
  AND is_active = TRUE
  AND (expires_at IS NULL OR expires_at > NOW())
`

func (q *Queries) CountProjectKeys(ctx context.Context, projectID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectKeys, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (
  key_type,
  key_prefix,
  key_hash,
  name,
  role,
  project_id,
  created_by,
  expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, key_type, key_prefix, key_hash, name, role, project_id, is_active, expires_at, last_used_at, created_by, created_at
`

type CreateAPIKeyParams struct {
	KeyType   string             `json:"key_type"`
	KeyPrefix string             `json:"key_prefix"`
	KeyHash   string             `json:"key_hash"`
	Name      string             `json:"name"`
	Role      string             `json:"role"`
	ProjectID pgtype.UUID        `json:"project_id"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.KeyType,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.Name,
		arg.Role,
		arg.ProjectID,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyType,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Name,
		&i.Role,
		&i.ProjectID,
		&i.IsActive,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, key_type, key_prefix, key_hash, name, role, project_id, is_active, expires_at, last_used_at, created_by, created_at
FROM api_keys
WHERE key_hash = $1
  AND is_active = TRUE
  AND (expires_at IS NULL OR expires_at > NOW())
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyType,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Name,
		&i.Role,
		&i.ProjectID,
		&i.IsActive,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, key_type, key_prefix, key_hash, name, role, project_id, is_active, expires_at, last_used_at, created_by, created_at
FROM api_keys
WHERE id = $1
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, id pgtype.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyType,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Name,
		&i.Role,
		&i.ProjectID,
		&i.IsActive,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listPersonalKeys = `-- name: ListPersonalKeys :many
SELECT id, key_type, key_prefix, key_hash, name, role, project_id, is_active, expires_at, last_used_at, created_by, created_at
FROM api_keys
WHERE created_by = $1
  AND key_type = 'personal'
  AND is_active = TRUE
  AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY created_at DESC
`

func (q *Queries) ListPersonalKeys(ctx context.Context, createdBy pgtype.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listPersonalKeys, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.KeyType,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.Name,
			&i.Role,
			&i.ProjectID,
			&i.IsActive,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectKeys = `-- name: ListProjectKeys :many
SELECT id, key_type, key_prefix, key_hash, name, role, project_id, is_active, expires_at, last_used_at, created_by, created_at
FROM api_keys
WHERE project_id = $1
  AND key_type = 'project'
  AND is_active = TRUE
  AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY created_at DESC
`

func (q *Queries) ListProjectKeys(ctx context.Context, projectID pgtype.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listProjectKeys, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.KeyType,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.Name,
			&i.Role,
			&i.ProjectID,
			&i.IsActive,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProjectRow = `-- name: LockProjectRow :one
SELECT id FROM projects WHERE id = $1 FOR UPDATE
`

// Acquires a row-level lock on a project; use inside a transaction.
func (q *Queries) LockProjectRow(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockProjectRow, id)
	err := row.Scan(&id)
	return id, err
}

const lockUserRow = `-- name: LockUserRow :one
SELECT id FROM users WHERE id = $1 FOR UPDATE
`

// Acquires a row-level lock on a user; use inside a transaction.
func (q *Queries) LockUserRow(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockUserRow, id)
	err := row.Scan(&id)
	return id, err
}

const softDeleteAPIKey = `-- name: SoftDeleteAPIKey :execrows
UPDATE api_keys
SET is_active = FALSE
WHERE id = $1
  AND is_active = TRUE
`

func (q *Queries) SoftDeleteAPIKey(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAPIKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = NOW()
WHERE key_hash = $1
  AND is_active = TRUE
  AND (expires_at IS NULL OR expires_at > NOW())
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, keyHash string) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsed, keyHash)
	return err
}
