// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProjectOwners = `-- name: CountProjectOwners :one
SELECT COUNT(*)::bigint AS total
FROM project_members pm
JOIN users u ON u.id = pm.user_id
WHERE pm.project_id = $1
  AND pm.role = 'owner'
  AND u.is_active = TRUE
`

func (q *Queries) CountProjectOwners(ctx context.Context, projectID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectOwners, projectID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countProjectOwnersForUpdate = `-- name: CountProjectOwnersForUpdate :one
SELECT COUNT(*)::bigint AS total
FROM (
  SELECT pm.id
  FROM project_members pm
  JOIN users u ON u.id = pm.user_id
  WHERE pm.project_id = $1
    AND pm.role = 'owner'
    AND u.is_active = TRUE
  FOR UPDATE OF pm
) locked
`

// Counts project owners while acquiring row-level locks on the matching
// project_members rows. Use inside a transaction to serialize concurrent
// owner demotion / removal and prevent the last-owner invariant from
// being violated by race conditions.
// NOTE: FOR UPDATE cannot be used directly with aggregates, so we lock
// the rows in a subquery and count the locked result set.
func (q *Queries) CountProjectOwnersForUpdate(ctx context.Context, projectID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectOwnersForUpdate, projectID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)::bigint AS total
FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createProjectMember = `-- name: CreateProjectMember :one
INSERT INTO project_members (
  project_id,
  user_id,
  role,
  invited_by
) VALUES ($1, $2, $3, $4)
RETURNING id, project_id, user_id, role, invited_by, created_at, updated_at
`

type CreateProjectMemberParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Role      string      `json:"role"`
	InvitedBy pgtype.UUID `json:"invited_by"`
}

func (q *Queries) CreateProjectMember(ctx context.Context, arg CreateProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, createProjectMember,
		arg.ProjectID,
		arg.UserID,
		arg.Role,
		arg.InvitedBy,
	)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username,
  email,
  display_name,
  is_active
) VALUES ($1, $2, $3, TRUE)
RETURNING id, username, email, display_name, avatar_url, is_active, created_at, updated_at
`

type CreateUserParams struct {
	Username    string      `json:"username"`
	Email       string      `json:"email"`
	DisplayName pgtype.Text `json:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users
SET
  is_active = FALSE,
  updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const deleteProjectMember = `-- name: DeleteProjectMember :exec
DELETE FROM project_members
WHERE project_id = $1
  AND user_id = $2
`

type DeleteProjectMemberParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteProjectMember(ctx context.Context, arg DeleteProjectMemberParams) error {
	_, err := q.db.Exec(ctx, deleteProjectMember, arg.ProjectID, arg.UserID)
	return err
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT id, project_id, user_id, role, invited_by, created_at, updated_at
FROM project_members
WHERE project_id = $1
  AND user_id = $2
`

type GetProjectMemberParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, getProjectMember, arg.ProjectID, arg.UserID)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectMemberForUpdate = `-- name: GetProjectMemberForUpdate :one
SELECT id, project_id, user_id, role, invited_by, created_at, updated_at
FROM project_members
WHERE project_id = $1
  AND user_id = $2
FOR UPDATE
`

type GetProjectMemberForUpdateParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

// Fetches a project member row while acquiring a FOR UPDATE lock.
// Use inside a transaction to prevent TOCTOU races on role checks.
func (q *Queries) GetProjectMemberForUpdate(ctx context.Context, arg GetProjectMemberForUpdateParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, getProjectMemberForUpdate, arg.ProjectID, arg.UserID)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, display_name, avatar_url, is_active, created_at, updated_at
FROM users
WHERE email = $1
  AND is_active = TRUE
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, display_name, avatar_url, is_active, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, display_name, avatar_url, is_active, created_at, updated_at
FROM users
WHERE username = $1
  AND is_active = TRUE
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllProjectsWithHealth = `-- name: ListAllProjectsWithHealth :many
SELECT
  p.id, p.name, p.repo_url, p.default_branch, p.status, p.created_by, p.created_at, p.updated_at, p.selected_embedding_global_config_id, p.selected_llm_global_config_id, 'owner'::text AS role,
  snap.id                      AS index_snapshot_id,
  COALESCE(snap.git_commit, '') AS index_git_commit,
  COALESCE(snap.branch, '')    AS index_branch,
  snap.activated_at            AS index_activated_at,
  active_job.id                AS active_job_id,
  COALESCE(active_job.status, '') AS active_job_status,
  COALESCE(active_job.worker_id, '') AS active_job_worker_id,
  active_job.started_at        AS active_job_started_at,
  failed_job.id                AS failed_job_id,
  failed_job.finished_at       AS failed_job_finished_at,
  COALESCE(failed_job.job_type, '') AS failed_job_type
FROM projects p
LEFT JOIN LATERAL (
  SELECT s.id, s.git_commit, s.branch, s.activated_at
  FROM index_snapshots s
  WHERE s.project_id = p.id AND s.is_active = TRUE
  ORDER BY s.activated_at DESC NULLS LAST, s.id DESC LIMIT 1
) snap ON TRUE
LEFT JOIN LATERAL (
  SELECT j.id, j.status, j.worker_id, j.started_at FROM indexing_jobs j
  WHERE j.project_id = p.id AND j.status IN ('queued', 'running')
  ORDER BY j.created_at DESC, j.id DESC LIMIT 1
) active_job ON TRUE
LEFT JOIN LATERAL (
  SELECT j.id, j.finished_at, j.job_type FROM indexing_jobs j
  WHERE j.project_id = p.id AND j.status = 'failed'
    AND j.finished_at >= NOW() - INTERVAL '24 hours'
    AND NOT EXISTS (
      SELECT 1 FROM indexing_jobs j2
      WHERE j2.project_id = p.id
        AND j2.status = 'completed'
        AND j2.finished_at > j.finished_at
    )
  ORDER BY j.finished_at DESC, j.id DESC LIMIT 1
) failed_job ON TRUE
ORDER BY p.created_at DESC
`

type ListAllProjectsWithHealthRow struct {
	ID                              pgtype.UUID        `json:"id"`
	Name                            string             `json:"name"`
	RepoUrl                         string             `json:"repo_url"`
	DefaultBranch                   string             `json:"default_branch"`
	Status                          string             `json:"status"`
	CreatedBy                       pgtype.UUID        `json:"created_by"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                       pgtype.Timestamptz `json:"updated_at"`
	SelectedEmbeddingGlobalConfigID pgtype.UUID        `json:"selected_embedding_global_config_id"`
	SelectedLlmGlobalConfigID       pgtype.UUID        `json:"selected_llm_global_config_id"`
	Role                            string             `json:"role"`
	IndexSnapshotID                 pgtype.UUID        `json:"index_snapshot_id"`
	IndexGitCommit                  string             `json:"index_git_commit"`
	IndexBranch                     string             `json:"index_branch"`
	IndexActivatedAt                pgtype.Timestamptz `json:"index_activated_at"`
	ActiveJobID                     pgtype.UUID        `json:"active_job_id"`
	ActiveJobStatus                 string             `json:"active_job_status"`
	ActiveJobWorkerID               string             `json:"active_job_worker_id"`
	ActiveJobStartedAt              pgtype.Timestamptz `json:"active_job_started_at"`
	FailedJobID                     pgtype.UUID        `json:"failed_job_id"`
	FailedJobFinishedAt             pgtype.Timestamptz `json:"failed_job_finished_at"`
	FailedJobType                   string             `json:"failed_job_type"`
}

func (q *Queries) ListAllProjectsWithHealth(ctx context.Context) ([]ListAllProjectsWithHealthRow, error) {
	rows, err := q.db.Query(ctx, listAllProjectsWithHealth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllProjectsWithHealthRow{}
	for rows.Next() {
		var i ListAllProjectsWithHealthRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepoUrl,
			&i.DefaultBranch,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SelectedEmbeddingGlobalConfigID,
			&i.SelectedLlmGlobalConfigID,
			&i.Role,
			&i.IndexSnapshotID,
			&i.IndexGitCommit,
			&i.IndexBranch,
			&i.IndexActivatedAt,
			&i.ActiveJobID,
			&i.ActiveJobStatus,
			&i.ActiveJobWorkerID,
			&i.ActiveJobStartedAt,
			&i.FailedJobID,
			&i.FailedJobFinishedAt,
			&i.FailedJobType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT pm.id, pm.project_id, pm.user_id, pm.role, pm.invited_by, pm.created_at, pm.updated_at, u.username, u.display_name, u.avatar_url
FROM project_members pm
JOIN users u ON u.id = pm.user_id
WHERE pm.project_id = $1
  AND u.is_active = TRUE
ORDER BY pm.created_at ASC
`

type ListProjectMembersRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        string             `json:"role"`
	InvitedBy   pgtype.UUID        `json:"invited_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Username    string             `json:"username"`
	DisplayName pgtype.Text        `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID pgtype.UUID) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMembersRow{}
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.InvitedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserProjectIDs = `-- name: ListUserProjectIDs :many
SELECT pm.project_id
FROM project_members pm
WHERE pm.user_id = $1
`

func (q *Queries) ListUserProjectIDs(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listUserProjectIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var project_id pgtype.UUID
		if err := rows.Scan(&project_id); err != nil {
			return nil, err
		}
		items = append(items, project_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserProjects = `-- name: ListUserProjects :many
SELECT p.id, p.name, p.repo_url, p.default_branch, p.status, p.created_by, p.created_at, p.updated_at, p.selected_embedding_global_config_id, p.selected_llm_global_config_id, pm.role
FROM projects p
JOIN project_members pm ON pm.project_id = p.id
WHERE pm.user_id = $1
ORDER BY p.created_at DESC
`

type ListUserProjectsRow struct {
	ID                              pgtype.UUID        `json:"id"`
	Name                            string             `json:"name"`
	RepoUrl                         string             `json:"repo_url"`
	DefaultBranch                   string             `json:"default_branch"`
	Status                          string             `json:"status"`
	CreatedBy                       pgtype.UUID        `json:"created_by"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                       pgtype.Timestamptz `json:"updated_at"`
	SelectedEmbeddingGlobalConfigID pgtype.UUID        `json:"selected_embedding_global_config_id"`
	SelectedLlmGlobalConfigID       pgtype.UUID        `json:"selected_llm_global_config_id"`
	Role                            string             `json:"role"`
}

func (q *Queries) ListUserProjects(ctx context.Context, userID pgtype.UUID) ([]ListUserProjectsRow, error) {
	rows, err := q.db.Query(ctx, listUserProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserProjectsRow{}
	for rows.Next() {
		var i ListUserProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepoUrl,
			&i.DefaultBranch,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SelectedEmbeddingGlobalConfigID,
			&i.SelectedLlmGlobalConfigID,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserProjectsWithHealth = `-- name: ListUserProjectsWithHealth :many
SELECT
  p.id, p.name, p.repo_url, p.default_branch, p.status, p.created_by, p.created_at, p.updated_at, p.selected_embedding_global_config_id, p.selected_llm_global_config_id, pm.role,
  snap.id                      AS index_snapshot_id,
  COALESCE(snap.git_commit, '') AS index_git_commit,
  COALESCE(snap.branch, '')    AS index_branch,
  snap.activated_at            AS index_activated_at,
  active_job.id                AS active_job_id,
  COALESCE(active_job.status, '') AS active_job_status,
  COALESCE(active_job.worker_id, '') AS active_job_worker_id,
  active_job.started_at        AS active_job_started_at,
  failed_job.id                AS failed_job_id,
  failed_job.finished_at       AS failed_job_finished_at,
  COALESCE(failed_job.job_type, '') AS failed_job_type
FROM projects p
JOIN project_members pm ON pm.project_id = p.id
LEFT JOIN LATERAL (
  SELECT s.id, s.git_commit, s.branch, s.activated_at
  FROM index_snapshots s
  WHERE s.project_id = p.id AND s.is_active = TRUE
  ORDER BY s.activated_at DESC NULLS LAST, s.id DESC LIMIT 1
) snap ON TRUE
LEFT JOIN LATERAL (
  SELECT j.id, j.status, j.worker_id, j.started_at FROM indexing_jobs j
  WHERE j.project_id = p.id AND j.status IN ('queued', 'running')
  ORDER BY j.created_at DESC, j.id DESC LIMIT 1
) active_job ON TRUE
LEFT JOIN LATERAL (
  SELECT j.id, j.finished_at, j.job_type FROM indexing_jobs j
  WHERE j.project_id = p.id AND j.status = 'failed'
    AND j.finished_at >= NOW() - INTERVAL '24 hours'
    AND NOT EXISTS (
      SELECT 1 FROM indexing_jobs j2
      WHERE j2.project_id = p.id
        AND j2.status = 'completed'
        AND j2.finished_at > j.finished_at
    )
  ORDER BY j.finished_at DESC, j.id DESC LIMIT 1
) failed_job ON TRUE
WHERE pm.user_id = $1
ORDER BY p.created_at DESC
`

type ListUserProjectsWithHealthRow struct {
	ID                              pgtype.UUID        `json:"id"`
	Name                            string             `json:"name"`
	RepoUrl                         string             `json:"repo_url"`
	DefaultBranch                   string             `json:"default_branch"`
	Status                          string             `json:"status"`
	CreatedBy                       pgtype.UUID        `json:"created_by"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                       pgtype.Timestamptz `json:"updated_at"`
	SelectedEmbeddingGlobalConfigID pgtype.UUID        `json:"selected_embedding_global_config_id"`
	SelectedLlmGlobalConfigID       pgtype.UUID        `json:"selected_llm_global_config_id"`
	Role                            string             `json:"role"`
	IndexSnapshotID                 pgtype.UUID        `json:"index_snapshot_id"`
	IndexGitCommit                  string             `json:"index_git_commit"`
	IndexBranch                     string             `json:"index_branch"`
	IndexActivatedAt                pgtype.Timestamptz `json:"index_activated_at"`
	ActiveJobID                     pgtype.UUID        `json:"active_job_id"`
	ActiveJobStatus                 string             `json:"active_job_status"`
	ActiveJobWorkerID               string             `json:"active_job_worker_id"`
	ActiveJobStartedAt              pgtype.Timestamptz `json:"active_job_started_at"`
	FailedJobID                     pgtype.UUID        `json:"failed_job_id"`
	FailedJobFinishedAt             pgtype.Timestamptz `json:"failed_job_finished_at"`
	FailedJobType                   string             `json:"failed_job_type"`
}

func (q *Queries) ListUserProjectsWithHealth(ctx context.Context, userID pgtype.UUID) ([]ListUserProjectsWithHealthRow, error) {
	rows, err := q.db.Query(ctx, listUserProjectsWithHealth, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserProjectsWithHealthRow{}
	for rows.Next() {
		var i ListUserProjectsWithHealthRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepoUrl,
			&i.DefaultBranch,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SelectedEmbeddingGlobalConfigID,
			&i.SelectedLlmGlobalConfigID,
			&i.Role,
			&i.IndexSnapshotID,
			&i.IndexGitCommit,
			&i.IndexBranch,
			&i.IndexActivatedAt,
			&i.ActiveJobID,
			&i.ActiveJobStatus,
			&i.ActiveJobWorkerID,
			&i.ActiveJobStartedAt,
			&i.FailedJobID,
			&i.FailedJobFinishedAt,
			&i.FailedJobType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, display_name, avatar_url, is_active, created_at, updated_at
FROM users
WHERE is_active = TRUE
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectMemberRole = `-- name: UpdateProjectMemberRole :one
UPDATE project_members
SET
  role = $3,
  updated_at = NOW()
WHERE project_id = $1
  AND user_id = $2
RETURNING id, project_id, user_id, role, invited_by, created_at, updated_at
`

type UpdateProjectMemberRoleParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Role      string      `json:"role"`
}

func (q *Queries) UpdateProjectMemberRole(ctx context.Context, arg UpdateProjectMemberRoleParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, updateProjectMemberRole, arg.ProjectID, arg.UserID, arg.Role)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
  display_name = COALESCE($2, display_name),
  avatar_url = CASE WHEN $3::text IS NOT NULL THEN NULLIF($3::text, '') ELSE avatar_url END,
  email = COALESCE($4, email),
  updated_at = NOW()
WHERE id = $1
RETURNING id, username, email, display_name, avatar_url, is_active, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName pgtype.Text `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	Email       pgtype.Text `json:"email"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
