// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: commits.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCommitFileDiffs = `-- name: CountCommitFileDiffs :one
SELECT COUNT(*)::bigint AS total
FROM commit_file_diffs
WHERE project_id = $1 AND commit_id = $2
`

type CountCommitFileDiffsParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	CommitID  pgtype.UUID `json:"commit_id"`
}

func (q *Queries) CountCommitFileDiffs(ctx context.Context, arg CountCommitFileDiffsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCommitFileDiffs, arg.ProjectID, arg.CommitID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countFileDiffsByPath = `-- name: CountFileDiffsByPath :one
SELECT count(*)::bigint AS total
FROM commit_file_diffs cfd
WHERE cfd.project_id = $1
  AND ($2 = cfd.new_file_path OR $2 = cfd.old_file_path)
`

type CountFileDiffsByPathParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	FilePath  pgtype.Text `json:"file_path"`
}

func (q *Queries) CountFileDiffsByPath(ctx context.Context, arg CountFileDiffsByPathParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFileDiffsByPath, arg.ProjectID, arg.FilePath)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countProjectCommits = `-- name: CountProjectCommits :one
SELECT COUNT(*)::bigint AS total
FROM commits
WHERE project_id = $1
`

func (q *Queries) CountProjectCommits(ctx context.Context, projectID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectCommits, projectID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const deleteProjectCommits = `-- name: DeleteProjectCommits :exec
DELETE FROM commits
WHERE project_id = $1
`

func (q *Queries) DeleteProjectCommits(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectCommits, projectID)
	return err
}

const deleteProjectFileContents = `-- name: DeleteProjectFileContents :exec
DELETE FROM file_contents
WHERE project_id = $1
`

func (q *Queries) DeleteProjectFileContents(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectFileContents, projectID)
	return err
}

const getCommitByHash = `-- name: GetCommitByHash :one
SELECT id, project_id, commit_hash, author_name, author_email, author_date, committer_name, committer_email, committer_date, message, created_at
FROM commits
WHERE project_id = $1 AND commit_hash = $2
`

type GetCommitByHashParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	CommitHash string      `json:"commit_hash"`
}

func (q *Queries) GetCommitByHash(ctx context.Context, arg GetCommitByHashParams) (Commit, error) {
	row := q.db.QueryRow(ctx, getCommitByHash, arg.ProjectID, arg.CommitHash)
	var i Commit
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CommitHash,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.AuthorDate,
		&i.CommitterName,
		&i.CommitterEmail,
		&i.CommitterDate,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const getCommitByID = `-- name: GetCommitByID :one
SELECT id, project_id, commit_hash, author_name, author_email, author_date, committer_name, committer_email, committer_date, message, created_at
FROM commits
WHERE project_id = $1 AND id = $2
`

type GetCommitByIDParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) GetCommitByID(ctx context.Context, arg GetCommitByIDParams) (Commit, error) {
	row := q.db.QueryRow(ctx, getCommitByID, arg.ProjectID, arg.ID)
	var i Commit
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CommitHash,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.AuthorDate,
		&i.CommitterName,
		&i.CommitterEmail,
		&i.CommitterDate,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const getCommitChildren = `-- name: GetCommitChildren :many
SELECT cp.project_id, cp.commit_id, cp.parent_commit_id, cp.ordinal, c.commit_hash AS child_hash
FROM commit_parents cp
JOIN commits c ON c.id = cp.commit_id
WHERE cp.project_id = $1 AND cp.parent_commit_id = $2
ORDER BY cp.ordinal, c.commit_hash
`

type GetCommitChildrenParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	ParentCommitID pgtype.UUID `json:"parent_commit_id"`
}

type GetCommitChildrenRow struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	CommitID       pgtype.UUID `json:"commit_id"`
	ParentCommitID pgtype.UUID `json:"parent_commit_id"`
	Ordinal        int32       `json:"ordinal"`
	ChildHash      string      `json:"child_hash"`
}

func (q *Queries) GetCommitChildren(ctx context.Context, arg GetCommitChildrenParams) ([]GetCommitChildrenRow, error) {
	rows, err := q.db.Query(ctx, getCommitChildren, arg.ProjectID, arg.ParentCommitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCommitChildrenRow{}
	for rows.Next() {
		var i GetCommitChildrenRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.CommitID,
			&i.ParentCommitID,
			&i.Ordinal,
			&i.ChildHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommitDiffStats = `-- name: GetCommitDiffStats :one
SELECT
  COUNT(*)::bigint AS files_changed,
  COALESCE(SUM(additions), 0)::bigint AS total_additions,
  COALESCE(SUM(deletions), 0)::bigint AS total_deletions
FROM commit_file_diffs
WHERE project_id = $1 AND commit_id = $2
`

type GetCommitDiffStatsParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	CommitID  pgtype.UUID `json:"commit_id"`
}

type GetCommitDiffStatsRow struct {
	FilesChanged   int64 `json:"files_changed"`
	TotalAdditions int64 `json:"total_additions"`
	TotalDeletions int64 `json:"total_deletions"`
}

func (q *Queries) GetCommitDiffStats(ctx context.Context, arg GetCommitDiffStatsParams) (GetCommitDiffStatsRow, error) {
	row := q.db.QueryRow(ctx, getCommitDiffStats, arg.ProjectID, arg.CommitID)
	var i GetCommitDiffStatsRow
	err := row.Scan(&i.FilesChanged, &i.TotalAdditions, &i.TotalDeletions)
	return i, err
}

const getCommitFileDiff = `-- name: GetCommitFileDiff :one
SELECT id, project_id, commit_id, parent_commit_id, old_file_path, new_file_path, change_type, patch, additions, deletions, created_at
FROM commit_file_diffs
WHERE project_id = $1 AND commit_id = $2 AND id = $3
`

type GetCommitFileDiffParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	CommitID  pgtype.UUID `json:"commit_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) GetCommitFileDiff(ctx context.Context, arg GetCommitFileDiffParams) (CommitFileDiff, error) {
	row := q.db.QueryRow(ctx, getCommitFileDiff, arg.ProjectID, arg.CommitID, arg.ID)
	var i CommitFileDiff
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CommitID,
		&i.ParentCommitID,
		&i.OldFilePath,
		&i.NewFilePath,
		&i.ChangeType,
		&i.Patch,
		&i.Additions,
		&i.Deletions,
		&i.CreatedAt,
	)
	return i, err
}

const getCommitParents = `-- name: GetCommitParents :many
SELECT cp.project_id, cp.commit_id, cp.parent_commit_id, cp.ordinal, c.commit_hash AS parent_hash
FROM commit_parents cp
JOIN commits c ON c.id = cp.parent_commit_id
WHERE cp.project_id = $1 AND cp.commit_id = $2
ORDER BY cp.ordinal
`

type GetCommitParentsParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	CommitID  pgtype.UUID `json:"commit_id"`
}

type GetCommitParentsRow struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	CommitID       pgtype.UUID `json:"commit_id"`
	ParentCommitID pgtype.UUID `json:"parent_commit_id"`
	Ordinal        int32       `json:"ordinal"`
	ParentHash     string      `json:"parent_hash"`
}

func (q *Queries) GetCommitParents(ctx context.Context, arg GetCommitParentsParams) ([]GetCommitParentsRow, error) {
	rows, err := q.db.Query(ctx, getCommitParents, arg.ProjectID, arg.CommitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCommitParentsRow{}
	for rows.Next() {
		var i GetCommitParentsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.CommitID,
			&i.ParentCommitID,
			&i.Ordinal,
			&i.ParentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileContentByHash = `-- name: GetFileContentByHash :one
SELECT id, project_id, content_hash, content, tree_sitter_ast, size_bytes, line_count, created_at
FROM file_contents
WHERE project_id = $1 AND content_hash = $2
`

type GetFileContentByHashParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	ContentHash string      `json:"content_hash"`
}

func (q *Queries) GetFileContentByHash(ctx context.Context, arg GetFileContentByHashParams) (FileContent, error) {
	row := q.db.QueryRow(ctx, getFileContentByHash, arg.ProjectID, arg.ContentHash)
	var i FileContent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ContentHash,
		&i.Content,
		&i.TreeSitterAst,
		&i.SizeBytes,
		&i.LineCount,
		&i.CreatedAt,
	)
	return i, err
}

const getFileContentByID = `-- name: GetFileContentByID :one
SELECT id, project_id, content_hash, content, tree_sitter_ast, size_bytes, line_count, created_at
FROM file_contents
WHERE project_id = $1 AND id = $2
`

type GetFileContentByIDParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) GetFileContentByID(ctx context.Context, arg GetFileContentByIDParams) (FileContent, error) {
	row := q.db.QueryRow(ctx, getFileContentByID, arg.ProjectID, arg.ID)
	var i FileContent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ContentHash,
		&i.Content,
		&i.TreeSitterAst,
		&i.SizeBytes,
		&i.LineCount,
		&i.CreatedAt,
	)
	return i, err
}

const insertCommit = `-- name: InsertCommit :one

INSERT INTO commits (
  project_id,
  commit_hash,
  author_name,
  author_email,
  author_date,
  committer_name,
  committer_email,
  committer_date,
  message
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (project_id, commit_hash) DO UPDATE
  SET project_id = commits.project_id
RETURNING id, project_id, commit_hash, author_name, author_email, author_date, committer_name, committer_email, committer_date, message, created_at
`

type InsertCommitParams struct {
	ProjectID      pgtype.UUID        `json:"project_id"`
	CommitHash     string             `json:"commit_hash"`
	AuthorName     string             `json:"author_name"`
	AuthorEmail    string             `json:"author_email"`
	AuthorDate     pgtype.Timestamptz `json:"author_date"`
	CommitterName  string             `json:"committer_name"`
	CommitterEmail string             `json:"committer_email"`
	CommitterDate  pgtype.Timestamptz `json:"committer_date"`
	Message        string             `json:"message"`
}

// =============================================
// Commits
// =============================================
func (q *Queries) InsertCommit(ctx context.Context, arg InsertCommitParams) (Commit, error) {
	row := q.db.QueryRow(ctx, insertCommit,
		arg.ProjectID,
		arg.CommitHash,
		arg.AuthorName,
		arg.AuthorEmail,
		arg.AuthorDate,
		arg.CommitterName,
		arg.CommitterEmail,
		arg.CommitterDate,
		arg.Message,
	)
	var i Commit
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CommitHash,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.AuthorDate,
		&i.CommitterName,
		&i.CommitterEmail,
		&i.CommitterDate,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const insertCommitFileDiff = `-- name: InsertCommitFileDiff :one

INSERT INTO commit_file_diffs (
  project_id,
  commit_id,
  parent_commit_id,
  old_file_path,
  new_file_path,
  change_type,
  patch,
  additions,
  deletions
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (project_id, commit_id, COALESCE(old_file_path, ''), COALESCE(new_file_path, ''))
  DO UPDATE SET project_id = commit_file_diffs.project_id
RETURNING id, project_id, commit_id, parent_commit_id, old_file_path, new_file_path, change_type, patch, additions, deletions, created_at
`

type InsertCommitFileDiffParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	CommitID       pgtype.UUID `json:"commit_id"`
	ParentCommitID pgtype.UUID `json:"parent_commit_id"`
	OldFilePath    pgtype.Text `json:"old_file_path"`
	NewFilePath    pgtype.Text `json:"new_file_path"`
	ChangeType     string      `json:"change_type"`
	Patch          pgtype.Text `json:"patch"`
	Additions      int32       `json:"additions"`
	Deletions      int32       `json:"deletions"`
}

// =============================================
// Commit file diffs
// =============================================
func (q *Queries) InsertCommitFileDiff(ctx context.Context, arg InsertCommitFileDiffParams) (CommitFileDiff, error) {
	row := q.db.QueryRow(ctx, insertCommitFileDiff,
		arg.ProjectID,
		arg.CommitID,
		arg.ParentCommitID,
		arg.OldFilePath,
		arg.NewFilePath,
		arg.ChangeType,
		arg.Patch,
		arg.Additions,
		arg.Deletions,
	)
	var i CommitFileDiff
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CommitID,
		&i.ParentCommitID,
		&i.OldFilePath,
		&i.NewFilePath,
		&i.ChangeType,
		&i.Patch,
		&i.Additions,
		&i.Deletions,
		&i.CreatedAt,
	)
	return i, err
}

const insertCommitParent = `-- name: InsertCommitParent :exec

INSERT INTO commit_parents (project_id, commit_id, parent_commit_id, ordinal)
VALUES ($1, $2, $3, $4)
ON CONFLICT (project_id, commit_id, parent_commit_id) DO NOTHING
`

type InsertCommitParentParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	CommitID       pgtype.UUID `json:"commit_id"`
	ParentCommitID pgtype.UUID `json:"parent_commit_id"`
	Ordinal        int32       `json:"ordinal"`
}

// =============================================
// Commit parents
// =============================================
func (q *Queries) InsertCommitParent(ctx context.Context, arg InsertCommitParentParams) error {
	_, err := q.db.Exec(ctx, insertCommitParent,
		arg.ProjectID,
		arg.CommitID,
		arg.ParentCommitID,
		arg.Ordinal,
	)
	return err
}

const listCommitFileDiffs = `-- name: ListCommitFileDiffs :many
SELECT id, project_id, commit_id, parent_commit_id, old_file_path, new_file_path, change_type, patch, additions, deletions, created_at
FROM commit_file_diffs
WHERE project_id = $1 AND commit_id = $2
ORDER BY COALESCE(new_file_path, old_file_path)
LIMIT $3 OFFSET $4
`

type ListCommitFileDiffsParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	CommitID  pgtype.UUID `json:"commit_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListCommitFileDiffs(ctx context.Context, arg ListCommitFileDiffsParams) ([]CommitFileDiff, error) {
	rows, err := q.db.Query(ctx, listCommitFileDiffs,
		arg.ProjectID,
		arg.CommitID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommitFileDiff{}
	for rows.Next() {
		var i CommitFileDiff
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CommitID,
			&i.ParentCommitID,
			&i.OldFilePath,
			&i.NewFilePath,
			&i.ChangeType,
			&i.Patch,
			&i.Additions,
			&i.Deletions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommitFileDiffsMeta = `-- name: ListCommitFileDiffsMeta :many
SELECT id, project_id, commit_id, parent_commit_id,
       old_file_path, new_file_path, change_type,
       additions, deletions, created_at
FROM commit_file_diffs
WHERE project_id = $1 AND commit_id = $2
ORDER BY COALESCE(new_file_path, old_file_path)
LIMIT $3 OFFSET $4
`

type ListCommitFileDiffsMetaParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	CommitID  pgtype.UUID `json:"commit_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListCommitFileDiffsMetaRow struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	CommitID       pgtype.UUID        `json:"commit_id"`
	ParentCommitID pgtype.UUID        `json:"parent_commit_id"`
	OldFilePath    pgtype.Text        `json:"old_file_path"`
	NewFilePath    pgtype.Text        `json:"new_file_path"`
	ChangeType     string             `json:"change_type"`
	Additions      int32              `json:"additions"`
	Deletions      int32              `json:"deletions"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListCommitFileDiffsMeta(ctx context.Context, arg ListCommitFileDiffsMetaParams) ([]ListCommitFileDiffsMetaRow, error) {
	rows, err := q.db.Query(ctx, listCommitFileDiffsMeta,
		arg.ProjectID,
		arg.CommitID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommitFileDiffsMetaRow{}
	for rows.Next() {
		var i ListCommitFileDiffsMetaRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CommitID,
			&i.ParentCommitID,
			&i.OldFilePath,
			&i.NewFilePath,
			&i.ChangeType,
			&i.Additions,
			&i.Deletions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommitsBetween = `-- name: ListCommitsBetween :many
SELECT id, project_id, commit_hash, author_name, author_email, author_date, committer_name, committer_email, committer_date, message, created_at
FROM commits
WHERE project_id = $1
  AND committer_date >= $2
  AND committer_date <= $3
ORDER BY committer_date DESC, id DESC
`

type ListCommitsBetweenParams struct {
	ProjectID       pgtype.UUID        `json:"project_id"`
	CommitterDate   pgtype.Timestamptz `json:"committer_date"`
	CommitterDate_2 pgtype.Timestamptz `json:"committer_date_2"`
}

func (q *Queries) ListCommitsBetween(ctx context.Context, arg ListCommitsBetweenParams) ([]Commit, error) {
	rows, err := q.db.Query(ctx, listCommitsBetween, arg.ProjectID, arg.CommitterDate, arg.CommitterDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Commit{}
	for rows.Next() {
		var i Commit
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CommitHash,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.AuthorDate,
			&i.CommitterName,
			&i.CommitterEmail,
			&i.CommitterDate,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileDiffsByPath = `-- name: ListFileDiffsByPath :many
SELECT cfd.id, cfd.project_id, cfd.commit_id, cfd.parent_commit_id, cfd.old_file_path, cfd.new_file_path, cfd.change_type, cfd.patch, cfd.additions, cfd.deletions, cfd.created_at
FROM commit_file_diffs cfd
JOIN commits c ON c.id = cfd.commit_id
WHERE cfd.project_id = $1
  AND (cfd.new_file_path = $2 OR cfd.old_file_path = $2)
ORDER BY c.committer_date DESC, cfd.id DESC
LIMIT $4 OFFSET $3
`

type ListFileDiffsByPathParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	FilePath    pgtype.Text `json:"file_path"`
	QueryOffset int32       `json:"query_offset"`
	QueryLimit  int32       `json:"query_limit"`
}

func (q *Queries) ListFileDiffsByPath(ctx context.Context, arg ListFileDiffsByPathParams) ([]CommitFileDiff, error) {
	rows, err := q.db.Query(ctx, listFileDiffsByPath,
		arg.ProjectID,
		arg.FilePath,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommitFileDiff{}
	for rows.Next() {
		var i CommitFileDiff
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CommitID,
			&i.ParentCommitID,
			&i.OldFilePath,
			&i.NewFilePath,
			&i.ChangeType,
			&i.Patch,
			&i.Additions,
			&i.Deletions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileDiffsByPathWithCommit = `-- name: ListFileDiffsByPathWithCommit :many
SELECT
  cfd.id         AS diff_id,
  c.commit_hash,
  c.author_name,
  c.committer_date,
  c.message,
  cfd.change_type,
  cfd.additions,
  cfd.deletions
FROM commit_file_diffs cfd
JOIN commits c ON c.id = cfd.commit_id
WHERE cfd.project_id = $1
  AND ($2 = cfd.new_file_path OR $2 = cfd.old_file_path)
ORDER BY c.committer_date DESC, cfd.id DESC
LIMIT $4 OFFSET $3
`

type ListFileDiffsByPathWithCommitParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	FilePath    pgtype.Text `json:"file_path"`
	QueryOffset int32       `json:"query_offset"`
	QueryLimit  int32       `json:"query_limit"`
}

type ListFileDiffsByPathWithCommitRow struct {
	DiffID        pgtype.UUID        `json:"diff_id"`
	CommitHash    string             `json:"commit_hash"`
	AuthorName    string             `json:"author_name"`
	CommitterDate pgtype.Timestamptz `json:"committer_date"`
	Message       string             `json:"message"`
	ChangeType    string             `json:"change_type"`
	Additions     int32              `json:"additions"`
	Deletions     int32              `json:"deletions"`
}

func (q *Queries) ListFileDiffsByPathWithCommit(ctx context.Context, arg ListFileDiffsByPathWithCommitParams) ([]ListFileDiffsByPathWithCommitRow, error) {
	rows, err := q.db.Query(ctx, listFileDiffsByPathWithCommit,
		arg.ProjectID,
		arg.FilePath,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFileDiffsByPathWithCommitRow{}
	for rows.Next() {
		var i ListFileDiffsByPathWithCommitRow
		if err := rows.Scan(
			&i.DiffID,
			&i.CommitHash,
			&i.AuthorName,
			&i.CommitterDate,
			&i.Message,
			&i.ChangeType,
			&i.Additions,
			&i.Deletions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectCommits = `-- name: ListProjectCommits :many
SELECT id, project_id, commit_hash, author_name, author_email, author_date, committer_name, committer_email, committer_date, message, created_at
FROM commits
WHERE project_id = $1
ORDER BY committer_date DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListProjectCommitsParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListProjectCommits(ctx context.Context, arg ListProjectCommitsParams) ([]Commit, error) {
	rows, err := q.db.Query(ctx, listProjectCommits, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Commit{}
	for rows.Next() {
		var i Commit
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CommitHash,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.AuthorDate,
			&i.CommitterName,
			&i.CommitterEmail,
			&i.CommitterDate,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFileContentAST = `-- name: SetFileContentAST :execrows
UPDATE file_contents
SET tree_sitter_ast = $3
WHERE project_id = $1 AND id = $2
`

type SetFileContentASTParams struct {
	ProjectID     pgtype.UUID `json:"project_id"`
	ID            pgtype.UUID `json:"id"`
	TreeSitterAst []byte      `json:"tree_sitter_ast"`
}

func (q *Queries) SetFileContentAST(ctx context.Context, arg SetFileContentASTParams) (int64, error) {
	result, err := q.db.Exec(ctx, setFileContentAST, arg.ProjectID, arg.ID, arg.TreeSitterAst)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFileContentRef = `-- name: UpdateFileContentRef :execrows
UPDATE files
SET file_content_id = $3
WHERE project_id = $1 AND id = $2
`

type UpdateFileContentRefParams struct {
	ProjectID     pgtype.UUID `json:"project_id"`
	ID            pgtype.UUID `json:"id"`
	FileContentID pgtype.UUID `json:"file_content_id"`
}

func (q *Queries) UpdateFileContentRef(ctx context.Context, arg UpdateFileContentRefParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFileContentRef, arg.ProjectID, arg.ID, arg.FileContentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSnapshotCommitID = `-- name: UpdateSnapshotCommitID :execrows

UPDATE index_snapshots
SET commit_id = $3
WHERE project_id = $1 AND id = $2
`

type UpdateSnapshotCommitIDParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ID        pgtype.UUID `json:"id"`
	CommitID  pgtype.UUID `json:"commit_id"`
}

// =============================================
// Snapshot ↔ Commit link
// =============================================
func (q *Queries) UpdateSnapshotCommitID(ctx context.Context, arg UpdateSnapshotCommitIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSnapshotCommitID, arg.ProjectID, arg.ID, arg.CommitID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertFileContent = `-- name: UpsertFileContent :one

INSERT INTO file_contents (
  project_id,
  content_hash,
  content,
  size_bytes,
  line_count
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (project_id, content_hash) DO UPDATE
  SET project_id = file_contents.project_id
RETURNING id, project_id, content_hash, content, tree_sitter_ast, size_bytes, line_count, created_at
`

type UpsertFileContentParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	ContentHash string      `json:"content_hash"`
	Content     string      `json:"content"`
	SizeBytes   int64       `json:"size_bytes"`
	LineCount   int32       `json:"line_count"`
}

// =============================================
// File contents
// =============================================
func (q *Queries) UpsertFileContent(ctx context.Context, arg UpsertFileContentParams) (FileContent, error) {
	row := q.db.QueryRow(ctx, upsertFileContent,
		arg.ProjectID,
		arg.ContentHash,
		arg.Content,
		arg.SizeBytes,
		arg.LineCount,
	)
	var i FileContent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ContentHash,
		&i.Content,
		&i.TreeSitterAst,
		&i.SizeBytes,
		&i.LineCount,
		&i.CreatedAt,
	)
	return i, err
}
