// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dependencies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFilesWithDependencies = `-- name: CountFilesWithDependencies :one
SELECT COUNT(DISTINCT file_path)::bigint AS total
FROM (
  SELECT d1.source_file_path AS file_path FROM dependencies d1
  WHERE d1.project_id = $1 AND d1.index_snapshot_id = $2
  UNION
  SELECT d2.target_file_path AS file_path FROM dependencies d2
  WHERE d2.project_id = $1 AND d2.index_snapshot_id = $2
    AND d2.target_file_path IS NOT NULL
) sub
`

type CountFilesWithDependenciesParams struct {
	ProjectID       pgtype.UUID `json:"project_id"`
	IndexSnapshotID pgtype.UUID `json:"index_snapshot_id"`
}

func (q *Queries) CountFilesWithDependencies(ctx context.Context, arg CountFilesWithDependenciesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFilesWithDependencies, arg.ProjectID, arg.IndexSnapshotID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const listDependenciesFromFile = `-- name: ListDependenciesFromFile :many
SELECT d.id, d.source_file_path, d.target_file_path,
       d.import_name, d.import_type, d.package_name, d.package_version
FROM dependencies d
WHERE d.project_id = $1
  AND d.index_snapshot_id = $2
  AND d.source_file_path = $3
ORDER BY d.import_name
`

type ListDependenciesFromFileParams struct {
	ProjectID       pgtype.UUID `json:"project_id"`
	IndexSnapshotID pgtype.UUID `json:"index_snapshot_id"`
	SourceFilePath  string      `json:"source_file_path"`
}

type ListDependenciesFromFileRow struct {
	ID             pgtype.UUID `json:"id"`
	SourceFilePath string      `json:"source_file_path"`
	TargetFilePath pgtype.Text `json:"target_file_path"`
	ImportName     string      `json:"import_name"`
	ImportType     string      `json:"import_type"`
	PackageName    pgtype.Text `json:"package_name"`
	PackageVersion pgtype.Text `json:"package_version"`
}

// Forward: what does this file import?
func (q *Queries) ListDependenciesFromFile(ctx context.Context, arg ListDependenciesFromFileParams) ([]ListDependenciesFromFileRow, error) {
	rows, err := q.db.Query(ctx, listDependenciesFromFile, arg.ProjectID, arg.IndexSnapshotID, arg.SourceFilePath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDependenciesFromFileRow{}
	for rows.Next() {
		var i ListDependenciesFromFileRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceFilePath,
			&i.TargetFilePath,
			&i.ImportName,
			&i.ImportType,
			&i.PackageName,
			&i.PackageVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDependenciesFromFiles = `-- name: ListDependenciesFromFiles :many
SELECT d.id, d.source_file_path, d.target_file_path,
       d.import_name, d.import_type, d.package_name, d.package_version
FROM dependencies d
WHERE d.project_id = $1
  AND d.index_snapshot_id = $2
  AND d.source_file_path = ANY($3::text[])
ORDER BY d.source_file_path, d.import_name
`

type ListDependenciesFromFilesParams struct {
	ProjectID       pgtype.UUID `json:"project_id"`
	IndexSnapshotID pgtype.UUID `json:"index_snapshot_id"`
	Column3         []string    `json:"column_3"`
}

type ListDependenciesFromFilesRow struct {
	ID             pgtype.UUID `json:"id"`
	SourceFilePath string      `json:"source_file_path"`
	TargetFilePath pgtype.Text `json:"target_file_path"`
	ImportName     string      `json:"import_name"`
	ImportType     string      `json:"import_type"`
	PackageName    pgtype.Text `json:"package_name"`
	PackageVersion pgtype.Text `json:"package_version"`
}

// Batch forward lookup for BFS: all imports from a set of source files.
func (q *Queries) ListDependenciesFromFiles(ctx context.Context, arg ListDependenciesFromFilesParams) ([]ListDependenciesFromFilesRow, error) {
	rows, err := q.db.Query(ctx, listDependenciesFromFiles, arg.ProjectID, arg.IndexSnapshotID, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDependenciesFromFilesRow{}
	for rows.Next() {
		var i ListDependenciesFromFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceFilePath,
			&i.TargetFilePath,
			&i.ImportName,
			&i.ImportType,
			&i.PackageName,
			&i.PackageVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDependenciesToFile = `-- name: ListDependenciesToFile :many
SELECT d.id, d.source_file_path, d.target_file_path,
       d.import_name, d.import_type, d.package_name, d.package_version
FROM dependencies d
WHERE d.project_id = $1
  AND d.index_snapshot_id = $2
  AND d.target_file_path = $3
ORDER BY d.source_file_path, d.import_name
`

type ListDependenciesToFileParams struct {
	ProjectID       pgtype.UUID `json:"project_id"`
	IndexSnapshotID pgtype.UUID `json:"index_snapshot_id"`
	TargetFilePath  pgtype.Text `json:"target_file_path"`
}

type ListDependenciesToFileRow struct {
	ID             pgtype.UUID `json:"id"`
	SourceFilePath string      `json:"source_file_path"`
	TargetFilePath pgtype.Text `json:"target_file_path"`
	ImportName     string      `json:"import_name"`
	ImportType     string      `json:"import_type"`
	PackageName    pgtype.Text `json:"package_name"`
	PackageVersion pgtype.Text `json:"package_version"`
}

// Reverse: what imports this file?
func (q *Queries) ListDependenciesToFile(ctx context.Context, arg ListDependenciesToFileParams) ([]ListDependenciesToFileRow, error) {
	rows, err := q.db.Query(ctx, listDependenciesToFile, arg.ProjectID, arg.IndexSnapshotID, arg.TargetFilePath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDependenciesToFileRow{}
	for rows.Next() {
		var i ListDependenciesToFileRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceFilePath,
			&i.TargetFilePath,
			&i.ImportName,
			&i.ImportType,
			&i.PackageName,
			&i.PackageVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDependenciesToFiles = `-- name: ListDependenciesToFiles :many
SELECT d.id, d.source_file_path, d.target_file_path,
       d.import_name, d.import_type, d.package_name, d.package_version
FROM dependencies d
WHERE d.project_id = $1
  AND d.index_snapshot_id = $2
  AND d.target_file_path = ANY($3::text[])
ORDER BY d.target_file_path, d.source_file_path
`

type ListDependenciesToFilesParams struct {
	ProjectID       pgtype.UUID `json:"project_id"`
	IndexSnapshotID pgtype.UUID `json:"index_snapshot_id"`
	Column3         []string    `json:"column_3"`
}

type ListDependenciesToFilesRow struct {
	ID             pgtype.UUID `json:"id"`
	SourceFilePath string      `json:"source_file_path"`
	TargetFilePath pgtype.Text `json:"target_file_path"`
	ImportName     string      `json:"import_name"`
	ImportType     string      `json:"import_type"`
	PackageName    pgtype.Text `json:"package_name"`
	PackageVersion pgtype.Text `json:"package_version"`
}

// Batch reverse lookup for BFS: all files importing any of the given files.
func (q *Queries) ListDependenciesToFiles(ctx context.Context, arg ListDependenciesToFilesParams) ([]ListDependenciesToFilesRow, error) {
	rows, err := q.db.Query(ctx, listDependenciesToFiles, arg.ProjectID, arg.IndexSnapshotID, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDependenciesToFilesRow{}
	for rows.Next() {
		var i ListDependenciesToFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceFilePath,
			&i.TargetFilePath,
			&i.ImportName,
			&i.ImportType,
			&i.PackageName,
			&i.PackageVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalDependencies = `-- name: ListExternalDependencies :many
SELECT d.package_name, d.package_version,
       COUNT(*)::bigint AS import_count,
       COUNT(DISTINCT d.source_file_path)::bigint AS file_count
FROM dependencies d
WHERE d.project_id = $1
  AND d.index_snapshot_id = $2
  AND d.target_file_path IS NULL
  AND d.package_name IS NOT NULL
GROUP BY d.package_name, d.package_version
ORDER BY import_count DESC
`

type ListExternalDependenciesParams struct {
	ProjectID       pgtype.UUID `json:"project_id"`
	IndexSnapshotID pgtype.UUID `json:"index_snapshot_id"`
}

type ListExternalDependenciesRow struct {
	PackageName    pgtype.Text `json:"package_name"`
	PackageVersion pgtype.Text `json:"package_version"`
	ImportCount    int64       `json:"import_count"`
	FileCount      int64       `json:"file_count"`
}

// External packages: target_file_path IS NULL (unresolvable within project).
func (q *Queries) ListExternalDependencies(ctx context.Context, arg ListExternalDependenciesParams) ([]ListExternalDependenciesRow, error) {
	rows, err := q.db.Query(ctx, listExternalDependencies, arg.ProjectID, arg.IndexSnapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExternalDependenciesRow{}
	for rows.Next() {
		var i ListExternalDependenciesRow
		if err := rows.Scan(
			&i.PackageName,
			&i.PackageVersion,
			&i.ImportCount,
			&i.FileCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileDependencyCounts = `-- name: ListFileDependencyCounts :many
SELECT sub.file_path,
       SUM(sub.imports_count)::bigint AS imports_count,
       SUM(sub.imported_by_count)::bigint AS imported_by_count
FROM (
  SELECT d1.source_file_path AS file_path,
         COUNT(*)::bigint AS imports_count,
         0::bigint AS imported_by_count
  FROM dependencies d1
  WHERE d1.project_id = $1 AND d1.index_snapshot_id = $2
  GROUP BY d1.source_file_path

  UNION ALL

  SELECT d2.target_file_path AS file_path,
         0::bigint AS imports_count,
         COUNT(*)::bigint AS imported_by_count
  FROM dependencies d2
  WHERE d2.project_id = $1 AND d2.index_snapshot_id = $2
    AND d2.target_file_path IS NOT NULL
  GROUP BY d2.target_file_path
) sub
GROUP BY sub.file_path
ORDER BY sub.file_path
LIMIT $3 OFFSET $4
`

type ListFileDependencyCountsParams struct {
	ProjectID       pgtype.UUID `json:"project_id"`
	IndexSnapshotID pgtype.UUID `json:"index_snapshot_id"`
	Limit           int32       `json:"limit"`
	Offset          int32       `json:"offset"`
}

type ListFileDependencyCountsRow struct {
	FilePath        string `json:"file_path"`
	ImportsCount    int64  `json:"imports_count"`
	ImportedByCount int64  `json:"imported_by_count"`
}

// Per-file aggregate: how many imports and how many importers.
func (q *Queries) ListFileDependencyCounts(ctx context.Context, arg ListFileDependencyCountsParams) ([]ListFileDependencyCountsRow, error) {
	rows, err := q.db.Query(ctx, listFileDependencyCounts,
		arg.ProjectID,
		arg.IndexSnapshotID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFileDependencyCountsRow{}
	for rows.Next() {
		var i ListFileDependencyCountsRow
		if err := rows.Scan(&i.FilePath, &i.ImportsCount, &i.ImportedByCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
