// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertExport = `-- name: InsertExport :one
INSERT INTO exports (
  project_id, index_snapshot_id, file_id, export_kind, exported_name,
  local_name, symbol_id, source_module, line, "column"
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, project_id, index_snapshot_id, file_id, export_kind, exported_name, local_name, symbol_id, source_module, line, "column", created_at
`

type InsertExportParams struct {
	ProjectID       pgtype.UUID `json:"project_id"`
	IndexSnapshotID pgtype.UUID `json:"index_snapshot_id"`
	FileID          pgtype.UUID `json:"file_id"`
	ExportKind      string      `json:"export_kind"`
	ExportedName    string      `json:"exported_name"`
	LocalName       pgtype.Text `json:"local_name"`
	SymbolID        pgtype.UUID `json:"symbol_id"`
	SourceModule    pgtype.Text `json:"source_module"`
	Line            int32       `json:"line"`
	Column          int32       `json:"column"`
}

func (q *Queries) InsertExport(ctx context.Context, arg InsertExportParams) (Export, error) {
	row := q.db.QueryRow(ctx, insertExport,
		arg.ProjectID,
		arg.IndexSnapshotID,
		arg.FileID,
		arg.ExportKind,
		arg.ExportedName,
		arg.LocalName,
		arg.SymbolID,
		arg.SourceModule,
		arg.Line,
		arg.Column,
	)
	var i Export
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IndexSnapshotID,
		&i.FileID,
		&i.ExportKind,
		&i.ExportedName,
		&i.LocalName,
		&i.SymbolID,
		&i.SourceModule,
		&i.Line,
		&i.Column,
		&i.CreatedAt,
	)
	return i, err
}

const listExportsByFileID = `-- name: ListExportsByFileID :many
SELECT id, project_id, index_snapshot_id, file_id, export_kind, exported_name, local_name, symbol_id, source_module, line, "column", created_at FROM exports WHERE file_id = $1 ORDER BY line
`

func (q *Queries) ListExportsByFileID(ctx context.Context, fileID pgtype.UUID) ([]Export, error) {
	rows, err := q.db.Query(ctx, listExportsByFileID, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Export{}
	for rows.Next() {
		var i Export
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IndexSnapshotID,
			&i.FileID,
			&i.ExportKind,
			&i.ExportedName,
			&i.LocalName,
			&i.SymbolID,
			&i.SourceModule,
			&i.Line,
			&i.Column,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
