// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveSnapshotForBranch = `-- name: GetActiveSnapshotForBranch :one
SELECT id, project_id, branch, embedding_version_id, git_commit, is_active, status, created_at, activated_at, commit_id
FROM index_snapshots
WHERE project_id = $1 AND branch = $2 AND is_active = TRUE
LIMIT 1
`

type GetActiveSnapshotForBranchParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Branch    string      `json:"branch"`
}

func (q *Queries) GetActiveSnapshotForBranch(ctx context.Context, arg GetActiveSnapshotForBranchParams) (IndexSnapshot, error) {
	row := q.db.QueryRow(ctx, getActiveSnapshotForBranch, arg.ProjectID, arg.Branch)
	var i IndexSnapshot
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Branch,
		&i.EmbeddingVersionID,
		&i.GitCommit,
		&i.IsActive,
		&i.Status,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.CommitID,
	)
	return i, err
}

const getActiveSnapshotForProject = `-- name: GetActiveSnapshotForProject :one
SELECT id, project_id, branch, embedding_version_id, git_commit, is_active, status, created_at, activated_at, commit_id
FROM index_snapshots
WHERE project_id = $1 AND is_active = TRUE
ORDER BY activated_at DESC NULLS LAST, id DESC
LIMIT 1
`

func (q *Queries) GetActiveSnapshotForProject(ctx context.Context, projectID pgtype.UUID) (IndexSnapshot, error) {
	row := q.db.QueryRow(ctx, getActiveSnapshotForProject, projectID)
	var i IndexSnapshot
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Branch,
		&i.EmbeddingVersionID,
		&i.GitCommit,
		&i.IsActive,
		&i.Status,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.CommitID,
	)
	return i, err
}

const getFileBySnapshotAndPath = `-- name: GetFileBySnapshotAndPath :one
SELECT id FROM files WHERE index_snapshot_id = $1 AND file_path = $2
`

type GetFileBySnapshotAndPathParams struct {
	IndexSnapshotID pgtype.UUID `json:"index_snapshot_id"`
	FilePath        string      `json:"file_path"`
}

func (q *Queries) GetFileBySnapshotAndPath(ctx context.Context, arg GetFileBySnapshotAndPathParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getFileBySnapshotAndPath, arg.IndexSnapshotID, arg.FilePath)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getFileWithContent = `-- name: GetFileWithContent :one
SELECT
  f.id,
  f.file_path,
  f.language,
  f.file_hash,
  fc.size_bytes,
  fc.line_count,
  fc.content,
  fc.content_hash,
  f.file_facts,
  f.issues,
  f.parser_meta,
  f.extractor_statuses
FROM files f
LEFT JOIN file_contents fc ON fc.id = f.file_content_id
WHERE f.index_snapshot_id = $1 AND f.file_path = $2
`

type GetFileWithContentParams struct {
	IndexSnapshotID pgtype.UUID `json:"index_snapshot_id"`
	FilePath        string      `json:"file_path"`
}

type GetFileWithContentRow struct {
	ID                pgtype.UUID `json:"id"`
	FilePath          string      `json:"file_path"`
	Language          pgtype.Text `json:"language"`
	FileHash          string      `json:"file_hash"`
	SizeBytes         pgtype.Int8 `json:"size_bytes"`
	LineCount         pgtype.Int4 `json:"line_count"`
	Content           pgtype.Text `json:"content"`
	ContentHash       pgtype.Text `json:"content_hash"`
	FileFacts         []byte      `json:"file_facts"`
	Issues            []byte      `json:"issues"`
	ParserMeta        []byte      `json:"parser_meta"`
	ExtractorStatuses []byte      `json:"extractor_statuses"`
}

func (q *Queries) GetFileWithContent(ctx context.Context, arg GetFileWithContentParams) (GetFileWithContentRow, error) {
	row := q.db.QueryRow(ctx, getFileWithContent, arg.IndexSnapshotID, arg.FilePath)
	var i GetFileWithContentRow
	err := row.Scan(
		&i.ID,
		&i.FilePath,
		&i.Language,
		&i.FileHash,
		&i.SizeBytes,
		&i.LineCount,
		&i.Content,
		&i.ContentHash,
		&i.FileFacts,
		&i.Issues,
		&i.ParserMeta,
		&i.ExtractorStatuses,
	)
	return i, err
}

const getFileWithContentAndAST = `-- name: GetFileWithContentAndAST :one
SELECT
  f.id,
  f.file_path,
  f.language,
  f.file_hash,
  fc.size_bytes,
  fc.line_count,
  fc.content,
  fc.tree_sitter_ast,
  fc.content_hash,
  f.file_facts,
  f.issues,
  f.parser_meta,
  f.extractor_statuses
FROM files f
LEFT JOIN file_contents fc ON fc.id = f.file_content_id
WHERE f.index_snapshot_id = $1 AND f.file_path = $2
`

type GetFileWithContentAndASTParams struct {
	IndexSnapshotID pgtype.UUID `json:"index_snapshot_id"`
	FilePath        string      `json:"file_path"`
}

type GetFileWithContentAndASTRow struct {
	ID                pgtype.UUID `json:"id"`
	FilePath          string      `json:"file_path"`
	Language          pgtype.Text `json:"language"`
	FileHash          string      `json:"file_hash"`
	SizeBytes         pgtype.Int8 `json:"size_bytes"`
	LineCount         pgtype.Int4 `json:"line_count"`
	Content           pgtype.Text `json:"content"`
	TreeSitterAst     []byte      `json:"tree_sitter_ast"`
	ContentHash       pgtype.Text `json:"content_hash"`
	FileFacts         []byte      `json:"file_facts"`
	Issues            []byte      `json:"issues"`
	ParserMeta        []byte      `json:"parser_meta"`
	ExtractorStatuses []byte      `json:"extractor_statuses"`
}

func (q *Queries) GetFileWithContentAndAST(ctx context.Context, arg GetFileWithContentAndASTParams) (GetFileWithContentAndASTRow, error) {
	row := q.db.QueryRow(ctx, getFileWithContentAndAST, arg.IndexSnapshotID, arg.FilePath)
	var i GetFileWithContentAndASTRow
	err := row.Scan(
		&i.ID,
		&i.FilePath,
		&i.Language,
		&i.FileHash,
		&i.SizeBytes,
		&i.LineCount,
		&i.Content,
		&i.TreeSitterAst,
		&i.ContentHash,
		&i.FileFacts,
		&i.Issues,
		&i.ParserMeta,
		&i.ExtractorStatuses,
	)
	return i, err
}

const listSnapshotFiles = `-- name: ListSnapshotFiles :many
SELECT id, project_id, index_snapshot_id, file_path, language, file_hash, size_bytes, line_count, file_facts, parser_meta, extractor_statuses, issues, updated_at, file_content_id
FROM files
WHERE index_snapshot_id = $1
ORDER BY file_path
`

func (q *Queries) ListSnapshotFiles(ctx context.Context, indexSnapshotID pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, listSnapshotFiles, indexSnapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IndexSnapshotID,
			&i.FilePath,
			&i.Language,
			&i.FileHash,
			&i.SizeBytes,
			&i.LineCount,
			&i.FileFacts,
			&i.ParserMeta,
			&i.ExtractorStatuses,
			&i.Issues,
			&i.UpdatedAt,
			&i.FileContentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
