// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: indexing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateSnapshot = `-- name: ActivateSnapshot :exec
UPDATE index_snapshots
SET
  is_active = TRUE,
  status = 'active',
  activated_at = NOW()
WHERE id = $1
`

func (q *Queries) ActivateSnapshot(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, activateSnapshot, id)
	return err
}

const claimQueuedIndexingJob = `-- name: ClaimQueuedIndexingJob :execrows
UPDATE indexing_jobs
SET
  status = 'running',
  started_at = NOW(),
  worker_id = $1
WHERE id = $2
  AND status = 'queued'
`

type ClaimQueuedIndexingJobParams struct {
	WorkerID pgtype.Text `json:"worker_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) ClaimQueuedIndexingJob(ctx context.Context, arg ClaimQueuedIndexingJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimQueuedIndexingJob, arg.WorkerID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActiveJobsForUser = `-- name: CountActiveJobsForUser :one
SELECT COUNT(*)::bigint AS total
FROM indexing_jobs ij
JOIN project_members pm ON pm.project_id = ij.project_id
WHERE pm.user_id = $1
  AND ij.status IN ('queued', 'running')
`

func (q *Queries) CountActiveJobsForUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveJobsForUser, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countFailedJobsForUser24h = `-- name: CountFailedJobsForUser24h :one
SELECT COUNT(*)::bigint AS total
FROM indexing_jobs ij
JOIN project_members pm ON pm.project_id = ij.project_id
WHERE pm.user_id = $1
  AND ij.status = 'failed'
  AND ij.finished_at >= NOW() - INTERVAL '24 hours'
`

func (q *Queries) CountFailedJobsForUser24h(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFailedJobsForUser24h, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countProjectJobs = `-- name: CountProjectJobs :one
SELECT COUNT(*)::bigint AS total
FROM indexing_jobs
WHERE project_id = $1
`

func (q *Queries) CountProjectJobs(ctx context.Context, projectID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectJobs, projectID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createIndexSnapshot = `-- name: CreateIndexSnapshot :one
INSERT INTO index_snapshots (
  project_id,
  branch,
  embedding_version_id,
  git_commit,
  is_active,
  status
) VALUES ($1, $2, $3, $4, FALSE, 'building')
ON CONFLICT (project_id, branch, embedding_version_id, git_commit)
DO UPDATE SET status = 'building', is_active = FALSE, activated_at = NULL
RETURNING id, project_id, branch, embedding_version_id, git_commit, is_active, status, created_at, activated_at, commit_id
`

type CreateIndexSnapshotParams struct {
	ProjectID          pgtype.UUID `json:"project_id"`
	Branch             string      `json:"branch"`
	EmbeddingVersionID pgtype.UUID `json:"embedding_version_id"`
	GitCommit          string      `json:"git_commit"`
}

func (q *Queries) CreateIndexSnapshot(ctx context.Context, arg CreateIndexSnapshotParams) (IndexSnapshot, error) {
	row := q.db.QueryRow(ctx, createIndexSnapshot,
		arg.ProjectID,
		arg.Branch,
		arg.EmbeddingVersionID,
		arg.GitCommit,
	)
	var i IndexSnapshot
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Branch,
		&i.EmbeddingVersionID,
		&i.GitCommit,
		&i.IsActive,
		&i.Status,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.CommitID,
	)
	return i, err
}

const createIndexingJob = `-- name: CreateIndexingJob :one
INSERT INTO indexing_jobs (
  project_id,
  index_snapshot_id,
  job_type,
  status,
  embedding_provider_config_id,
  llm_provider_config_id
) VALUES ($1, $2, $3, 'queued', $4, $5)
RETURNING id, project_id, index_snapshot_id, job_type, status, files_processed, chunks_upserted, vectors_deleted, error_details, embedding_provider_config_id, llm_provider_config_id, worker_id, started_at, finished_at, created_at
`

type CreateIndexingJobParams struct {
	ProjectID                 pgtype.UUID `json:"project_id"`
	IndexSnapshotID           pgtype.UUID `json:"index_snapshot_id"`
	JobType                   string      `json:"job_type"`
	EmbeddingProviderConfigID pgtype.UUID `json:"embedding_provider_config_id"`
	LlmProviderConfigID       pgtype.UUID `json:"llm_provider_config_id"`
}

func (q *Queries) CreateIndexingJob(ctx context.Context, arg CreateIndexingJobParams) (IndexingJob, error) {
	row := q.db.QueryRow(ctx, createIndexingJob,
		arg.ProjectID,
		arg.IndexSnapshotID,
		arg.JobType,
		arg.EmbeddingProviderConfigID,
		arg.LlmProviderConfigID,
	)
	var i IndexingJob
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IndexSnapshotID,
		&i.JobType,
		&i.Status,
		&i.FilesProcessed,
		&i.ChunksUpserted,
		&i.VectorsDeleted,
		&i.ErrorDetails,
		&i.EmbeddingProviderConfigID,
		&i.LlmProviderConfigID,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateActiveSnapshot = `-- name: DeactivateActiveSnapshot :exec
UPDATE index_snapshots
SET is_active = FALSE
WHERE project_id = $1
  AND branch = $2
  AND is_active = TRUE
`

type DeactivateActiveSnapshotParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Branch    string      `json:"branch"`
}

func (q *Queries) DeactivateActiveSnapshot(ctx context.Context, arg DeactivateActiveSnapshotParams) error {
	_, err := q.db.Exec(ctx, deactivateActiveSnapshot, arg.ProjectID, arg.Branch)
	return err
}

const deleteOrphanedBuildingSnapshot = `-- name: DeleteOrphanedBuildingSnapshot :exec
DELETE FROM index_snapshots
WHERE id = $1
  AND status = 'building'
  AND is_active = FALSE
`

func (q *Queries) DeleteOrphanedBuildingSnapshot(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrphanedBuildingSnapshot, id)
	return err
}

const deleteSnapshotArtifacts = `-- name: DeleteSnapshotArtifacts :exec
DELETE FROM files WHERE index_snapshot_id = $1
`

func (q *Queries) DeleteSnapshotArtifacts(ctx context.Context, indexSnapshotID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSnapshotArtifacts, indexSnapshotID)
	return err
}

const failStaleJob = `-- name: FailStaleJob :execrows
UPDATE indexing_jobs
SET
  status = 'failed',
  error_details = $1,
  finished_at = NOW()
WHERE id = $2
  AND status = 'running'
`

type FailStaleJobParams struct {
	ErrorDetails []byte      `json:"error_details"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) FailStaleJob(ctx context.Context, arg FailStaleJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, failStaleJob, arg.ErrorDetails, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findActiveIndexingJobForProjectAndType = `-- name: FindActiveIndexingJobForProjectAndType :one
SELECT id, project_id, index_snapshot_id, job_type, status, files_processed, chunks_upserted, vectors_deleted, error_details, embedding_provider_config_id, llm_provider_config_id, worker_id, started_at, finished_at, created_at
FROM indexing_jobs
WHERE project_id = $1
  AND job_type = $2
  AND status IN ('queued', 'running')
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type FindActiveIndexingJobForProjectAndTypeParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	JobType   string      `json:"job_type"`
}

func (q *Queries) FindActiveIndexingJobForProjectAndType(ctx context.Context, arg FindActiveIndexingJobForProjectAndTypeParams) (IndexingJob, error) {
	row := q.db.QueryRow(ctx, findActiveIndexingJobForProjectAndType, arg.ProjectID, arg.JobType)
	var i IndexingJob
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IndexSnapshotID,
		&i.JobType,
		&i.Status,
		&i.FilesProcessed,
		&i.ChunksUpserted,
		&i.VectorsDeleted,
		&i.ErrorDetails,
		&i.EmbeddingProviderConfigID,
		&i.LlmProviderConfigID,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getIndexSnapshot = `-- name: GetIndexSnapshot :one
SELECT id, project_id, branch, embedding_version_id, git_commit, is_active, status, created_at, activated_at, commit_id FROM index_snapshots WHERE id = $1
`

func (q *Queries) GetIndexSnapshot(ctx context.Context, id pgtype.UUID) (IndexSnapshot, error) {
	row := q.db.QueryRow(ctx, getIndexSnapshot, id)
	var i IndexSnapshot
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Branch,
		&i.EmbeddingVersionID,
		&i.GitCommit,
		&i.IsActive,
		&i.Status,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.CommitID,
	)
	return i, err
}

const getIndexingJob = `-- name: GetIndexingJob :one
SELECT id, project_id, index_snapshot_id, job_type, status, files_processed, chunks_upserted, vectors_deleted, error_details, embedding_provider_config_id, llm_provider_config_id, worker_id, started_at, finished_at, created_at FROM indexing_jobs WHERE id = $1
`

func (q *Queries) GetIndexingJob(ctx context.Context, id pgtype.UUID) (IndexingJob, error) {
	row := q.db.QueryRow(ctx, getIndexingJob, id)
	var i IndexingJob
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IndexSnapshotID,
		&i.JobType,
		&i.Status,
		&i.FilesProcessed,
		&i.ChunksUpserted,
		&i.VectorsDeleted,
		&i.ErrorDetails,
		&i.EmbeddingProviderConfigID,
		&i.LlmProviderConfigID,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getQueryStats24hForUser = `-- name: GetQueryStats24hForUser :one
SELECT
  COUNT(*)::bigint AS query_count,
  COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY ql.latency_ms), 0)::bigint AS p95_latency_ms
FROM query_log ql
JOIN project_members pm ON pm.project_id = ql.project_id
WHERE pm.user_id = $1
  AND ql.created_at >= NOW() - INTERVAL '24 hours'
`

type GetQueryStats24hForUserRow struct {
	QueryCount   int64 `json:"query_count"`
	P95LatencyMs int64 `json:"p95_latency_ms"`
}

func (q *Queries) GetQueryStats24hForUser(ctx context.Context, userID pgtype.UUID) (GetQueryStats24hForUserRow, error) {
	row := q.db.QueryRow(ctx, getQueryStats24hForUser, userID)
	var i GetQueryStats24hForUserRow
	err := row.Scan(&i.QueryCount, &i.P95LatencyMs)
	return i, err
}

const insertCodeChunk = `-- name: InsertCodeChunk :one
INSERT INTO code_chunks (
  project_id, index_snapshot_id, file_id, symbol_id, chunk_type,
  chunk_hash, content, context_before, context_after, start_line,
  end_line, estimated_tokens,
  owner_qualified_name, owner_kind, is_exported_context, semantic_role
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, project_id, index_snapshot_id, file_id, symbol_id, chunk_type, chunk_hash, content, context_before, context_after, start_line, end_line, estimated_tokens, owner_qualified_name, owner_kind, is_exported_context, semantic_role, created_at
`

type InsertCodeChunkParams struct {
	ProjectID          pgtype.UUID `json:"project_id"`
	IndexSnapshotID    pgtype.UUID `json:"index_snapshot_id"`
	FileID             pgtype.UUID `json:"file_id"`
	SymbolID           pgtype.UUID `json:"symbol_id"`
	ChunkType          string      `json:"chunk_type"`
	ChunkHash          string      `json:"chunk_hash"`
	Content            string      `json:"content"`
	ContextBefore      pgtype.Text `json:"context_before"`
	ContextAfter       pgtype.Text `json:"context_after"`
	StartLine          int32       `json:"start_line"`
	EndLine            int32       `json:"end_line"`
	EstimatedTokens    pgtype.Int4 `json:"estimated_tokens"`
	OwnerQualifiedName pgtype.Text `json:"owner_qualified_name"`
	OwnerKind          pgtype.Text `json:"owner_kind"`
	IsExportedContext  bool        `json:"is_exported_context"`
	SemanticRole       pgtype.Text `json:"semantic_role"`
}

func (q *Queries) InsertCodeChunk(ctx context.Context, arg InsertCodeChunkParams) (CodeChunk, error) {
	row := q.db.QueryRow(ctx, insertCodeChunk,
		arg.ProjectID,
		arg.IndexSnapshotID,
		arg.FileID,
		arg.SymbolID,
		arg.ChunkType,
		arg.ChunkHash,
		arg.Content,
		arg.ContextBefore,
		arg.ContextAfter,
		arg.StartLine,
		arg.EndLine,
		arg.EstimatedTokens,
		arg.OwnerQualifiedName,
		arg.OwnerKind,
		arg.IsExportedContext,
		arg.SemanticRole,
	)
	var i CodeChunk
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IndexSnapshotID,
		&i.FileID,
		&i.SymbolID,
		&i.ChunkType,
		&i.ChunkHash,
		&i.Content,
		&i.ContextBefore,
		&i.ContextAfter,
		&i.StartLine,
		&i.EndLine,
		&i.EstimatedTokens,
		&i.OwnerQualifiedName,
		&i.OwnerKind,
		&i.IsExportedContext,
		&i.SemanticRole,
		&i.CreatedAt,
	)
	return i, err
}

const insertDependency = `-- name: InsertDependency :one
INSERT INTO dependencies (
  project_id, index_snapshot_id, source_symbol_id, source_file_path,
  target_file_path, import_name, import_type, package_name,
  package_version
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, index_snapshot_id, source_symbol_id, source_file_path, target_file_path, import_name, import_type, package_name, package_version
`

type InsertDependencyParams struct {
	ProjectID       pgtype.UUID `json:"project_id"`
	IndexSnapshotID pgtype.UUID `json:"index_snapshot_id"`
	SourceSymbolID  pgtype.UUID `json:"source_symbol_id"`
	SourceFilePath  string      `json:"source_file_path"`
	TargetFilePath  pgtype.Text `json:"target_file_path"`
	ImportName      string      `json:"import_name"`
	ImportType      string      `json:"import_type"`
	PackageName     pgtype.Text `json:"package_name"`
	PackageVersion  pgtype.Text `json:"package_version"`
}

func (q *Queries) InsertDependency(ctx context.Context, arg InsertDependencyParams) (Dependency, error) {
	row := q.db.QueryRow(ctx, insertDependency,
		arg.ProjectID,
		arg.IndexSnapshotID,
		arg.SourceSymbolID,
		arg.SourceFilePath,
		arg.TargetFilePath,
		arg.ImportName,
		arg.ImportType,
		arg.PackageName,
		arg.PackageVersion,
	)
	var i Dependency
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IndexSnapshotID,
		&i.SourceSymbolID,
		&i.SourceFilePath,
		&i.TargetFilePath,
		&i.ImportName,
		&i.ImportType,
		&i.PackageName,
		&i.PackageVersion,
	)
	return i, err
}

const insertFile = `-- name: InsertFile :one
INSERT INTO files (
  project_id, index_snapshot_id, file_path, language, file_hash,
  size_bytes, line_count, file_content_id,
  file_facts, parser_meta, extractor_statuses, issues
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, project_id, index_snapshot_id, file_path, language, file_hash, size_bytes, line_count, file_facts, parser_meta, extractor_statuses, issues, updated_at, file_content_id
`

type InsertFileParams struct {
	ProjectID         pgtype.UUID `json:"project_id"`
	IndexSnapshotID   pgtype.UUID `json:"index_snapshot_id"`
	FilePath          string      `json:"file_path"`
	Language          pgtype.Text `json:"language"`
	FileHash          string      `json:"file_hash"`
	SizeBytes         pgtype.Int8 `json:"size_bytes"`
	LineCount         pgtype.Int4 `json:"line_count"`
	FileContentID     pgtype.UUID `json:"file_content_id"`
	FileFacts         []byte      `json:"file_facts"`
	ParserMeta        []byte      `json:"parser_meta"`
	ExtractorStatuses []byte      `json:"extractor_statuses"`
	Issues            []byte      `json:"issues"`
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) (File, error) {
	row := q.db.QueryRow(ctx, insertFile,
		arg.ProjectID,
		arg.IndexSnapshotID,
		arg.FilePath,
		arg.Language,
		arg.FileHash,
		arg.SizeBytes,
		arg.LineCount,
		arg.FileContentID,
		arg.FileFacts,
		arg.ParserMeta,
		arg.ExtractorStatuses,
		arg.Issues,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IndexSnapshotID,
		&i.FilePath,
		&i.Language,
		&i.FileHash,
		&i.SizeBytes,
		&i.LineCount,
		&i.FileFacts,
		&i.ParserMeta,
		&i.ExtractorStatuses,
		&i.Issues,
		&i.UpdatedAt,
		&i.FileContentID,
	)
	return i, err
}

const insertSymbol = `-- name: InsertSymbol :one
INSERT INTO symbols (
  project_id, index_snapshot_id, file_id, name, qualified_name,
  kind, signature, start_line, end_line, doc_text, symbol_hash,
  parent_symbol_id,
  flags, modifiers, return_type, parameter_types
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, project_id, index_snapshot_id, file_id, name, qualified_name, kind, signature, start_line, end_line, doc_text, symbol_hash, parent_symbol_id, flags, modifiers, return_type, parameter_types, created_at
`

type InsertSymbolParams struct {
	ProjectID       pgtype.UUID `json:"project_id"`
	IndexSnapshotID pgtype.UUID `json:"index_snapshot_id"`
	FileID          pgtype.UUID `json:"file_id"`
	Name            string      `json:"name"`
	QualifiedName   pgtype.Text `json:"qualified_name"`
	Kind            string      `json:"kind"`
	Signature       pgtype.Text `json:"signature"`
	StartLine       pgtype.Int4 `json:"start_line"`
	EndLine         pgtype.Int4 `json:"end_line"`
	DocText         pgtype.Text `json:"doc_text"`
	SymbolHash      string      `json:"symbol_hash"`
	ParentSymbolID  pgtype.UUID `json:"parent_symbol_id"`
	Flags           []byte      `json:"flags"`
	Modifiers       []string    `json:"modifiers"`
	ReturnType      pgtype.Text `json:"return_type"`
	ParameterTypes  []string    `json:"parameter_types"`
}

func (q *Queries) InsertSymbol(ctx context.Context, arg InsertSymbolParams) (Symbol, error) {
	row := q.db.QueryRow(ctx, insertSymbol,
		arg.ProjectID,
		arg.IndexSnapshotID,
		arg.FileID,
		arg.Name,
		arg.QualifiedName,
		arg.Kind,
		arg.Signature,
		arg.StartLine,
		arg.EndLine,
		arg.DocText,
		arg.SymbolHash,
		arg.ParentSymbolID,
		arg.Flags,
		arg.Modifiers,
		arg.ReturnType,
		arg.ParameterTypes,
	)
	var i Symbol
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IndexSnapshotID,
		&i.FileID,
		&i.Name,
		&i.QualifiedName,
		&i.Kind,
		&i.Signature,
		&i.StartLine,
		&i.EndLine,
		&i.DocText,
		&i.SymbolHash,
		&i.ParentSymbolID,
		&i.Flags,
		&i.Modifiers,
		&i.ReturnType,
		&i.ParameterTypes,
		&i.CreatedAt,
	)
	return i, err
}

const listChunksByFileID = `-- name: ListChunksByFileID :many
SELECT id, project_id, index_snapshot_id, file_id, symbol_id, chunk_type, chunk_hash, content, context_before, context_after, start_line, end_line, estimated_tokens, owner_qualified_name, owner_kind, is_exported_context, semantic_role, created_at FROM code_chunks WHERE file_id = $1 ORDER BY start_line
`

func (q *Queries) ListChunksByFileID(ctx context.Context, fileID pgtype.UUID) ([]CodeChunk, error) {
	rows, err := q.db.Query(ctx, listChunksByFileID, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CodeChunk{}
	for rows.Next() {
		var i CodeChunk
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IndexSnapshotID,
			&i.FileID,
			&i.SymbolID,
			&i.ChunkType,
			&i.ChunkHash,
			&i.Content,
			&i.ContextBefore,
			&i.ContextAfter,
			&i.StartLine,
			&i.EndLine,
			&i.EstimatedTokens,
			&i.OwnerQualifiedName,
			&i.OwnerKind,
			&i.IsExportedContext,
			&i.SemanticRole,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDependenciesBySnapshotAndFile = `-- name: ListDependenciesBySnapshotAndFile :many
SELECT id, project_id, index_snapshot_id, source_symbol_id, source_file_path, target_file_path, import_name, import_type, package_name, package_version FROM dependencies
WHERE index_snapshot_id = $1 AND source_file_path = $2
`

type ListDependenciesBySnapshotAndFileParams struct {
	IndexSnapshotID pgtype.UUID `json:"index_snapshot_id"`
	SourceFilePath  string      `json:"source_file_path"`
}

func (q *Queries) ListDependenciesBySnapshotAndFile(ctx context.Context, arg ListDependenciesBySnapshotAndFileParams) ([]Dependency, error) {
	rows, err := q.db.Query(ctx, listDependenciesBySnapshotAndFile, arg.IndexSnapshotID, arg.SourceFilePath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dependency{}
	for rows.Next() {
		var i Dependency
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IndexSnapshotID,
			&i.SourceSymbolID,
			&i.SourceFilePath,
			&i.TargetFilePath,
			&i.ImportName,
			&i.ImportType,
			&i.PackageName,
			&i.PackageVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectJobs = `-- name: ListProjectJobs :many
SELECT id, project_id, index_snapshot_id, job_type, status, files_processed, chunks_upserted, vectors_deleted, error_details, embedding_provider_config_id, llm_provider_config_id, worker_id, started_at, finished_at, created_at
FROM indexing_jobs
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProjectJobsParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListProjectJobs(ctx context.Context, arg ListProjectJobsParams) ([]IndexingJob, error) {
	rows, err := q.db.Query(ctx, listProjectJobs, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IndexingJob{}
	for rows.Next() {
		var i IndexingJob
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IndexSnapshotID,
			&i.JobType,
			&i.Status,
			&i.FilesProcessed,
			&i.ChunksUpserted,
			&i.VectorsDeleted,
			&i.ErrorDetails,
			&i.EmbeddingProviderConfigID,
			&i.LlmProviderConfigID,
			&i.WorkerID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSymbolsByFileID = `-- name: ListSymbolsByFileID :many
SELECT id, project_id, index_snapshot_id, file_id, name, qualified_name, kind, signature, start_line, end_line, doc_text, symbol_hash, parent_symbol_id, flags, modifiers, return_type, parameter_types, created_at FROM symbols WHERE file_id = $1 ORDER BY start_line
`

func (q *Queries) ListSymbolsByFileID(ctx context.Context, fileID pgtype.UUID) ([]Symbol, error) {
	rows, err := q.db.Query(ctx, listSymbolsByFileID, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Symbol{}
	for rows.Next() {
		var i Symbol
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IndexSnapshotID,
			&i.FileID,
			&i.Name,
			&i.QualifiedName,
			&i.Kind,
			&i.Signature,
			&i.StartLine,
			&i.EndLine,
			&i.DocText,
			&i.SymbolHash,
			&i.ParentSymbolID,
			&i.Flags,
			&i.Modifiers,
			&i.ReturnType,
			&i.ParameterTypes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseAdvisoryLockForProject = `-- name: ReleaseAdvisoryLockForProject :one
SELECT pg_advisory_unlock($1::int, $2::int)::boolean AS released
`

type ReleaseAdvisoryLockForProjectParams struct {
	Column1 int32 `json:"column_1"`
	Column2 int32 `json:"column_2"`
}

func (q *Queries) ReleaseAdvisoryLockForProject(ctx context.Context, arg ReleaseAdvisoryLockForProjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, releaseAdvisoryLockForProject, arg.Column1, arg.Column2)
	var released bool
	err := row.Scan(&released)
	return released, err
}

const setIndexingJobCompleted = `-- name: SetIndexingJobCompleted :exec
UPDATE indexing_jobs
SET
  status = 'completed',
  finished_at = NOW()
WHERE id = $1
`

func (q *Queries) SetIndexingJobCompleted(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setIndexingJobCompleted, id)
	return err
}

const setIndexingJobCompletedFromRunning = `-- name: SetIndexingJobCompletedFromRunning :execrows
UPDATE indexing_jobs
SET
  status = 'completed',
  finished_at = NOW()
WHERE id = $1
  AND status = 'running'
`

func (q *Queries) SetIndexingJobCompletedFromRunning(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, setIndexingJobCompletedFromRunning, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setIndexingJobFailed = `-- name: SetIndexingJobFailed :exec
UPDATE indexing_jobs
SET
  status = 'failed',
  error_details = $2,
  finished_at = NOW()
WHERE id = $1
`

type SetIndexingJobFailedParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorDetails []byte      `json:"error_details"`
}

func (q *Queries) SetIndexingJobFailed(ctx context.Context, arg SetIndexingJobFailedParams) error {
	_, err := q.db.Exec(ctx, setIndexingJobFailed, arg.ID, arg.ErrorDetails)
	return err
}

const setIndexingJobFailedFromRunning = `-- name: SetIndexingJobFailedFromRunning :execrows
UPDATE indexing_jobs
SET
  status = 'failed',
  error_details = $2,
  finished_at = NOW()
WHERE id = $1
  AND status = 'running'
`

type SetIndexingJobFailedFromRunningParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorDetails []byte      `json:"error_details"`
}

func (q *Queries) SetIndexingJobFailedFromRunning(ctx context.Context, arg SetIndexingJobFailedFromRunningParams) (int64, error) {
	result, err := q.db.Exec(ctx, setIndexingJobFailedFromRunning, arg.ID, arg.ErrorDetails)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setIndexingJobProgress = `-- name: SetIndexingJobProgress :exec
UPDATE indexing_jobs
SET
  files_processed = $2,
  chunks_upserted = $3,
  vectors_deleted = $4
WHERE id = $1
`

type SetIndexingJobProgressParams struct {
	ID             pgtype.UUID `json:"id"`
	FilesProcessed int32       `json:"files_processed"`
	ChunksUpserted int32       `json:"chunks_upserted"`
	VectorsDeleted int32       `json:"vectors_deleted"`
}

func (q *Queries) SetIndexingJobProgress(ctx context.Context, arg SetIndexingJobProgressParams) error {
	_, err := q.db.Exec(ctx, setIndexingJobProgress,
		arg.ID,
		arg.FilesProcessed,
		arg.ChunksUpserted,
		arg.VectorsDeleted,
	)
	return err
}

const setIndexingJobRunning = `-- name: SetIndexingJobRunning :exec
UPDATE indexing_jobs
SET
  status = 'running',
  started_at = NOW()
WHERE id = $1
`

func (q *Queries) SetIndexingJobRunning(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setIndexingJobRunning, id)
	return err
}

const tryAdvisoryLockForProject = `-- name: TryAdvisoryLockForProject :one
SELECT pg_try_advisory_lock($1::int, $2::int)::boolean AS acquired
`

type TryAdvisoryLockForProjectParams struct {
	Column1 int32 `json:"column_1"`
	Column2 int32 `json:"column_2"`
}

// Uses two int4 keys derived from the UUID to avoid hashtext collisions.
func (q *Queries) TryAdvisoryLockForProject(ctx context.Context, arg TryAdvisoryLockForProjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, tryAdvisoryLockForProject, arg.Column1, arg.Column2)
	var acquired bool
	err := row.Scan(&acquired)
	return acquired, err
}
