// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jsx_usages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertJsxUsage = `-- name: InsertJsxUsage :one
INSERT INTO jsx_usages (
  project_id, index_snapshot_id, file_id, source_symbol_id,
  component_name, is_intrinsic, is_fragment, line, "column",
  resolved_target_symbol_id, confidence
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, project_id, index_snapshot_id, file_id, source_symbol_id, component_name, is_intrinsic, is_fragment, line, "column", resolved_target_symbol_id, confidence, created_at
`

type InsertJsxUsageParams struct {
	ProjectID              pgtype.UUID `json:"project_id"`
	IndexSnapshotID        pgtype.UUID `json:"index_snapshot_id"`
	FileID                 pgtype.UUID `json:"file_id"`
	SourceSymbolID         pgtype.UUID `json:"source_symbol_id"`
	ComponentName          string      `json:"component_name"`
	IsIntrinsic            bool        `json:"is_intrinsic"`
	IsFragment             bool        `json:"is_fragment"`
	Line                   int32       `json:"line"`
	Column                 int32       `json:"column"`
	ResolvedTargetSymbolID pgtype.UUID `json:"resolved_target_symbol_id"`
	Confidence             pgtype.Text `json:"confidence"`
}

func (q *Queries) InsertJsxUsage(ctx context.Context, arg InsertJsxUsageParams) (JsxUsage, error) {
	row := q.db.QueryRow(ctx, insertJsxUsage,
		arg.ProjectID,
		arg.IndexSnapshotID,
		arg.FileID,
		arg.SourceSymbolID,
		arg.ComponentName,
		arg.IsIntrinsic,
		arg.IsFragment,
		arg.Line,
		arg.Column,
		arg.ResolvedTargetSymbolID,
		arg.Confidence,
	)
	var i JsxUsage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IndexSnapshotID,
		&i.FileID,
		&i.SourceSymbolID,
		&i.ComponentName,
		&i.IsIntrinsic,
		&i.IsFragment,
		&i.Line,
		&i.Column,
		&i.ResolvedTargetSymbolID,
		&i.Confidence,
		&i.CreatedAt,
	)
	return i, err
}

const listJsxUsagesByFileID = `-- name: ListJsxUsagesByFileID :many
SELECT id, project_id, index_snapshot_id, file_id, source_symbol_id, component_name, is_intrinsic, is_fragment, line, "column", resolved_target_symbol_id, confidence, created_at FROM jsx_usages WHERE file_id = $1 ORDER BY line
`

func (q *Queries) ListJsxUsagesByFileID(ctx context.Context, fileID pgtype.UUID) ([]JsxUsage, error) {
	rows, err := q.db.Query(ctx, listJsxUsagesByFileID, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JsxUsage{}
	for rows.Next() {
		var i JsxUsage
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IndexSnapshotID,
			&i.FileID,
			&i.SourceSymbolID,
			&i.ComponentName,
			&i.IsIntrinsic,
			&i.IsFragment,
			&i.Line,
			&i.Column,
			&i.ResolvedTargetSymbolID,
			&i.Confidence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
