// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: keys_and_settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearSelectedEmbeddingGlobalConfig = `-- name: ClearSelectedEmbeddingGlobalConfig :exec
UPDATE projects
SET
  selected_embedding_global_config_id = NULL,
  updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ClearSelectedEmbeddingGlobalConfig(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearSelectedEmbeddingGlobalConfig, id)
	return err
}

const clearSelectedLLMGlobalConfig = `-- name: ClearSelectedLLMGlobalConfig :exec
UPDATE projects
SET
  selected_llm_global_config_id = NULL,
  updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ClearSelectedLLMGlobalConfig(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearSelectedLLMGlobalConfig, id)
	return err
}

const countProjectsUsingEmbeddingConfig = `-- name: CountProjectsUsingEmbeddingConfig :one
SELECT COUNT(*)::bigint AS total
FROM projects
WHERE selected_embedding_global_config_id = $1
`

func (q *Queries) CountProjectsUsingEmbeddingConfig(ctx context.Context, selectedEmbeddingGlobalConfigID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectsUsingEmbeddingConfig, selectedEmbeddingGlobalConfigID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countProjectsUsingLLMConfig = `-- name: CountProjectsUsingLLMConfig :one
SELECT COUNT(*)::bigint AS total
FROM projects
WHERE selected_llm_global_config_id = $1
`

func (q *Queries) CountProjectsUsingLLMConfig(ctx context.Context, selectedLlmGlobalConfigID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectsUsingLLMConfig, selectedLlmGlobalConfigID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createEmbeddingDefaultProviderConfigIfMissing = `-- name: CreateEmbeddingDefaultProviderConfigIfMissing :exec
INSERT INTO embedding_provider_configs (
  name,
  provider,
  endpoint_url,
  model,
  dimensions,
  max_tokens,
  settings_json,
  is_active,
  is_default,
  is_available_to_projects,
  project_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, TRUE, TRUE, TRUE, NULL
)
ON CONFLICT (is_default)
  WHERE is_default = TRUE AND project_id IS NULL
DO NOTHING
`

type CreateEmbeddingDefaultProviderConfigIfMissingParams struct {
	Name         string `json:"name"`
	Provider     string `json:"provider"`
	EndpointUrl  string `json:"endpoint_url"`
	Model        string `json:"model"`
	Dimensions   int32  `json:"dimensions"`
	MaxTokens    int32  `json:"max_tokens"`
	SettingsJson []byte `json:"settings_json"`
}

func (q *Queries) CreateEmbeddingDefaultProviderConfigIfMissing(ctx context.Context, arg CreateEmbeddingDefaultProviderConfigIfMissingParams) error {
	_, err := q.db.Exec(ctx, createEmbeddingDefaultProviderConfigIfMissing,
		arg.Name,
		arg.Provider,
		arg.EndpointUrl,
		arg.Model,
		arg.Dimensions,
		arg.MaxTokens,
		arg.SettingsJson,
	)
	return err
}

const createEmbeddingProviderConfig = `-- name: CreateEmbeddingProviderConfig :one
INSERT INTO embedding_provider_configs (
  name,
  provider,
  endpoint_url,
  model,
  dimensions,
  max_tokens,
  settings_json,
  credentials_encrypted,
  is_active,
  is_default,
  is_available_to_projects,
  project_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, TRUE, FALSE, FALSE, $9
)
RETURNING id, name, provider, endpoint_url, model, dimensions, max_tokens, settings_json, credentials_encrypted, is_active, is_default, is_available_to_projects, project_id, created_at, updated_at
`

type CreateEmbeddingProviderConfigParams struct {
	Name                 string      `json:"name"`
	Provider             string      `json:"provider"`
	EndpointUrl          string      `json:"endpoint_url"`
	Model                string      `json:"model"`
	Dimensions           int32       `json:"dimensions"`
	MaxTokens            int32       `json:"max_tokens"`
	SettingsJson         []byte      `json:"settings_json"`
	CredentialsEncrypted []byte      `json:"credentials_encrypted"`
	ProjectID            pgtype.UUID `json:"project_id"`
}

func (q *Queries) CreateEmbeddingProviderConfig(ctx context.Context, arg CreateEmbeddingProviderConfigParams) (EmbeddingProviderConfig, error) {
	row := q.db.QueryRow(ctx, createEmbeddingProviderConfig,
		arg.Name,
		arg.Provider,
		arg.EndpointUrl,
		arg.Model,
		arg.Dimensions,
		arg.MaxTokens,
		arg.SettingsJson,
		arg.CredentialsEncrypted,
		arg.ProjectID,
	)
	var i EmbeddingProviderConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.EndpointUrl,
		&i.Model,
		&i.Dimensions,
		&i.MaxTokens,
		&i.SettingsJson,
		&i.CredentialsEncrypted,
		&i.IsActive,
		&i.IsDefault,
		&i.IsAvailableToProjects,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEmbeddingVersion = `-- name: CreateEmbeddingVersion :one
INSERT INTO embedding_versions (
  embedding_provider_config_id,
  provider,
  model,
  dimensions,
  version_label
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, embedding_provider_config_id, provider, model, dimensions, version_label, created_at
`

type CreateEmbeddingVersionParams struct {
	EmbeddingProviderConfigID pgtype.UUID `json:"embedding_provider_config_id"`
	Provider                  string      `json:"provider"`
	Model                     string      `json:"model"`
	Dimensions                int32       `json:"dimensions"`
	VersionLabel              string      `json:"version_label"`
}

func (q *Queries) CreateEmbeddingVersion(ctx context.Context, arg CreateEmbeddingVersionParams) (EmbeddingVersion, error) {
	row := q.db.QueryRow(ctx, createEmbeddingVersion,
		arg.EmbeddingProviderConfigID,
		arg.Provider,
		arg.Model,
		arg.Dimensions,
		arg.VersionLabel,
	)
	var i EmbeddingVersion
	err := row.Scan(
		&i.ID,
		&i.EmbeddingProviderConfigID,
		&i.Provider,
		&i.Model,
		&i.Dimensions,
		&i.VersionLabel,
		&i.CreatedAt,
	)
	return i, err
}

const createGlobalEmbeddingProviderConfig = `-- name: CreateGlobalEmbeddingProviderConfig :one
INSERT INTO embedding_provider_configs (
  name, provider, endpoint_url, model, dimensions, max_tokens,
  settings_json, credentials_encrypted,
  is_active, is_default, is_available_to_projects, project_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8,
  TRUE, TRUE, $9, NULL
)
RETURNING id, name, provider, endpoint_url, model, dimensions, max_tokens, settings_json, credentials_encrypted, is_active, is_default, is_available_to_projects, project_id, created_at, updated_at
`

type CreateGlobalEmbeddingProviderConfigParams struct {
	Name                  string `json:"name"`
	Provider              string `json:"provider"`
	EndpointUrl           string `json:"endpoint_url"`
	Model                 string `json:"model"`
	Dimensions            int32  `json:"dimensions"`
	MaxTokens             int32  `json:"max_tokens"`
	SettingsJson          []byte `json:"settings_json"`
	CredentialsEncrypted  []byte `json:"credentials_encrypted"`
	IsAvailableToProjects bool   `json:"is_available_to_projects"`
}

func (q *Queries) CreateGlobalEmbeddingProviderConfig(ctx context.Context, arg CreateGlobalEmbeddingProviderConfigParams) (EmbeddingProviderConfig, error) {
	row := q.db.QueryRow(ctx, createGlobalEmbeddingProviderConfig,
		arg.Name,
		arg.Provider,
		arg.EndpointUrl,
		arg.Model,
		arg.Dimensions,
		arg.MaxTokens,
		arg.SettingsJson,
		arg.CredentialsEncrypted,
		arg.IsAvailableToProjects,
	)
	var i EmbeddingProviderConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.EndpointUrl,
		&i.Model,
		&i.Dimensions,
		&i.MaxTokens,
		&i.SettingsJson,
		&i.CredentialsEncrypted,
		&i.IsActive,
		&i.IsDefault,
		&i.IsAvailableToProjects,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGlobalEmbeddingProviderConfigNonDefault = `-- name: CreateGlobalEmbeddingProviderConfigNonDefault :one
INSERT INTO embedding_provider_configs (
  name, provider, endpoint_url, model, dimensions, max_tokens,
  settings_json, credentials_encrypted,
  is_active, is_default, is_available_to_projects, project_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8,
  TRUE, FALSE, $9, NULL
)
RETURNING id, name, provider, endpoint_url, model, dimensions, max_tokens, settings_json, credentials_encrypted, is_active, is_default, is_available_to_projects, project_id, created_at, updated_at
`

type CreateGlobalEmbeddingProviderConfigNonDefaultParams struct {
	Name                  string `json:"name"`
	Provider              string `json:"provider"`
	EndpointUrl           string `json:"endpoint_url"`
	Model                 string `json:"model"`
	Dimensions            int32  `json:"dimensions"`
	MaxTokens             int32  `json:"max_tokens"`
	SettingsJson          []byte `json:"settings_json"`
	CredentialsEncrypted  []byte `json:"credentials_encrypted"`
	IsAvailableToProjects bool   `json:"is_available_to_projects"`
}

// Creates a new non-default global config. is_default is always FALSE.
func (q *Queries) CreateGlobalEmbeddingProviderConfigNonDefault(ctx context.Context, arg CreateGlobalEmbeddingProviderConfigNonDefaultParams) (EmbeddingProviderConfig, error) {
	row := q.db.QueryRow(ctx, createGlobalEmbeddingProviderConfigNonDefault,
		arg.Name,
		arg.Provider,
		arg.EndpointUrl,
		arg.Model,
		arg.Dimensions,
		arg.MaxTokens,
		arg.SettingsJson,
		arg.CredentialsEncrypted,
		arg.IsAvailableToProjects,
	)
	var i EmbeddingProviderConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.EndpointUrl,
		&i.Model,
		&i.Dimensions,
		&i.MaxTokens,
		&i.SettingsJson,
		&i.CredentialsEncrypted,
		&i.IsActive,
		&i.IsDefault,
		&i.IsAvailableToProjects,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGlobalLLMProviderConfig = `-- name: CreateGlobalLLMProviderConfig :one
INSERT INTO llm_provider_configs (
  name, provider, endpoint_url, model,
  settings_json, credentials_encrypted,
  is_active, is_default, is_available_to_projects, project_id
) VALUES (
  $1, $2, $3, $4, $5, $6,
  TRUE, TRUE, $7, NULL
)
RETURNING id, name, provider, endpoint_url, model, settings_json, credentials_encrypted, is_active, is_default, is_available_to_projects, project_id, created_at, updated_at
`

type CreateGlobalLLMProviderConfigParams struct {
	Name                  string      `json:"name"`
	Provider              string      `json:"provider"`
	EndpointUrl           string      `json:"endpoint_url"`
	Model                 pgtype.Text `json:"model"`
	SettingsJson          []byte      `json:"settings_json"`
	CredentialsEncrypted  []byte      `json:"credentials_encrypted"`
	IsAvailableToProjects bool        `json:"is_available_to_projects"`
}

func (q *Queries) CreateGlobalLLMProviderConfig(ctx context.Context, arg CreateGlobalLLMProviderConfigParams) (LlmProviderConfig, error) {
	row := q.db.QueryRow(ctx, createGlobalLLMProviderConfig,
		arg.Name,
		arg.Provider,
		arg.EndpointUrl,
		arg.Model,
		arg.SettingsJson,
		arg.CredentialsEncrypted,
		arg.IsAvailableToProjects,
	)
	var i LlmProviderConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.EndpointUrl,
		&i.Model,
		&i.SettingsJson,
		&i.CredentialsEncrypted,
		&i.IsActive,
		&i.IsDefault,
		&i.IsAvailableToProjects,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGlobalLLMProviderConfigNonDefault = `-- name: CreateGlobalLLMProviderConfigNonDefault :one
INSERT INTO llm_provider_configs (
  name, provider, endpoint_url, model,
  settings_json, credentials_encrypted,
  is_active, is_default, is_available_to_projects, project_id
) VALUES (
  $1, $2, $3, $4, $5, $6,
  TRUE, FALSE, $7, NULL
)
RETURNING id, name, provider, endpoint_url, model, settings_json, credentials_encrypted, is_active, is_default, is_available_to_projects, project_id, created_at, updated_at
`

type CreateGlobalLLMProviderConfigNonDefaultParams struct {
	Name                  string      `json:"name"`
	Provider              string      `json:"provider"`
	EndpointUrl           string      `json:"endpoint_url"`
	Model                 pgtype.Text `json:"model"`
	SettingsJson          []byte      `json:"settings_json"`
	CredentialsEncrypted  []byte      `json:"credentials_encrypted"`
	IsAvailableToProjects bool        `json:"is_available_to_projects"`
}

// Creates a new non-default global LLM config. is_default is always FALSE.
func (q *Queries) CreateGlobalLLMProviderConfigNonDefault(ctx context.Context, arg CreateGlobalLLMProviderConfigNonDefaultParams) (LlmProviderConfig, error) {
	row := q.db.QueryRow(ctx, createGlobalLLMProviderConfigNonDefault,
		arg.Name,
		arg.Provider,
		arg.EndpointUrl,
		arg.Model,
		arg.SettingsJson,
		arg.CredentialsEncrypted,
		arg.IsAvailableToProjects,
	)
	var i LlmProviderConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.EndpointUrl,
		&i.Model,
		&i.SettingsJson,
		&i.CredentialsEncrypted,
		&i.IsActive,
		&i.IsDefault,
		&i.IsAvailableToProjects,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLLMDefaultProviderConfigIfMissing = `-- name: CreateLLMDefaultProviderConfigIfMissing :exec
INSERT INTO llm_provider_configs (
  name,
  provider,
  endpoint_url,
  model,
  settings_json,
  is_active,
  is_default,
  is_available_to_projects,
  project_id
) VALUES (
  $1, $2, $3, $4, $5, TRUE, TRUE, TRUE, NULL
)
ON CONFLICT (is_default)
  WHERE is_default = TRUE AND project_id IS NULL
DO NOTHING
`

type CreateLLMDefaultProviderConfigIfMissingParams struct {
	Name         string      `json:"name"`
	Provider     string      `json:"provider"`
	EndpointUrl  string      `json:"endpoint_url"`
	Model        pgtype.Text `json:"model"`
	SettingsJson []byte      `json:"settings_json"`
}

func (q *Queries) CreateLLMDefaultProviderConfigIfMissing(ctx context.Context, arg CreateLLMDefaultProviderConfigIfMissingParams) error {
	_, err := q.db.Exec(ctx, createLLMDefaultProviderConfigIfMissing,
		arg.Name,
		arg.Provider,
		arg.EndpointUrl,
		arg.Model,
		arg.SettingsJson,
	)
	return err
}

const createLLMProviderConfig = `-- name: CreateLLMProviderConfig :one
INSERT INTO llm_provider_configs (
  name,
  provider,
  endpoint_url,
  model,
  settings_json,
  credentials_encrypted,
  is_active,
  is_default,
  is_available_to_projects,
  project_id
) VALUES (
  $1, $2, $3, $4, $5, $6, TRUE, FALSE, FALSE, $7
)
RETURNING id, name, provider, endpoint_url, model, settings_json, credentials_encrypted, is_active, is_default, is_available_to_projects, project_id, created_at, updated_at
`

type CreateLLMProviderConfigParams struct {
	Name                 string      `json:"name"`
	Provider             string      `json:"provider"`
	EndpointUrl          string      `json:"endpoint_url"`
	Model                pgtype.Text `json:"model"`
	SettingsJson         []byte      `json:"settings_json"`
	CredentialsEncrypted []byte      `json:"credentials_encrypted"`
	ProjectID            pgtype.UUID `json:"project_id"`
}

func (q *Queries) CreateLLMProviderConfig(ctx context.Context, arg CreateLLMProviderConfigParams) (LlmProviderConfig, error) {
	row := q.db.QueryRow(ctx, createLLMProviderConfig,
		arg.Name,
		arg.Provider,
		arg.EndpointUrl,
		arg.Model,
		arg.SettingsJson,
		arg.CredentialsEncrypted,
		arg.ProjectID,
	)
	var i LlmProviderConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.EndpointUrl,
		&i.Model,
		&i.SettingsJson,
		&i.CredentialsEncrypted,
		&i.IsActive,
		&i.IsDefault,
		&i.IsAvailableToProjects,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateDefaultGlobalEmbeddingProviderConfig = `-- name: DeactivateDefaultGlobalEmbeddingProviderConfig :exec
UPDATE embedding_provider_configs
SET is_active = FALSE, is_default = FALSE, updated_at = NOW()
WHERE project_id IS NULL AND is_default = TRUE AND is_active = TRUE
`

// Deactivates only the current default global config, leaving non-default configs untouched.
func (q *Queries) DeactivateDefaultGlobalEmbeddingProviderConfig(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deactivateDefaultGlobalEmbeddingProviderConfig)
	return err
}

const deactivateDefaultGlobalLLMProviderConfig = `-- name: DeactivateDefaultGlobalLLMProviderConfig :exec
UPDATE llm_provider_configs
SET is_active = FALSE, is_default = FALSE, updated_at = NOW()
WHERE project_id IS NULL AND is_default = TRUE AND is_active = TRUE
`

// Deactivates only the current default global config, leaving non-default configs untouched.
func (q *Queries) DeactivateDefaultGlobalLLMProviderConfig(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deactivateDefaultGlobalLLMProviderConfig)
	return err
}

const deactivateGlobalEmbeddingProviderConfigByID = `-- name: DeactivateGlobalEmbeddingProviderConfigByID :execrows
UPDATE embedding_provider_configs
SET is_active = FALSE, is_default = FALSE, credentials_encrypted = NULL, updated_at = NOW()
WHERE id = $1 AND project_id IS NULL AND is_active = TRUE AND is_default = FALSE
`

// Soft-deletes a single global config by ID.
// The is_default = FALSE guard prevents deleting a config that was concurrently promoted.
func (q *Queries) DeactivateGlobalEmbeddingProviderConfigByID(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateGlobalEmbeddingProviderConfigByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deactivateGlobalEmbeddingProviderConfigs = `-- name: DeactivateGlobalEmbeddingProviderConfigs :exec
UPDATE embedding_provider_configs
SET is_active = FALSE, is_default = FALSE, updated_at = NOW()
WHERE project_id IS NULL AND (is_active = TRUE OR is_default = TRUE)
`

// DEPRECATED: Use DeactivateDefaultGlobalEmbeddingProviderConfig instead.
// This deactivates ALL global rows, which breaks multi-provider support.
func (q *Queries) DeactivateGlobalEmbeddingProviderConfigs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deactivateGlobalEmbeddingProviderConfigs)
	return err
}

const deactivateGlobalLLMProviderConfigByID = `-- name: DeactivateGlobalLLMProviderConfigByID :execrows
UPDATE llm_provider_configs
SET is_active = FALSE, is_default = FALSE, credentials_encrypted = NULL, updated_at = NOW()
WHERE id = $1 AND project_id IS NULL AND is_active = TRUE AND is_default = FALSE
`

// Soft-deletes a single global LLM config by ID.
// The is_default = FALSE guard prevents deleting a config that was concurrently promoted.
func (q *Queries) DeactivateGlobalLLMProviderConfigByID(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateGlobalLLMProviderConfigByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deactivateGlobalLLMProviderConfigs = `-- name: DeactivateGlobalLLMProviderConfigs :exec
UPDATE llm_provider_configs
SET is_active = FALSE, is_default = FALSE, updated_at = NOW()
WHERE project_id IS NULL AND (is_active = TRUE OR is_default = TRUE)
`

// DEPRECATED: Use DeactivateDefaultGlobalLLMProviderConfig instead.
// This deactivates ALL global rows, which breaks multi-provider support.
func (q *Queries) DeactivateGlobalLLMProviderConfigs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deactivateGlobalLLMProviderConfigs)
	return err
}

const deactivateProjectEmbeddingProviderConfigs = `-- name: DeactivateProjectEmbeddingProviderConfigs :exec
UPDATE embedding_provider_configs
SET
  is_active = FALSE,
  credentials_encrypted = NULL,
  updated_at = NOW()
WHERE project_id = $1
  AND is_active = TRUE
`

func (q *Queries) DeactivateProjectEmbeddingProviderConfigs(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateProjectEmbeddingProviderConfigs, projectID)
	return err
}

const deactivateProjectLLMProviderConfigs = `-- name: DeactivateProjectLLMProviderConfigs :exec
UPDATE llm_provider_configs
SET
  is_active = FALSE,
  credentials_encrypted = NULL,
  updated_at = NOW()
WHERE project_id = $1
  AND is_active = TRUE
`

func (q *Queries) DeactivateProjectLLMProviderConfigs(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateProjectLLMProviderConfigs, projectID)
	return err
}

const demoteGlobalEmbeddingProviderConfigDefault = `-- name: DemoteGlobalEmbeddingProviderConfigDefault :exec
UPDATE embedding_provider_configs
SET is_default = FALSE, updated_at = NOW()
WHERE project_id IS NULL AND is_default = TRUE
`

// Clears is_default on the current default. Step 1 of the promote transaction.
func (q *Queries) DemoteGlobalEmbeddingProviderConfigDefault(ctx context.Context) error {
	_, err := q.db.Exec(ctx, demoteGlobalEmbeddingProviderConfigDefault)
	return err
}

const demoteGlobalLLMProviderConfigDefault = `-- name: DemoteGlobalLLMProviderConfigDefault :exec
UPDATE llm_provider_configs
SET is_default = FALSE, updated_at = NOW()
WHERE project_id IS NULL AND is_default = TRUE
`

// Clears is_default on the current default LLM config. Step 1 of the promote transaction.
func (q *Queries) DemoteGlobalLLMProviderConfigDefault(ctx context.Context) error {
	_, err := q.db.Exec(ctx, demoteGlobalLLMProviderConfigDefault)
	return err
}

const getActiveProjectEmbeddingProviderConfig = `-- name: GetActiveProjectEmbeddingProviderConfig :one
SELECT id, name, provider, endpoint_url, model, dimensions, max_tokens, settings_json, credentials_encrypted, is_active, is_default, is_available_to_projects, project_id, created_at, updated_at
FROM embedding_provider_configs
WHERE project_id = $1
  AND is_active = TRUE
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetActiveProjectEmbeddingProviderConfig(ctx context.Context, projectID pgtype.UUID) (EmbeddingProviderConfig, error) {
	row := q.db.QueryRow(ctx, getActiveProjectEmbeddingProviderConfig, projectID)
	var i EmbeddingProviderConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.EndpointUrl,
		&i.Model,
		&i.Dimensions,
		&i.MaxTokens,
		&i.SettingsJson,
		&i.CredentialsEncrypted,
		&i.IsActive,
		&i.IsDefault,
		&i.IsAvailableToProjects,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveProjectLLMProviderConfig = `-- name: GetActiveProjectLLMProviderConfig :one
SELECT id, name, provider, endpoint_url, model, settings_json, credentials_encrypted, is_active, is_default, is_available_to_projects, project_id, created_at, updated_at
FROM llm_provider_configs
WHERE project_id = $1
  AND is_active = TRUE
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetActiveProjectLLMProviderConfig(ctx context.Context, projectID pgtype.UUID) (LlmProviderConfig, error) {
	row := q.db.QueryRow(ctx, getActiveProjectLLMProviderConfig, projectID)
	var i LlmProviderConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.EndpointUrl,
		&i.Model,
		&i.SettingsJson,
		&i.CredentialsEncrypted,
		&i.IsActive,
		&i.IsDefault,
		&i.IsAvailableToProjects,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultGlobalEmbeddingProviderConfig = `-- name: GetDefaultGlobalEmbeddingProviderConfig :one
SELECT id, name, provider, endpoint_url, model, dimensions, max_tokens, settings_json, credentials_encrypted, is_active, is_default, is_available_to_projects, project_id, created_at, updated_at
FROM embedding_provider_configs
WHERE project_id IS NULL
  AND is_active = TRUE
  AND is_default = TRUE
LIMIT 1
`

func (q *Queries) GetDefaultGlobalEmbeddingProviderConfig(ctx context.Context) (EmbeddingProviderConfig, error) {
	row := q.db.QueryRow(ctx, getDefaultGlobalEmbeddingProviderConfig)
	var i EmbeddingProviderConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.EndpointUrl,
		&i.Model,
		&i.Dimensions,
		&i.MaxTokens,
		&i.SettingsJson,
		&i.CredentialsEncrypted,
		&i.IsActive,
		&i.IsDefault,
		&i.IsAvailableToProjects,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultGlobalLLMProviderConfig = `-- name: GetDefaultGlobalLLMProviderConfig :one
SELECT id, name, provider, endpoint_url, model, settings_json, credentials_encrypted, is_active, is_default, is_available_to_projects, project_id, created_at, updated_at
FROM llm_provider_configs
WHERE project_id IS NULL
  AND is_active = TRUE
  AND is_default = TRUE
LIMIT 1
`

func (q *Queries) GetDefaultGlobalLLMProviderConfig(ctx context.Context) (LlmProviderConfig, error) {
	row := q.db.QueryRow(ctx, getDefaultGlobalLLMProviderConfig)
	var i LlmProviderConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.EndpointUrl,
		&i.Model,
		&i.SettingsJson,
		&i.CredentialsEncrypted,
		&i.IsActive,
		&i.IsDefault,
		&i.IsAvailableToProjects,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmbeddingProviderConfigByID = `-- name: GetEmbeddingProviderConfigByID :one

SELECT id, name, provider, endpoint_url, model, dimensions, max_tokens, settings_json, credentials_encrypted, is_active, is_default, is_available_to_projects, project_id, created_at, updated_at
FROM embedding_provider_configs
WHERE id = $1
LIMIT 1
`

// ===================== Embedding Provider Configs =====================
func (q *Queries) GetEmbeddingProviderConfigByID(ctx context.Context, id pgtype.UUID) (EmbeddingProviderConfig, error) {
	row := q.db.QueryRow(ctx, getEmbeddingProviderConfigByID, id)
	var i EmbeddingProviderConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.EndpointUrl,
		&i.Model,
		&i.Dimensions,
		&i.MaxTokens,
		&i.SettingsJson,
		&i.CredentialsEncrypted,
		&i.IsActive,
		&i.IsDefault,
		&i.IsAvailableToProjects,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmbeddingVersionByLabel = `-- name: GetEmbeddingVersionByLabel :one
SELECT id, embedding_provider_config_id, provider, model, dimensions, version_label, created_at FROM embedding_versions WHERE version_label = $1
`

func (q *Queries) GetEmbeddingVersionByLabel(ctx context.Context, versionLabel string) (EmbeddingVersion, error) {
	row := q.db.QueryRow(ctx, getEmbeddingVersionByLabel, versionLabel)
	var i EmbeddingVersion
	err := row.Scan(
		&i.ID,
		&i.EmbeddingProviderConfigID,
		&i.Provider,
		&i.Model,
		&i.Dimensions,
		&i.VersionLabel,
		&i.CreatedAt,
	)
	return i, err
}

const getGlobalEmbeddingProviderConfigByID = `-- name: GetGlobalEmbeddingProviderConfigByID :one
SELECT id, name, provider, endpoint_url, model, dimensions, max_tokens, settings_json, credentials_encrypted, is_active, is_default, is_available_to_projects, project_id, created_at, updated_at
FROM embedding_provider_configs
WHERE id = $1 AND project_id IS NULL
LIMIT 1
`

func (q *Queries) GetGlobalEmbeddingProviderConfigByID(ctx context.Context, id pgtype.UUID) (EmbeddingProviderConfig, error) {
	row := q.db.QueryRow(ctx, getGlobalEmbeddingProviderConfigByID, id)
	var i EmbeddingProviderConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.EndpointUrl,
		&i.Model,
		&i.Dimensions,
		&i.MaxTokens,
		&i.SettingsJson,
		&i.CredentialsEncrypted,
		&i.IsActive,
		&i.IsDefault,
		&i.IsAvailableToProjects,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGlobalLLMProviderConfigByID = `-- name: GetGlobalLLMProviderConfigByID :one
SELECT id, name, provider, endpoint_url, model, settings_json, credentials_encrypted, is_active, is_default, is_available_to_projects, project_id, created_at, updated_at
FROM llm_provider_configs
WHERE id = $1 AND project_id IS NULL
LIMIT 1
`

func (q *Queries) GetGlobalLLMProviderConfigByID(ctx context.Context, id pgtype.UUID) (LlmProviderConfig, error) {
	row := q.db.QueryRow(ctx, getGlobalLLMProviderConfigByID, id)
	var i LlmProviderConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.EndpointUrl,
		&i.Model,
		&i.SettingsJson,
		&i.CredentialsEncrypted,
		&i.IsActive,
		&i.IsDefault,
		&i.IsAvailableToProjects,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLLMProviderConfigByID = `-- name: GetLLMProviderConfigByID :one

SELECT id, name, provider, endpoint_url, model, settings_json, credentials_encrypted, is_active, is_default, is_available_to_projects, project_id, created_at, updated_at
FROM llm_provider_configs
WHERE id = $1
LIMIT 1
`

// ===================== LLM Provider Configs =====================
func (q *Queries) GetLLMProviderConfigByID(ctx context.Context, id pgtype.UUID) (LlmProviderConfig, error) {
	row := q.db.QueryRow(ctx, getLLMProviderConfigByID, id)
	var i LlmProviderConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.EndpointUrl,
		&i.Model,
		&i.SettingsJson,
		&i.CredentialsEncrypted,
		&i.IsActive,
		&i.IsDefault,
		&i.IsAvailableToProjects,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectProviderSelections = `-- name: GetProjectProviderSelections :one

SELECT
  selected_embedding_global_config_id,
  selected_llm_global_config_id
FROM projects
WHERE id = $1
`

type GetProjectProviderSelectionsRow struct {
	SelectedEmbeddingGlobalConfigID pgtype.UUID `json:"selected_embedding_global_config_id"`
	SelectedLlmGlobalConfigID       pgtype.UUID `json:"selected_llm_global_config_id"`
}

// ===================== Project Provider Selections =====================
func (q *Queries) GetProjectProviderSelections(ctx context.Context, id pgtype.UUID) (GetProjectProviderSelectionsRow, error) {
	row := q.db.QueryRow(ctx, getProjectProviderSelections, id)
	var i GetProjectProviderSelectionsRow
	err := row.Scan(&i.SelectedEmbeddingGlobalConfigID, &i.SelectedLlmGlobalConfigID)
	return i, err
}

const listAvailableGlobalEmbeddingProviderConfigs = `-- name: ListAvailableGlobalEmbeddingProviderConfigs :many
SELECT
  id,
  name,
  provider,
  endpoint_url,
  model,
  dimensions,
  max_tokens,
  settings_json,
  COALESCE(octet_length(credentials_encrypted), 0) > 0 AS has_credentials,
  is_active,
  is_default,
  is_available_to_projects,
  project_id,
  created_at,
  updated_at
FROM embedding_provider_configs
WHERE project_id IS NULL
  AND is_active = TRUE
  AND is_available_to_projects = TRUE
ORDER BY is_default DESC, created_at ASC, id ASC
`

type ListAvailableGlobalEmbeddingProviderConfigsRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Name                  string             `json:"name"`
	Provider              string             `json:"provider"`
	EndpointUrl           string             `json:"endpoint_url"`
	Model                 string             `json:"model"`
	Dimensions            int32              `json:"dimensions"`
	MaxTokens             int32              `json:"max_tokens"`
	SettingsJson          []byte             `json:"settings_json"`
	HasCredentials        bool               `json:"has_credentials"`
	IsActive              bool               `json:"is_active"`
	IsDefault             bool               `json:"is_default"`
	IsAvailableToProjects bool               `json:"is_available_to_projects"`
	ProjectID             pgtype.UUID        `json:"project_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAvailableGlobalEmbeddingProviderConfigs(ctx context.Context) ([]ListAvailableGlobalEmbeddingProviderConfigsRow, error) {
	rows, err := q.db.Query(ctx, listAvailableGlobalEmbeddingProviderConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailableGlobalEmbeddingProviderConfigsRow{}
	for rows.Next() {
		var i ListAvailableGlobalEmbeddingProviderConfigsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.EndpointUrl,
			&i.Model,
			&i.Dimensions,
			&i.MaxTokens,
			&i.SettingsJson,
			&i.HasCredentials,
			&i.IsActive,
			&i.IsDefault,
			&i.IsAvailableToProjects,
			&i.ProjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailableGlobalLLMProviderConfigs = `-- name: ListAvailableGlobalLLMProviderConfigs :many
SELECT
  id,
  name,
  provider,
  endpoint_url,
  model,
  settings_json,
  COALESCE(octet_length(credentials_encrypted), 0) > 0 AS has_credentials,
  is_active,
  is_default,
  is_available_to_projects,
  project_id,
  created_at,
  updated_at
FROM llm_provider_configs
WHERE project_id IS NULL
  AND is_active = TRUE
  AND is_available_to_projects = TRUE
ORDER BY is_default DESC, created_at ASC, id ASC
`

type ListAvailableGlobalLLMProviderConfigsRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Name                  string             `json:"name"`
	Provider              string             `json:"provider"`
	EndpointUrl           string             `json:"endpoint_url"`
	Model                 pgtype.Text        `json:"model"`
	SettingsJson          []byte             `json:"settings_json"`
	HasCredentials        bool               `json:"has_credentials"`
	IsActive              bool               `json:"is_active"`
	IsDefault             bool               `json:"is_default"`
	IsAvailableToProjects bool               `json:"is_available_to_projects"`
	ProjectID             pgtype.UUID        `json:"project_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAvailableGlobalLLMProviderConfigs(ctx context.Context) ([]ListAvailableGlobalLLMProviderConfigsRow, error) {
	rows, err := q.db.Query(ctx, listAvailableGlobalLLMProviderConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailableGlobalLLMProviderConfigsRow{}
	for rows.Next() {
		var i ListAvailableGlobalLLMProviderConfigsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.EndpointUrl,
			&i.Model,
			&i.SettingsJson,
			&i.HasCredentials,
			&i.IsActive,
			&i.IsDefault,
			&i.IsAvailableToProjects,
			&i.ProjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalEmbeddingProviderConfigs = `-- name: ListGlobalEmbeddingProviderConfigs :many

SELECT id, name, provider, endpoint_url, model, dimensions, max_tokens, settings_json, credentials_encrypted, is_active, is_default, is_available_to_projects, project_id, created_at, updated_at
FROM embedding_provider_configs
WHERE project_id IS NULL
ORDER BY is_default DESC, is_active DESC, created_at DESC
`

// ===================== Global Provider Config Management =====================
func (q *Queries) ListGlobalEmbeddingProviderConfigs(ctx context.Context) ([]EmbeddingProviderConfig, error) {
	rows, err := q.db.Query(ctx, listGlobalEmbeddingProviderConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmbeddingProviderConfig{}
	for rows.Next() {
		var i EmbeddingProviderConfig
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.EndpointUrl,
			&i.Model,
			&i.Dimensions,
			&i.MaxTokens,
			&i.SettingsJson,
			&i.CredentialsEncrypted,
			&i.IsActive,
			&i.IsDefault,
			&i.IsAvailableToProjects,
			&i.ProjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalLLMProviderConfigs = `-- name: ListGlobalLLMProviderConfigs :many
SELECT id, name, provider, endpoint_url, model, settings_json, credentials_encrypted, is_active, is_default, is_available_to_projects, project_id, created_at, updated_at
FROM llm_provider_configs
WHERE project_id IS NULL
ORDER BY is_default DESC, is_active DESC, created_at DESC
`

func (q *Queries) ListGlobalLLMProviderConfigs(ctx context.Context) ([]LlmProviderConfig, error) {
	rows, err := q.db.Query(ctx, listGlobalLLMProviderConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LlmProviderConfig{}
	for rows.Next() {
		var i LlmProviderConfig
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.EndpointUrl,
			&i.Model,
			&i.SettingsJson,
			&i.CredentialsEncrypted,
			&i.IsActive,
			&i.IsDefault,
			&i.IsAvailableToProjects,
			&i.ProjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteGlobalEmbeddingProviderConfigToDefault = `-- name: PromoteGlobalEmbeddingProviderConfigToDefault :execrows
UPDATE embedding_provider_configs
SET is_default = TRUE, updated_at = NOW()
WHERE id = $1 AND project_id IS NULL AND is_active = TRUE
`

// Sets is_default=TRUE on the target config. Step 2 of the promote transaction.
func (q *Queries) PromoteGlobalEmbeddingProviderConfigToDefault(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, promoteGlobalEmbeddingProviderConfigToDefault, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const promoteGlobalLLMProviderConfigToDefault = `-- name: PromoteGlobalLLMProviderConfigToDefault :execrows
UPDATE llm_provider_configs
SET is_default = TRUE, updated_at = NOW()
WHERE id = $1 AND project_id IS NULL AND is_active = TRUE
`

// Sets is_default=TRUE on the target LLM config. Step 2 of the promote transaction.
func (q *Queries) PromoteGlobalLLMProviderConfigToDefault(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, promoteGlobalLLMProviderConfigToDefault, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSelectedEmbeddingGlobalConfig = `-- name: SetSelectedEmbeddingGlobalConfig :exec
UPDATE projects
SET
  selected_embedding_global_config_id = $2,
  updated_at = NOW()
WHERE id = $1
`

type SetSelectedEmbeddingGlobalConfigParams struct {
	ID                              pgtype.UUID `json:"id"`
	SelectedEmbeddingGlobalConfigID pgtype.UUID `json:"selected_embedding_global_config_id"`
}

func (q *Queries) SetSelectedEmbeddingGlobalConfig(ctx context.Context, arg SetSelectedEmbeddingGlobalConfigParams) error {
	_, err := q.db.Exec(ctx, setSelectedEmbeddingGlobalConfig, arg.ID, arg.SelectedEmbeddingGlobalConfigID)
	return err
}

const setSelectedLLMGlobalConfig = `-- name: SetSelectedLLMGlobalConfig :exec
UPDATE projects
SET
  selected_llm_global_config_id = $2,
  updated_at = NOW()
WHERE id = $1
`

type SetSelectedLLMGlobalConfigParams struct {
	ID                        pgtype.UUID `json:"id"`
	SelectedLlmGlobalConfigID pgtype.UUID `json:"selected_llm_global_config_id"`
}

func (q *Queries) SetSelectedLLMGlobalConfig(ctx context.Context, arg SetSelectedLLMGlobalConfigParams) error {
	_, err := q.db.Exec(ctx, setSelectedLLMGlobalConfig, arg.ID, arg.SelectedLlmGlobalConfigID)
	return err
}

const updateGlobalEmbeddingProviderConfig = `-- name: UpdateGlobalEmbeddingProviderConfig :one
UPDATE embedding_provider_configs
SET
  name = COALESCE($1, name),
  provider = COALESCE($2, provider),
  endpoint_url = COALESCE($3, endpoint_url),
  model = COALESCE($4, model),
  dimensions = COALESCE($5, dimensions),
  max_tokens = COALESCE($6, max_tokens),
  settings_json = COALESCE($7::jsonb, settings_json),
  credentials_encrypted = CASE
    WHEN $8::boolean THEN NULL
    WHEN $9::bytea IS NOT NULL THEN $9::bytea
    ELSE credentials_encrypted
  END,
  is_available_to_projects = COALESCE($10, is_available_to_projects),
  updated_at = NOW()
WHERE id = $11 AND project_id IS NULL AND is_active = TRUE
RETURNING id, name, provider, endpoint_url, model, dimensions, max_tokens, settings_json, credentials_encrypted, is_active, is_default, is_available_to_projects, project_id, created_at, updated_at
`

type UpdateGlobalEmbeddingProviderConfigParams struct {
	Name                  pgtype.Text `json:"name"`
	Provider              pgtype.Text `json:"provider"`
	EndpointUrl           pgtype.Text `json:"endpoint_url"`
	Model                 pgtype.Text `json:"model"`
	Dimensions            pgtype.Int4 `json:"dimensions"`
	MaxTokens             pgtype.Int4 `json:"max_tokens"`
	SettingsJson          []byte      `json:"settings_json"`
	ClearCredentials      bool        `json:"clear_credentials"`
	CredentialsEncrypted  []byte      `json:"credentials_encrypted"`
	IsAvailableToProjects pgtype.Bool `json:"is_available_to_projects"`
	ID                    pgtype.UUID `json:"id"`
}

// In-place partial update of a global config. Only provided (non-NULL) fields are changed.
func (q *Queries) UpdateGlobalEmbeddingProviderConfig(ctx context.Context, arg UpdateGlobalEmbeddingProviderConfigParams) (EmbeddingProviderConfig, error) {
	row := q.db.QueryRow(ctx, updateGlobalEmbeddingProviderConfig,
		arg.Name,
		arg.Provider,
		arg.EndpointUrl,
		arg.Model,
		arg.Dimensions,
		arg.MaxTokens,
		arg.SettingsJson,
		arg.ClearCredentials,
		arg.CredentialsEncrypted,
		arg.IsAvailableToProjects,
		arg.ID,
	)
	var i EmbeddingProviderConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.EndpointUrl,
		&i.Model,
		&i.Dimensions,
		&i.MaxTokens,
		&i.SettingsJson,
		&i.CredentialsEncrypted,
		&i.IsActive,
		&i.IsDefault,
		&i.IsAvailableToProjects,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGlobalLLMProviderConfig = `-- name: UpdateGlobalLLMProviderConfig :one
UPDATE llm_provider_configs
SET
  name = COALESCE($1, name),
  provider = COALESCE($2, provider),
  endpoint_url = COALESCE($3, endpoint_url),
  model = COALESCE($4, model),
  settings_json = COALESCE($5::jsonb, settings_json),
  credentials_encrypted = CASE
    WHEN $6::boolean THEN NULL
    WHEN $7::bytea IS NOT NULL THEN $7::bytea
    ELSE credentials_encrypted
  END,
  is_available_to_projects = COALESCE($8, is_available_to_projects),
  updated_at = NOW()
WHERE id = $9 AND project_id IS NULL AND is_active = TRUE
RETURNING id, name, provider, endpoint_url, model, settings_json, credentials_encrypted, is_active, is_default, is_available_to_projects, project_id, created_at, updated_at
`

type UpdateGlobalLLMProviderConfigParams struct {
	Name                  pgtype.Text `json:"name"`
	Provider              pgtype.Text `json:"provider"`
	EndpointUrl           pgtype.Text `json:"endpoint_url"`
	Model                 pgtype.Text `json:"model"`
	SettingsJson          []byte      `json:"settings_json"`
	ClearCredentials      bool        `json:"clear_credentials"`
	CredentialsEncrypted  []byte      `json:"credentials_encrypted"`
	IsAvailableToProjects pgtype.Bool `json:"is_available_to_projects"`
	ID                    pgtype.UUID `json:"id"`
}

// In-place partial update of a global LLM config. Only provided (non-NULL) fields are changed.
func (q *Queries) UpdateGlobalLLMProviderConfig(ctx context.Context, arg UpdateGlobalLLMProviderConfigParams) (LlmProviderConfig, error) {
	row := q.db.QueryRow(ctx, updateGlobalLLMProviderConfig,
		arg.Name,
		arg.Provider,
		arg.EndpointUrl,
		arg.Model,
		arg.SettingsJson,
		arg.ClearCredentials,
		arg.CredentialsEncrypted,
		arg.IsAvailableToProjects,
		arg.ID,
	)
	var i LlmProviderConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.EndpointUrl,
		&i.Model,
		&i.SettingsJson,
		&i.CredentialsEncrypted,
		&i.IsActive,
		&i.IsDefault,
		&i.IsAvailableToProjects,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
