// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         pgtype.UUID        `json:"id"`
	KeyType    string             `json:"key_type"`
	KeyPrefix  string             `json:"key_prefix"`
	KeyHash    string             `json:"key_hash"`
	Name       string             `json:"name"`
	Role       string             `json:"role"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	IsActive   bool               `json:"is_active"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ApiKeyProjectAccess struct {
	ApiKeyID      pgtype.UUID `json:"api_key_id"`
	KeyPrefix     string      `json:"key_prefix"`
	KeyHash       string      `json:"key_hash"`
	EffectiveRole string      `json:"effective_role"`
	IsActive      bool        `json:"is_active"`
	ProjectID     pgtype.UUID `json:"project_id"`
}

type CodeChunk struct {
	ID                 pgtype.UUID        `json:"id"`
	ProjectID          pgtype.UUID        `json:"project_id"`
	IndexSnapshotID    pgtype.UUID        `json:"index_snapshot_id"`
	FileID             pgtype.UUID        `json:"file_id"`
	SymbolID           pgtype.UUID        `json:"symbol_id"`
	ChunkType          string             `json:"chunk_type"`
	ChunkHash          string             `json:"chunk_hash"`
	Content            string             `json:"content"`
	ContextBefore      pgtype.Text        `json:"context_before"`
	ContextAfter       pgtype.Text        `json:"context_after"`
	StartLine          int32              `json:"start_line"`
	EndLine            int32              `json:"end_line"`
	EstimatedTokens    pgtype.Int4        `json:"estimated_tokens"`
	OwnerQualifiedName pgtype.Text        `json:"owner_qualified_name"`
	OwnerKind          pgtype.Text        `json:"owner_kind"`
	IsExportedContext  bool               `json:"is_exported_context"`
	SemanticRole       pgtype.Text        `json:"semantic_role"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Commit struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	CommitHash     string             `json:"commit_hash"`
	AuthorName     string             `json:"author_name"`
	AuthorEmail    string             `json:"author_email"`
	AuthorDate     pgtype.Timestamptz `json:"author_date"`
	CommitterName  string             `json:"committer_name"`
	CommitterEmail string             `json:"committer_email"`
	CommitterDate  pgtype.Timestamptz `json:"committer_date"`
	Message        string             `json:"message"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type CommitFileDiff struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	CommitID       pgtype.UUID        `json:"commit_id"`
	ParentCommitID pgtype.UUID        `json:"parent_commit_id"`
	OldFilePath    pgtype.Text        `json:"old_file_path"`
	NewFilePath    pgtype.Text        `json:"new_file_path"`
	ChangeType     string             `json:"change_type"`
	Patch          pgtype.Text        `json:"patch"`
	Additions      int32              `json:"additions"`
	Deletions      int32              `json:"deletions"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type CommitParent struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	CommitID       pgtype.UUID `json:"commit_id"`
	ParentCommitID pgtype.UUID `json:"parent_commit_id"`
	Ordinal        int32       `json:"ordinal"`
}

type Dependency struct {
	ID              pgtype.UUID `json:"id"`
	ProjectID       pgtype.UUID `json:"project_id"`
	IndexSnapshotID pgtype.UUID `json:"index_snapshot_id"`
	SourceSymbolID  pgtype.UUID `json:"source_symbol_id"`
	SourceFilePath  string      `json:"source_file_path"`
	TargetFilePath  pgtype.Text `json:"target_file_path"`
	ImportName      string      `json:"import_name"`
	ImportType      string      `json:"import_type"`
	PackageName     pgtype.Text `json:"package_name"`
	PackageVersion  pgtype.Text `json:"package_version"`
}

type EmbeddingProviderConfig struct {
	ID                    pgtype.UUID        `json:"id"`
	Name                  string             `json:"name"`
	Provider              string             `json:"provider"`
	EndpointUrl           string             `json:"endpoint_url"`
	Model                 string             `json:"model"`
	Dimensions            int32              `json:"dimensions"`
	MaxTokens             int32              `json:"max_tokens"`
	SettingsJson          []byte             `json:"settings_json"`
	CredentialsEncrypted  []byte             `json:"credentials_encrypted"`
	IsActive              bool               `json:"is_active"`
	IsDefault             bool               `json:"is_default"`
	IsAvailableToProjects bool               `json:"is_available_to_projects"`
	ProjectID             pgtype.UUID        `json:"project_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type EmbeddingVersion struct {
	ID                        pgtype.UUID        `json:"id"`
	EmbeddingProviderConfigID pgtype.UUID        `json:"embedding_provider_config_id"`
	Provider                  string             `json:"provider"`
	Model                     string             `json:"model"`
	Dimensions                int32              `json:"dimensions"`
	VersionLabel              string             `json:"version_label"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
}

type Export struct {
	ID              pgtype.UUID        `json:"id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	IndexSnapshotID pgtype.UUID        `json:"index_snapshot_id"`
	FileID          pgtype.UUID        `json:"file_id"`
	ExportKind      string             `json:"export_kind"`
	ExportedName    string             `json:"exported_name"`
	LocalName       pgtype.Text        `json:"local_name"`
	SymbolID        pgtype.UUID        `json:"symbol_id"`
	SourceModule    pgtype.Text        `json:"source_module"`
	Line            int32              `json:"line"`
	Column          int32              `json:"column"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type File struct {
	ID                pgtype.UUID        `json:"id"`
	ProjectID         pgtype.UUID        `json:"project_id"`
	IndexSnapshotID   pgtype.UUID        `json:"index_snapshot_id"`
	FilePath          string             `json:"file_path"`
	Language          pgtype.Text        `json:"language"`
	FileHash          string             `json:"file_hash"`
	SizeBytes         pgtype.Int8        `json:"size_bytes"`
	LineCount         pgtype.Int4        `json:"line_count"`
	FileFacts         []byte             `json:"file_facts"`
	ParserMeta        []byte             `json:"parser_meta"`
	ExtractorStatuses []byte             `json:"extractor_statuses"`
	Issues            []byte             `json:"issues"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	FileContentID     pgtype.UUID        `json:"file_content_id"`
}

type FileContent struct {
	ID            pgtype.UUID        `json:"id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	ContentHash   string             `json:"content_hash"`
	Content       string             `json:"content"`
	TreeSitterAst []byte             `json:"tree_sitter_ast"`
	SizeBytes     int64              `json:"size_bytes"`
	LineCount     int32              `json:"line_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type IndexSnapshot struct {
	ID                 pgtype.UUID        `json:"id"`
	ProjectID          pgtype.UUID        `json:"project_id"`
	Branch             string             `json:"branch"`
	EmbeddingVersionID pgtype.UUID        `json:"embedding_version_id"`
	GitCommit          string             `json:"git_commit"`
	IsActive           bool               `json:"is_active"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	ActivatedAt        pgtype.Timestamptz `json:"activated_at"`
	CommitID           pgtype.UUID        `json:"commit_id"`
}

type IndexingJob struct {
	ID                        pgtype.UUID        `json:"id"`
	ProjectID                 pgtype.UUID        `json:"project_id"`
	IndexSnapshotID           pgtype.UUID        `json:"index_snapshot_id"`
	JobType                   string             `json:"job_type"`
	Status                    string             `json:"status"`
	FilesProcessed            int32              `json:"files_processed"`
	ChunksUpserted            int32              `json:"chunks_upserted"`
	VectorsDeleted            int32              `json:"vectors_deleted"`
	ErrorDetails              []byte             `json:"error_details"`
	EmbeddingProviderConfigID pgtype.UUID        `json:"embedding_provider_config_id"`
	LlmProviderConfigID       pgtype.UUID        `json:"llm_provider_config_id"`
	WorkerID                  pgtype.Text        `json:"worker_id"`
	StartedAt                 pgtype.Timestamptz `json:"started_at"`
	FinishedAt                pgtype.Timestamptz `json:"finished_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
}

type JsxUsage struct {
	ID                     pgtype.UUID        `json:"id"`
	ProjectID              pgtype.UUID        `json:"project_id"`
	IndexSnapshotID        pgtype.UUID        `json:"index_snapshot_id"`
	FileID                 pgtype.UUID        `json:"file_id"`
	SourceSymbolID         pgtype.UUID        `json:"source_symbol_id"`
	ComponentName          string             `json:"component_name"`
	IsIntrinsic            bool               `json:"is_intrinsic"`
	IsFragment             bool               `json:"is_fragment"`
	Line                   int32              `json:"line"`
	Column                 int32              `json:"column"`
	ResolvedTargetSymbolID pgtype.UUID        `json:"resolved_target_symbol_id"`
	Confidence             pgtype.Text        `json:"confidence"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type LlmProviderConfig struct {
	ID                    pgtype.UUID        `json:"id"`
	Name                  string             `json:"name"`
	Provider              string             `json:"provider"`
	EndpointUrl           string             `json:"endpoint_url"`
	Model                 pgtype.Text        `json:"model"`
	SettingsJson          []byte             `json:"settings_json"`
	CredentialsEncrypted  []byte             `json:"credentials_encrypted"`
	IsActive              bool               `json:"is_active"`
	IsDefault             bool               `json:"is_default"`
	IsAvailableToProjects bool               `json:"is_available_to_projects"`
	ProjectID             pgtype.UUID        `json:"project_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type NetworkCall struct {
	ID              pgtype.UUID        `json:"id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	IndexSnapshotID pgtype.UUID        `json:"index_snapshot_id"`
	FileID          pgtype.UUID        `json:"file_id"`
	SourceSymbolID  pgtype.UUID        `json:"source_symbol_id"`
	ClientKind      string             `json:"client_kind"`
	Method          string             `json:"method"`
	UrlLiteral      pgtype.Text        `json:"url_literal"`
	UrlTemplate     pgtype.Text        `json:"url_template"`
	IsRelative      bool               `json:"is_relative"`
	StartLine       int32              `json:"start_line"`
	StartColumn     int32              `json:"start_column"`
	Confidence      pgtype.Text        `json:"confidence"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID                              pgtype.UUID        `json:"id"`
	Name                            string             `json:"name"`
	RepoUrl                         string             `json:"repo_url"`
	DefaultBranch                   string             `json:"default_branch"`
	Status                          string             `json:"status"`
	CreatedBy                       pgtype.UUID        `json:"created_by"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                       pgtype.Timestamptz `json:"updated_at"`
	SelectedEmbeddingGlobalConfigID pgtype.UUID        `json:"selected_embedding_global_config_id"`
	SelectedLlmGlobalConfigID       pgtype.UUID        `json:"selected_llm_global_config_id"`
}

type ProjectMember struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ProjectSshKeyAssignment struct {
	ID           pgtype.UUID        `json:"id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	SshKeyID     pgtype.UUID        `json:"ssh_key_id"`
	IsActive     bool               `json:"is_active"`
	AssignedAt   pgtype.Timestamptz `json:"assigned_at"`
	UnassignedAt pgtype.Timestamptz `json:"unassigned_at"`
}

type QueryLog struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	ApiKeyID    pgtype.UUID        `json:"api_key_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	ToolName    string             `json:"tool_name"`
	QueryText   pgtype.Text        `json:"query_text"`
	ResultCount pgtype.Int4        `json:"result_count"`
	LatencyMs   pgtype.Int4        `json:"latency_ms"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	IpAddress pgtype.Text        `json:"ip_address"`
	UserAgent pgtype.Text        `json:"user_agent"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SshKey struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	PublicKey           string             `json:"public_key"`
	PrivateKeyEncrypted []byte             `json:"private_key_encrypted"`
	KeyType             string             `json:"key_type"`
	Fingerprint         string             `json:"fingerprint"`
	IsActive            bool               `json:"is_active"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	RotatedAt           pgtype.Timestamptz `json:"rotated_at"`
}

type Symbol struct {
	ID              pgtype.UUID        `json:"id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	IndexSnapshotID pgtype.UUID        `json:"index_snapshot_id"`
	FileID          pgtype.UUID        `json:"file_id"`
	Name            string             `json:"name"`
	QualifiedName   pgtype.Text        `json:"qualified_name"`
	Kind            string             `json:"kind"`
	Signature       pgtype.Text        `json:"signature"`
	StartLine       pgtype.Int4        `json:"start_line"`
	EndLine         pgtype.Int4        `json:"end_line"`
	DocText         pgtype.Text        `json:"doc_text"`
	SymbolHash      string             `json:"symbol_hash"`
	ParentSymbolID  pgtype.UUID        `json:"parent_symbol_id"`
	Flags           []byte             `json:"flags"`
	Modifiers       []string           `json:"modifiers"`
	ReturnType      pgtype.Text        `json:"return_type"`
	ParameterTypes  []string           `json:"parameter_types"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type SymbolReference struct {
	ID                     pgtype.UUID        `json:"id"`
	ProjectID              pgtype.UUID        `json:"project_id"`
	IndexSnapshotID        pgtype.UUID        `json:"index_snapshot_id"`
	FileID                 pgtype.UUID        `json:"file_id"`
	SourceSymbolID         pgtype.UUID        `json:"source_symbol_id"`
	ReferenceKind          string             `json:"reference_kind"`
	RawText                pgtype.Text        `json:"raw_text"`
	TargetName             string             `json:"target_name"`
	QualifiedTargetHint    pgtype.Text        `json:"qualified_target_hint"`
	StartLine              int32              `json:"start_line"`
	StartColumn            int32              `json:"start_column"`
	EndLine                int32              `json:"end_line"`
	EndColumn              int32              `json:"end_column"`
	ResolutionScope        pgtype.Text        `json:"resolution_scope"`
	ResolvedTargetSymbolID pgtype.UUID        `json:"resolved_target_symbol_id"`
	Confidence             pgtype.Text        `json:"confidence"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Username    string             `json:"username"`
	Email       string             `json:"email"`
	DisplayName pgtype.Text        `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type UserPlatformRole struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	GrantedBy pgtype.UUID        `json:"granted_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
