// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: network_calls.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertNetworkCall = `-- name: InsertNetworkCall :one
INSERT INTO network_calls (
  project_id, index_snapshot_id, file_id, source_symbol_id,
  client_kind, method, url_literal, url_template, is_relative,
  start_line, start_column, confidence
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, project_id, index_snapshot_id, file_id, source_symbol_id, client_kind, method, url_literal, url_template, is_relative, start_line, start_column, confidence, created_at
`

type InsertNetworkCallParams struct {
	ProjectID       pgtype.UUID `json:"project_id"`
	IndexSnapshotID pgtype.UUID `json:"index_snapshot_id"`
	FileID          pgtype.UUID `json:"file_id"`
	SourceSymbolID  pgtype.UUID `json:"source_symbol_id"`
	ClientKind      string      `json:"client_kind"`
	Method          string      `json:"method"`
	UrlLiteral      pgtype.Text `json:"url_literal"`
	UrlTemplate     pgtype.Text `json:"url_template"`
	IsRelative      bool        `json:"is_relative"`
	StartLine       int32       `json:"start_line"`
	StartColumn     int32       `json:"start_column"`
	Confidence      pgtype.Text `json:"confidence"`
}

func (q *Queries) InsertNetworkCall(ctx context.Context, arg InsertNetworkCallParams) (NetworkCall, error) {
	row := q.db.QueryRow(ctx, insertNetworkCall,
		arg.ProjectID,
		arg.IndexSnapshotID,
		arg.FileID,
		arg.SourceSymbolID,
		arg.ClientKind,
		arg.Method,
		arg.UrlLiteral,
		arg.UrlTemplate,
		arg.IsRelative,
		arg.StartLine,
		arg.StartColumn,
		arg.Confidence,
	)
	var i NetworkCall
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IndexSnapshotID,
		&i.FileID,
		&i.SourceSymbolID,
		&i.ClientKind,
		&i.Method,
		&i.UrlLiteral,
		&i.UrlTemplate,
		&i.IsRelative,
		&i.StartLine,
		&i.StartColumn,
		&i.Confidence,
		&i.CreatedAt,
	)
	return i, err
}

const listNetworkCallsByFileID = `-- name: ListNetworkCallsByFileID :many
SELECT id, project_id, index_snapshot_id, file_id, source_symbol_id, client_kind, method, url_literal, url_template, is_relative, start_line, start_column, confidence, created_at FROM network_calls WHERE file_id = $1 ORDER BY start_line
`

func (q *Queries) ListNetworkCallsByFileID(ctx context.Context, fileID pgtype.UUID) ([]NetworkCall, error) {
	rows, err := q.db.Query(ctx, listNetworkCallsByFileID, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NetworkCall{}
	for rows.Next() {
		var i NetworkCall
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IndexSnapshotID,
			&i.FileID,
			&i.SourceSymbolID,
			&i.ClientKind,
			&i.Method,
			&i.UrlLiteral,
			&i.UrlTemplate,
			&i.IsRelative,
			&i.StartLine,
			&i.StartColumn,
			&i.Confidence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
