// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platform_roles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActivePlatformAdmins = `-- name: CountActivePlatformAdmins :one
SELECT COUNT(*)::bigint AS total
FROM user_platform_roles upr
JOIN users u ON u.id = upr.user_id
WHERE upr.role = 'platform_admin'
  AND u.is_active = TRUE
`

func (q *Queries) CountActivePlatformAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActivePlatformAdmins)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countActivePlatformAdminsForUpdate = `-- name: CountActivePlatformAdminsForUpdate :one
SELECT COUNT(*)::bigint AS total
FROM (
  SELECT upr.id
  FROM user_platform_roles upr
  JOIN users u ON u.id = upr.user_id
  WHERE upr.role = 'platform_admin'
    AND u.is_active = TRUE
  FOR UPDATE OF upr, u
) locked
`

// Locking variant: acquires FOR UPDATE on both user_platform_roles AND users rows
// to serialize concurrent attempts to deactivate or revoke the last platform admin.
// Locking users rows too is critical: the deactivation flow sets users.is_active = FALSE,
// so without locking users a concurrent deactivation could bypass the role-only lock.
// FOR UPDATE cannot be used with aggregate functions directly, so we lock
// the matching rows in a subquery first, then count.
func (q *Queries) CountActivePlatformAdminsForUpdate(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActivePlatformAdminsForUpdate)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getUserPlatformRoles = `-- name: GetUserPlatformRoles :many
SELECT role
FROM user_platform_roles
WHERE user_id = $1
`

func (q *Queries) GetUserPlatformRoles(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserPlatformRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const grantPlatformRole = `-- name: GrantPlatformRole :one
INSERT INTO user_platform_roles (user_id, role, granted_by)
SELECT $1, $2, $3
FROM users WHERE id = $1 AND is_active = TRUE
ON CONFLICT (user_id, role) DO NOTHING
RETURNING id, user_id, role, granted_by, created_at
`

type GrantPlatformRoleParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Role      string      `json:"role"`
	GrantedBy pgtype.UUID `json:"granted_by"`
}

// Only grants when the target user is active, preventing TOCTOU races
// where a concurrent deactivation could allow granting to an inactive user.
func (q *Queries) GrantPlatformRole(ctx context.Context, arg GrantPlatformRoleParams) (UserPlatformRole, error) {
	row := q.db.QueryRow(ctx, grantPlatformRole, arg.UserID, arg.Role, arg.GrantedBy)
	var i UserPlatformRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.GrantedBy,
		&i.CreatedAt,
	)
	return i, err
}

const hasPlatformRole = `-- name: HasPlatformRole :one
SELECT EXISTS (
  SELECT 1 FROM user_platform_roles
  WHERE user_id = $1 AND role = $2
) AS has_role
`

type HasPlatformRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) HasPlatformRole(ctx context.Context, arg HasPlatformRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPlatformRole, arg.UserID, arg.Role)
	var has_role bool
	err := row.Scan(&has_role)
	return has_role, err
}

const listActivePlatformRoleAssignments = `-- name: ListActivePlatformRoleAssignments :many
SELECT upr.id, upr.user_id, upr.role, upr.granted_by, upr.created_at,
       u.username, u.display_name, u.avatar_url
FROM user_platform_roles upr
JOIN users u ON u.id = upr.user_id
WHERE u.is_active = TRUE
ORDER BY upr.created_at ASC
`

type ListActivePlatformRoleAssignmentsRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        string             `json:"role"`
	GrantedBy   pgtype.UUID        `json:"granted_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Username    string             `json:"username"`
	DisplayName pgtype.Text        `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
}

// Returns role assignments for active users only. Deactivated users are
// excluded because their roles are effectively dormant (they cannot log in).
func (q *Queries) ListActivePlatformRoleAssignments(ctx context.Context) ([]ListActivePlatformRoleAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listActivePlatformRoleAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivePlatformRoleAssignmentsRow{}
	for rows.Next() {
		var i ListActivePlatformRoleAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.GrantedBy,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePlatformRole = `-- name: RevokePlatformRole :execrows
DELETE FROM user_platform_roles
WHERE user_id = $1 AND role = $2
`

type RevokePlatformRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) RevokePlatformRole(ctx context.Context, arg RevokePlatformRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokePlatformRole, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPlatformRoleByUsername = `-- name: UpsertPlatformRoleByUsername :execresult
INSERT INTO user_platform_roles (user_id, role)
SELECT u.id, 'platform_admin'
FROM users u
WHERE u.username = $1
  AND u.is_active = TRUE
ON CONFLICT (user_id, role) DO NOTHING
`

func (q *Queries) UpsertPlatformRoleByUsername(ctx context.Context, username string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, upsertPlatformRoleByUsername, username)
}
