// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignProjectSSHKey = `-- name: AssignProjectSSHKey :one
INSERT INTO project_ssh_key_assignments (
  project_id,
  ssh_key_id,
  is_active
) VALUES ($1, $2, TRUE)
RETURNING id, project_id, ssh_key_id, is_active, assigned_at, unassigned_at
`

type AssignProjectSSHKeyParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	SshKeyID  pgtype.UUID `json:"ssh_key_id"`
}

func (q *Queries) AssignProjectSSHKey(ctx context.Context, arg AssignProjectSSHKeyParams) (ProjectSshKeyAssignment, error) {
	row := q.db.QueryRow(ctx, assignProjectSSHKey, arg.ProjectID, arg.SshKeyID)
	var i ProjectSshKeyAssignment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SshKeyID,
		&i.IsActive,
		&i.AssignedAt,
		&i.UnassignedAt,
	)
	return i, err
}

const countProjectsByMember = `-- name: CountProjectsByMember :one
SELECT count(*)
FROM projects p
JOIN project_members pm ON pm.project_id = p.id
WHERE pm.user_id = $1
`

func (q *Queries) CountProjectsByMember(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectsByMember, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
  name,
  repo_url,
  default_branch,
  status,
  created_by
) VALUES (
  $1, $2, COALESCE($4, 'main'), COALESCE($5, 'active'), $3
)
RETURNING id, name, repo_url, default_branch, status, created_by, created_at, updated_at, selected_embedding_global_config_id, selected_llm_global_config_id
`

type CreateProjectParams struct {
	Name          string      `json:"name"`
	RepoUrl       string      `json:"repo_url"`
	CreatedBy     pgtype.UUID `json:"created_by"`
	DefaultBranch interface{} `json:"default_branch"`
	Status        interface{} `json:"status"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Name,
		arg.RepoUrl,
		arg.CreatedBy,
		arg.DefaultBranch,
		arg.Status,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoUrl,
		&i.DefaultBranch,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SelectedEmbeddingGlobalConfigID,
		&i.SelectedLlmGlobalConfigID,
	)
	return i, err
}

const deactivateProjectSSHKeyAssignments = `-- name: DeactivateProjectSSHKeyAssignments :exec
UPDATE project_ssh_key_assignments
SET
  is_active = FALSE,
  unassigned_at = NOW()
WHERE project_id = $1
  AND is_active = TRUE
`

func (q *Queries) DeactivateProjectSSHKeyAssignments(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateProjectSSHKeyAssignments, projectID)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, repo_url, default_branch, status, created_by, created_at, updated_at, selected_embedding_global_config_id, selected_llm_global_config_id
FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoUrl,
		&i.DefaultBranch,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SelectedEmbeddingGlobalConfigID,
		&i.SelectedLlmGlobalConfigID,
	)
	return i, err
}

const getProjectSSHKeyAssignment = `-- name: GetProjectSSHKeyAssignment :one
SELECT
  psa.id,
  psa.project_id,
  psa.ssh_key_id,
  psa.is_active,
  psa.assigned_at,
  psa.unassigned_at
FROM project_ssh_key_assignments psa
WHERE psa.project_id = $1
  AND psa.is_active = TRUE
`

func (q *Queries) GetProjectSSHKeyAssignment(ctx context.Context, projectID pgtype.UUID) (ProjectSshKeyAssignment, error) {
	row := q.db.QueryRow(ctx, getProjectSSHKeyAssignment, projectID)
	var i ProjectSshKeyAssignment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SshKeyID,
		&i.IsActive,
		&i.AssignedAt,
		&i.UnassignedAt,
	)
	return i, err
}

const getProjectSSHKeyForExecution = `-- name: GetProjectSSHKeyForExecution :one
SELECT
  sk.id,
  sk.name,
  sk.public_key,
  sk.private_key_encrypted,
  sk.key_type,
  sk.fingerprint,
  p.repo_url,
  p.default_branch
FROM projects p
JOIN project_ssh_key_assignments psa ON psa.project_id = p.id
JOIN ssh_keys sk ON sk.id = psa.ssh_key_id
WHERE p.id = $1
  AND psa.is_active = TRUE
  AND sk.is_active = TRUE
`

type GetProjectSSHKeyForExecutionRow struct {
	ID                  pgtype.UUID `json:"id"`
	Name                string      `json:"name"`
	PublicKey           string      `json:"public_key"`
	PrivateKeyEncrypted []byte      `json:"private_key_encrypted"`
	KeyType             string      `json:"key_type"`
	Fingerprint         string      `json:"fingerprint"`
	RepoUrl             string      `json:"repo_url"`
	DefaultBranch       string      `json:"default_branch"`
}

func (q *Queries) GetProjectSSHKeyForExecution(ctx context.Context, id pgtype.UUID) (GetProjectSSHKeyForExecutionRow, error) {
	row := q.db.QueryRow(ctx, getProjectSSHKeyForExecution, id)
	var i GetProjectSSHKeyForExecutionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicKey,
		&i.PrivateKeyEncrypted,
		&i.KeyType,
		&i.Fingerprint,
		&i.RepoUrl,
		&i.DefaultBranch,
	)
	return i, err
}

const getProjectSSHKeyWithDetails = `-- name: GetProjectSSHKeyWithDetails :one
SELECT
  sk.id,
  sk.name,
  sk.fingerprint,
  sk.public_key,
  sk.key_type,
  sk.created_at
FROM project_ssh_key_assignments psa
JOIN ssh_keys sk ON sk.id = psa.ssh_key_id
WHERE psa.project_id = $1
  AND psa.is_active = TRUE
`

type GetProjectSSHKeyWithDetailsRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Fingerprint string             `json:"fingerprint"`
	PublicKey   string             `json:"public_key"`
	KeyType     string             `json:"key_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetProjectSSHKeyWithDetails(ctx context.Context, projectID pgtype.UUID) (GetProjectSSHKeyWithDetailsRow, error) {
	row := q.db.QueryRow(ctx, getProjectSSHKeyWithDetails, projectID)
	var i GetProjectSSHKeyWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Fingerprint,
		&i.PublicKey,
		&i.KeyType,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectWithHealth = `-- name: GetProjectWithHealth :one
SELECT
  p.id, p.name, p.repo_url, p.default_branch, p.status, p.created_by, p.created_at, p.updated_at, p.selected_embedding_global_config_id, p.selected_llm_global_config_id,
  snap.id                           AS index_snapshot_id,
  COALESCE(snap.git_commit, '')     AS index_git_commit,
  COALESCE(snap.branch, '')         AS index_branch,
  snap.activated_at                 AS index_activated_at,
  active_job.id                     AS active_job_id,
  COALESCE(active_job.status, '')   AS active_job_status,
  COALESCE(active_job.worker_id, '') AS active_job_worker_id,
  active_job.started_at             AS active_job_started_at,
  failed_job.id                     AS failed_job_id,
  failed_job.finished_at            AS failed_job_finished_at,
  COALESCE(failed_job.job_type, '') AS failed_job_type
FROM projects p
LEFT JOIN LATERAL (
  SELECT s.id, s.git_commit, s.branch, s.activated_at
  FROM index_snapshots s
  WHERE s.project_id = p.id AND s.is_active = TRUE
  ORDER BY s.activated_at DESC NULLS LAST, s.id DESC LIMIT 1
) snap ON TRUE
LEFT JOIN LATERAL (
  SELECT j.id, j.status, j.worker_id, j.started_at FROM indexing_jobs j
  WHERE j.project_id = p.id AND j.status IN ('queued', 'running')
  ORDER BY j.created_at DESC, j.id DESC LIMIT 1
) active_job ON TRUE
LEFT JOIN LATERAL (
  SELECT j.id, j.finished_at, j.job_type FROM indexing_jobs j
  WHERE j.project_id = p.id AND j.status = 'failed'
    AND j.finished_at >= NOW() - INTERVAL '24 hours'
    AND NOT EXISTS (
      SELECT 1 FROM indexing_jobs j2
      WHERE j2.project_id = p.id
        AND j2.status = 'completed'
        AND j2.finished_at > j.finished_at
    )
  ORDER BY j.finished_at DESC, j.id DESC LIMIT 1
) failed_job ON TRUE
WHERE p.id = $1
`

type GetProjectWithHealthRow struct {
	ID                              pgtype.UUID        `json:"id"`
	Name                            string             `json:"name"`
	RepoUrl                         string             `json:"repo_url"`
	DefaultBranch                   string             `json:"default_branch"`
	Status                          string             `json:"status"`
	CreatedBy                       pgtype.UUID        `json:"created_by"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                       pgtype.Timestamptz `json:"updated_at"`
	SelectedEmbeddingGlobalConfigID pgtype.UUID        `json:"selected_embedding_global_config_id"`
	SelectedLlmGlobalConfigID       pgtype.UUID        `json:"selected_llm_global_config_id"`
	IndexSnapshotID                 pgtype.UUID        `json:"index_snapshot_id"`
	IndexGitCommit                  string             `json:"index_git_commit"`
	IndexBranch                     string             `json:"index_branch"`
	IndexActivatedAt                pgtype.Timestamptz `json:"index_activated_at"`
	ActiveJobID                     pgtype.UUID        `json:"active_job_id"`
	ActiveJobStatus                 string             `json:"active_job_status"`
	ActiveJobWorkerID               string             `json:"active_job_worker_id"`
	ActiveJobStartedAt              pgtype.Timestamptz `json:"active_job_started_at"`
	FailedJobID                     pgtype.UUID        `json:"failed_job_id"`
	FailedJobFinishedAt             pgtype.Timestamptz `json:"failed_job_finished_at"`
	FailedJobType                   string             `json:"failed_job_type"`
}

func (q *Queries) GetProjectWithHealth(ctx context.Context, id pgtype.UUID) (GetProjectWithHealthRow, error) {
	row := q.db.QueryRow(ctx, getProjectWithHealth, id)
	var i GetProjectWithHealthRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoUrl,
		&i.DefaultBranch,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SelectedEmbeddingGlobalConfigID,
		&i.SelectedLlmGlobalConfigID,
		&i.IndexSnapshotID,
		&i.IndexGitCommit,
		&i.IndexBranch,
		&i.IndexActivatedAt,
		&i.ActiveJobID,
		&i.ActiveJobStatus,
		&i.ActiveJobWorkerID,
		&i.ActiveJobStartedAt,
		&i.FailedJobID,
		&i.FailedJobFinishedAt,
		&i.FailedJobType,
	)
	return i, err
}

const listProjectsByMember = `-- name: ListProjectsByMember :many
SELECT p.id, p.name, p.repo_url, p.default_branch, p.status, p.created_by, p.created_at, p.updated_at, p.selected_embedding_global_config_id, p.selected_llm_global_config_id
FROM projects p
JOIN project_members pm ON pm.project_id = p.id
WHERE pm.user_id = $1
ORDER BY p.created_at DESC, p.id DESC
LIMIT $2 OFFSET $3
`

type ListProjectsByMemberParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListProjectsByMember(ctx context.Context, arg ListProjectsByMemberParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByMember, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepoUrl,
			&i.DefaultBranch,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SelectedEmbeddingGlobalConfigID,
			&i.SelectedLlmGlobalConfigID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveProjectSSHKeyAssignment = `-- name: LockActiveProjectSSHKeyAssignment :one
SELECT psa.id
FROM project_ssh_key_assignments psa
WHERE psa.project_id = $1
  AND psa.is_active = TRUE
FOR UPDATE
`

func (q *Queries) LockActiveProjectSSHKeyAssignment(ctx context.Context, projectID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockActiveProjectSSHKeyAssignment, projectID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
  name = COALESCE($1, name),
  repo_url = COALESCE($2, repo_url),
  default_branch = COALESCE($3, default_branch),
  status = COALESCE($4, status),
  updated_at = NOW()
WHERE id = $5
RETURNING id, name, repo_url, default_branch, status, created_by, created_at, updated_at, selected_embedding_global_config_id, selected_llm_global_config_id
`

type UpdateProjectParams struct {
	Name          pgtype.Text `json:"name"`
	RepoUrl       pgtype.Text `json:"repo_url"`
	DefaultBranch pgtype.Text `json:"default_branch"`
	Status        pgtype.Text `json:"status"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Name,
		arg.RepoUrl,
		arg.DefaultBranch,
		arg.Status,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoUrl,
		&i.DefaultBranch,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SelectedEmbeddingGlobalConfigID,
		&i.SelectedLlmGlobalConfigID,
	)
	return i, err
}
