// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateSnapshot(ctx context.Context, id pgtype.UUID) error
	ActivateUser(ctx context.Context, id pgtype.UUID) error
	AdminCountUsers(ctx context.Context, arg AdminCountUsersParams) (int64, error)
	AdminGetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	AdminGetUserMemberships(ctx context.Context, userID pgtype.UUID) ([]AdminGetUserMembershipsRow, error)
	AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error)
	AdminUpdateUser(ctx context.Context, arg AdminUpdateUserParams) (User, error)
	AssignProjectSSHKey(ctx context.Context, arg AssignProjectSSHKeyParams) (ProjectSshKeyAssignment, error)
	CheckAPIKeyProjectAccess(ctx context.Context, arg CheckAPIKeyProjectAccessParams) (string, error)
	ClaimQueuedIndexingJob(ctx context.Context, arg ClaimQueuedIndexingJobParams) (int64, error)
	ClearSelectedEmbeddingGlobalConfig(ctx context.Context, id pgtype.UUID) error
	ClearSelectedLLMGlobalConfig(ctx context.Context, id pgtype.UUID) error
	CountActiveAssignmentsByKey(ctx context.Context, sshKeyID pgtype.UUID) (int64, error)
	CountActiveJobsForUser(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountActivePlatformAdmins(ctx context.Context) (int64, error)
	// Locking variant: acquires FOR UPDATE on both user_platform_roles AND users rows
	// to serialize concurrent attempts to deactivate or revoke the last platform admin.
	// Locking users rows too is critical: the deactivation flow sets users.is_active = FALSE,
	// so without locking users a concurrent deactivation could bypass the role-only lock.
	// FOR UPDATE cannot be used with aggregate functions directly, so we lock
	// the matching rows in a subquery first, then count.
	CountActivePlatformAdminsForUpdate(ctx context.Context) (int64, error)
	CountCommitFileDiffs(ctx context.Context, arg CountCommitFileDiffsParams) (int64, error)
	CountFailedJobsForUser24h(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountFileDiffsByPath(ctx context.Context, arg CountFileDiffsByPathParams) (int64, error)
	CountFilesWithDependencies(ctx context.Context, arg CountFilesWithDependenciesParams) (int64, error)
	CountPersonalKeys(ctx context.Context, createdBy pgtype.UUID) (int64, error)
	CountProjectCommits(ctx context.Context, projectID pgtype.UUID) (int64, error)
	CountProjectJobs(ctx context.Context, projectID pgtype.UUID) (int64, error)
	CountProjectKeys(ctx context.Context, projectID pgtype.UUID) (int64, error)
	CountProjectOwners(ctx context.Context, projectID pgtype.UUID) (int64, error)
	// Counts project owners while acquiring row-level locks on the matching
	// project_members rows. Use inside a transaction to serialize concurrent
	// owner demotion / removal and prevent the last-owner invariant from
	// being violated by race conditions.
	// NOTE: FOR UPDATE cannot be used directly with aggregates, so we lock
	// the rows in a subquery and count the locked result set.
	CountProjectOwnersForUpdate(ctx context.Context, projectID pgtype.UUID) (int64, error)
	CountProjectsByMember(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountProjectsUsingEmbeddingConfig(ctx context.Context, selectedEmbeddingGlobalConfigID pgtype.UUID) (int64, error)
	CountProjectsUsingLLMConfig(ctx context.Context, selectedLlmGlobalConfigID pgtype.UUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateEmbeddingDefaultProviderConfigIfMissing(ctx context.Context, arg CreateEmbeddingDefaultProviderConfigIfMissingParams) error
	CreateEmbeddingProviderConfig(ctx context.Context, arg CreateEmbeddingProviderConfigParams) (EmbeddingProviderConfig, error)
	CreateEmbeddingVersion(ctx context.Context, arg CreateEmbeddingVersionParams) (EmbeddingVersion, error)
	CreateGlobalEmbeddingProviderConfig(ctx context.Context, arg CreateGlobalEmbeddingProviderConfigParams) (EmbeddingProviderConfig, error)
	// Creates a new non-default global config. is_default is always FALSE.
	CreateGlobalEmbeddingProviderConfigNonDefault(ctx context.Context, arg CreateGlobalEmbeddingProviderConfigNonDefaultParams) (EmbeddingProviderConfig, error)
	CreateGlobalLLMProviderConfig(ctx context.Context, arg CreateGlobalLLMProviderConfigParams) (LlmProviderConfig, error)
	// Creates a new non-default global LLM config. is_default is always FALSE.
	CreateGlobalLLMProviderConfigNonDefault(ctx context.Context, arg CreateGlobalLLMProviderConfigNonDefaultParams) (LlmProviderConfig, error)
	CreateIndexSnapshot(ctx context.Context, arg CreateIndexSnapshotParams) (IndexSnapshot, error)
	CreateIndexingJob(ctx context.Context, arg CreateIndexingJobParams) (IndexingJob, error)
	CreateLLMDefaultProviderConfigIfMissing(ctx context.Context, arg CreateLLMDefaultProviderConfigIfMissingParams) error
	CreateLLMProviderConfig(ctx context.Context, arg CreateLLMProviderConfigParams) (LlmProviderConfig, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProjectMember(ctx context.Context, arg CreateProjectMemberParams) (ProjectMember, error)
	CreateSSHKey(ctx context.Context, arg CreateSSHKeyParams) (SshKey, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateActiveSnapshot(ctx context.Context, arg DeactivateActiveSnapshotParams) error
	// Deactivates only the current default global config, leaving non-default configs untouched.
	DeactivateDefaultGlobalEmbeddingProviderConfig(ctx context.Context) error
	// Deactivates only the current default global config, leaving non-default configs untouched.
	DeactivateDefaultGlobalLLMProviderConfig(ctx context.Context) error
	// Soft-deletes a single global config by ID.
	// The is_default = FALSE guard prevents deleting a config that was concurrently promoted.
	DeactivateGlobalEmbeddingProviderConfigByID(ctx context.Context, id pgtype.UUID) (int64, error)
	// DEPRECATED: Use DeactivateDefaultGlobalEmbeddingProviderConfig instead.
	// This deactivates ALL global rows, which breaks multi-provider support.
	DeactivateGlobalEmbeddingProviderConfigs(ctx context.Context) error
	// Soft-deletes a single global LLM config by ID.
	// The is_default = FALSE guard prevents deleting a config that was concurrently promoted.
	DeactivateGlobalLLMProviderConfigByID(ctx context.Context, id pgtype.UUID) (int64, error)
	// DEPRECATED: Use DeactivateDefaultGlobalLLMProviderConfig instead.
	// This deactivates ALL global rows, which breaks multi-provider support.
	DeactivateGlobalLLMProviderConfigs(ctx context.Context) error
	DeactivateProjectEmbeddingProviderConfigs(ctx context.Context, projectID pgtype.UUID) error
	DeactivateProjectLLMProviderConfigs(ctx context.Context, projectID pgtype.UUID) error
	DeactivateProjectSSHKeyAssignments(ctx context.Context, projectID pgtype.UUID) error
	DeactivateUser(ctx context.Context, id pgtype.UUID) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteOrphanedBuildingSnapshot(ctx context.Context, id pgtype.UUID) error
	DeleteProject(ctx context.Context, id pgtype.UUID) error
	DeleteProjectCommits(ctx context.Context, projectID pgtype.UUID) error
	DeleteProjectFileContents(ctx context.Context, projectID pgtype.UUID) error
	DeleteProjectMember(ctx context.Context, arg DeleteProjectMemberParams) error
	DeleteSession(ctx context.Context, tokenHash string) error
	DeleteSnapshotArtifacts(ctx context.Context, indexSnapshotID pgtype.UUID) error
	DeleteUserSessions(ctx context.Context, userID pgtype.UUID) error
	// Clears is_default on the current default. Step 1 of the promote transaction.
	DemoteGlobalEmbeddingProviderConfigDefault(ctx context.Context) error
	// Clears is_default on the current default LLM config. Step 1 of the promote transaction.
	DemoteGlobalLLMProviderConfigDefault(ctx context.Context) error
	FailStaleJob(ctx context.Context, arg FailStaleJobParams) (int64, error)
	FindActiveIndexingJobForProjectAndType(ctx context.Context, arg FindActiveIndexingJobForProjectAndTypeParams) (IndexingJob, error)
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetAPIKeyByID(ctx context.Context, id pgtype.UUID) (ApiKey, error)
	GetActiveProjectEmbeddingProviderConfig(ctx context.Context, projectID pgtype.UUID) (EmbeddingProviderConfig, error)
	GetActiveProjectLLMProviderConfig(ctx context.Context, projectID pgtype.UUID) (LlmProviderConfig, error)
	GetActiveSnapshotForBranch(ctx context.Context, arg GetActiveSnapshotForBranchParams) (IndexSnapshot, error)
	GetActiveSnapshotForProject(ctx context.Context, projectID pgtype.UUID) (IndexSnapshot, error)
	GetCommitByHash(ctx context.Context, arg GetCommitByHashParams) (Commit, error)
	GetCommitByID(ctx context.Context, arg GetCommitByIDParams) (Commit, error)
	GetCommitChildren(ctx context.Context, arg GetCommitChildrenParams) ([]GetCommitChildrenRow, error)
	GetCommitDiffStats(ctx context.Context, arg GetCommitDiffStatsParams) (GetCommitDiffStatsRow, error)
	GetCommitFileDiff(ctx context.Context, arg GetCommitFileDiffParams) (CommitFileDiff, error)
	GetCommitParents(ctx context.Context, arg GetCommitParentsParams) ([]GetCommitParentsRow, error)
	GetDefaultGlobalEmbeddingProviderConfig(ctx context.Context) (EmbeddingProviderConfig, error)
	GetDefaultGlobalLLMProviderConfig(ctx context.Context) (LlmProviderConfig, error)
	// ===================== Embedding Provider Configs =====================
	GetEmbeddingProviderConfigByID(ctx context.Context, id pgtype.UUID) (EmbeddingProviderConfig, error)
	GetEmbeddingVersionByLabel(ctx context.Context, versionLabel string) (EmbeddingVersion, error)
	GetFileBySnapshotAndPath(ctx context.Context, arg GetFileBySnapshotAndPathParams) (pgtype.UUID, error)
	GetFileContentByHash(ctx context.Context, arg GetFileContentByHashParams) (FileContent, error)
	GetFileContentByID(ctx context.Context, arg GetFileContentByIDParams) (FileContent, error)
	GetFileWithContent(ctx context.Context, arg GetFileWithContentParams) (GetFileWithContentRow, error)
	GetFileWithContentAndAST(ctx context.Context, arg GetFileWithContentAndASTParams) (GetFileWithContentAndASTRow, error)
	GetGlobalEmbeddingProviderConfigByID(ctx context.Context, id pgtype.UUID) (EmbeddingProviderConfig, error)
	GetGlobalLLMProviderConfigByID(ctx context.Context, id pgtype.UUID) (LlmProviderConfig, error)
	GetIndexSnapshot(ctx context.Context, id pgtype.UUID) (IndexSnapshot, error)
	GetIndexingJob(ctx context.Context, id pgtype.UUID) (IndexingJob, error)
	// ===================== LLM Provider Configs =====================
	GetLLMProviderConfigByID(ctx context.Context, id pgtype.UUID) (LlmProviderConfig, error)
	GetProject(ctx context.Context, id pgtype.UUID) (Project, error)
	GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (ProjectMember, error)
	// Fetches a project member row while acquiring a FOR UPDATE lock.
	// Use inside a transaction to prevent TOCTOU races on role checks.
	GetProjectMemberForUpdate(ctx context.Context, arg GetProjectMemberForUpdateParams) (ProjectMember, error)
	// ===================== Project Provider Selections =====================
	GetProjectProviderSelections(ctx context.Context, id pgtype.UUID) (GetProjectProviderSelectionsRow, error)
	GetProjectSSHKeyAssignment(ctx context.Context, projectID pgtype.UUID) (ProjectSshKeyAssignment, error)
	GetProjectSSHKeyForExecution(ctx context.Context, id pgtype.UUID) (GetProjectSSHKeyForExecutionRow, error)
	GetProjectSSHKeyWithDetails(ctx context.Context, projectID pgtype.UUID) (GetProjectSSHKeyWithDetailsRow, error)
	GetProjectWithHealth(ctx context.Context, id pgtype.UUID) (GetProjectWithHealthRow, error)
	GetQueryStats24hForUser(ctx context.Context, userID pgtype.UUID) (GetQueryStats24hForUserRow, error)
	GetSSHKey(ctx context.Context, arg GetSSHKeyParams) (SshKey, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error)
	// Fetch a single symbol by ID with joined file metadata.
	GetSymbolByID(ctx context.Context, arg GetSymbolByIDParams) (GetSymbolByIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserPlatformRoles(ctx context.Context, userID pgtype.UUID) ([]string, error)
	// Only grants when the target user is active, preventing TOCTOU races
	// where a concurrent deactivation could allow granting to an inactive user.
	GrantPlatformRole(ctx context.Context, arg GrantPlatformRoleParams) (UserPlatformRole, error)
	HasPlatformRole(ctx context.Context, arg HasPlatformRoleParams) (bool, error)
	InsertCodeChunk(ctx context.Context, arg InsertCodeChunkParams) (CodeChunk, error)
	// =============================================
	// Commits
	// =============================================
	InsertCommit(ctx context.Context, arg InsertCommitParams) (Commit, error)
	// =============================================
	// Commit file diffs
	// =============================================
	InsertCommitFileDiff(ctx context.Context, arg InsertCommitFileDiffParams) (CommitFileDiff, error)
	// =============================================
	// Commit parents
	// =============================================
	InsertCommitParent(ctx context.Context, arg InsertCommitParentParams) error
	InsertDependency(ctx context.Context, arg InsertDependencyParams) (Dependency, error)
	InsertExport(ctx context.Context, arg InsertExportParams) (Export, error)
	InsertFile(ctx context.Context, arg InsertFileParams) (File, error)
	InsertJsxUsage(ctx context.Context, arg InsertJsxUsageParams) (JsxUsage, error)
	InsertNetworkCall(ctx context.Context, arg InsertNetworkCallParams) (NetworkCall, error)
	InsertSymbol(ctx context.Context, arg InsertSymbolParams) (Symbol, error)
	InsertSymbolReference(ctx context.Context, arg InsertSymbolReferenceParams) (SymbolReference, error)
	// Returns role assignments for active users only. Deactivated users are
	// excluded because their roles are effectively dormant (they cannot log in).
	ListActivePlatformRoleAssignments(ctx context.Context) ([]ListActivePlatformRoleAssignmentsRow, error)
	ListAllProjectsWithHealth(ctx context.Context) ([]ListAllProjectsWithHealthRow, error)
	ListAvailableGlobalEmbeddingProviderConfigs(ctx context.Context) ([]ListAvailableGlobalEmbeddingProviderConfigsRow, error)
	ListAvailableGlobalLLMProviderConfigs(ctx context.Context) ([]ListAvailableGlobalLLMProviderConfigsRow, error)
	ListChunksByFileID(ctx context.Context, fileID pgtype.UUID) ([]CodeChunk, error)
	ListCommitFileDiffs(ctx context.Context, arg ListCommitFileDiffsParams) ([]CommitFileDiff, error)
	ListCommitFileDiffsMeta(ctx context.Context, arg ListCommitFileDiffsMetaParams) ([]ListCommitFileDiffsMetaRow, error)
	ListCommitsBetween(ctx context.Context, arg ListCommitsBetweenParams) ([]Commit, error)
	ListDependenciesBySnapshotAndFile(ctx context.Context, arg ListDependenciesBySnapshotAndFileParams) ([]Dependency, error)
	// Forward: what does this file import?
	ListDependenciesFromFile(ctx context.Context, arg ListDependenciesFromFileParams) ([]ListDependenciesFromFileRow, error)
	// Batch forward lookup for BFS: all imports from a set of source files.
	ListDependenciesFromFiles(ctx context.Context, arg ListDependenciesFromFilesParams) ([]ListDependenciesFromFilesRow, error)
	// Reverse: what imports this file?
	ListDependenciesToFile(ctx context.Context, arg ListDependenciesToFileParams) ([]ListDependenciesToFileRow, error)
	// Batch reverse lookup for BFS: all files importing any of the given files.
	ListDependenciesToFiles(ctx context.Context, arg ListDependenciesToFilesParams) ([]ListDependenciesToFilesRow, error)
	ListExportsByFileID(ctx context.Context, fileID pgtype.UUID) ([]Export, error)
	// External packages: target_file_path IS NULL (unresolvable within project).
	ListExternalDependencies(ctx context.Context, arg ListExternalDependenciesParams) ([]ListExternalDependenciesRow, error)
	// Per-file aggregate: how many imports and how many importers.
	ListFileDependencyCounts(ctx context.Context, arg ListFileDependencyCountsParams) ([]ListFileDependencyCountsRow, error)
	ListFileDiffsByPath(ctx context.Context, arg ListFileDiffsByPathParams) ([]CommitFileDiff, error)
	ListFileDiffsByPathWithCommit(ctx context.Context, arg ListFileDiffsByPathWithCommitParams) ([]ListFileDiffsByPathWithCommitRow, error)
	// ===================== Global Provider Config Management =====================
	ListGlobalEmbeddingProviderConfigs(ctx context.Context) ([]EmbeddingProviderConfig, error)
	ListGlobalLLMProviderConfigs(ctx context.Context) ([]LlmProviderConfig, error)
	ListJsxUsagesByFileID(ctx context.Context, fileID pgtype.UUID) ([]JsxUsage, error)
	ListNetworkCallsByFileID(ctx context.Context, fileID pgtype.UUID) ([]NetworkCall, error)
	ListPersonalKeys(ctx context.Context, createdBy pgtype.UUID) ([]ApiKey, error)
	ListProjectCommits(ctx context.Context, arg ListProjectCommitsParams) ([]Commit, error)
	ListProjectJobs(ctx context.Context, arg ListProjectJobsParams) ([]IndexingJob, error)
	ListProjectKeys(ctx context.Context, projectID pgtype.UUID) ([]ApiKey, error)
	ListProjectMembers(ctx context.Context, projectID pgtype.UUID) ([]ListProjectMembersRow, error)
	ListProjectsByMember(ctx context.Context, arg ListProjectsByMemberParams) ([]Project, error)
	ListProjectsBySSHKey(ctx context.Context, arg ListProjectsBySSHKeyParams) ([]Project, error)
	ListSSHKeys(ctx context.Context, createdBy pgtype.UUID) ([]SshKey, error)
	ListSnapshotFiles(ctx context.Context, indexSnapshotID pgtype.UUID) ([]File, error)
	// List child symbols (e.g. methods of a class) ordered by source position.
	ListSymbolChildren(ctx context.Context, arg ListSymbolChildrenParams) ([]ListSymbolChildrenRow, error)
	ListSymbolReferencesByFileID(ctx context.Context, fileID pgtype.UUID) ([]SymbolReference, error)
	ListSymbolsByFileID(ctx context.Context, fileID pgtype.UUID) ([]Symbol, error)
	ListUserProjectIDs(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error)
	ListUserProjects(ctx context.Context, userID pgtype.UUID) ([]ListUserProjectsRow, error)
	ListUserProjectsWithHealth(ctx context.Context, userID pgtype.UUID) ([]ListUserProjectsWithHealthRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	LockActiveProjectSSHKeyAssignment(ctx context.Context, projectID pgtype.UUID) (pgtype.UUID, error)
	// Acquires a row-level lock on a project; use inside a transaction.
	LockProjectRow(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	// Acquires a row-level lock on a user; use inside a transaction.
	LockUserRow(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	// Sets is_default=TRUE on the target config. Step 2 of the promote transaction.
	PromoteGlobalEmbeddingProviderConfigToDefault(ctx context.Context, id pgtype.UUID) (int64, error)
	// Sets is_default=TRUE on the target LLM config. Step 2 of the promote transaction.
	PromoteGlobalLLMProviderConfigToDefault(ctx context.Context, id pgtype.UUID) (int64, error)
	ReleaseAdvisoryLockForProject(ctx context.Context, arg ReleaseAdvisoryLockForProjectParams) (bool, error)
	RetireSSHKey(ctx context.Context, arg RetireSSHKeyParams) (SshKey, error)
	RetireSSHKeyIfNoAssignments(ctx context.Context, arg RetireSSHKeyIfNoAssignmentsParams) (SshKey, error)
	RevokePlatformRole(ctx context.Context, arg RevokePlatformRoleParams) (int64, error)
	SetFileContentAST(ctx context.Context, arg SetFileContentASTParams) (int64, error)
	SetIndexingJobCompleted(ctx context.Context, id pgtype.UUID) error
	SetIndexingJobCompletedFromRunning(ctx context.Context, id pgtype.UUID) (int64, error)
	SetIndexingJobFailed(ctx context.Context, arg SetIndexingJobFailedParams) error
	SetIndexingJobFailedFromRunning(ctx context.Context, arg SetIndexingJobFailedFromRunningParams) (int64, error)
	SetIndexingJobProgress(ctx context.Context, arg SetIndexingJobProgressParams) error
	SetIndexingJobRunning(ctx context.Context, id pgtype.UUID) error
	SetSelectedEmbeddingGlobalConfig(ctx context.Context, arg SetSelectedEmbeddingGlobalConfigParams) error
	SetSelectedLLMGlobalConfig(ctx context.Context, arg SetSelectedLLMGlobalConfigParams) error
	SoftDeleteAPIKey(ctx context.Context, id pgtype.UUID) (int64, error)
	// Uses two int4 keys derived from the UUID to avoid hashtext collisions.
	TryAdvisoryLockForProject(ctx context.Context, arg TryAdvisoryLockForProjectParams) (bool, error)
	UpdateAPIKeyLastUsed(ctx context.Context, keyHash string) error
	UpdateFileContentRef(ctx context.Context, arg UpdateFileContentRefParams) (int64, error)
	// In-place partial update of a global config. Only provided (non-NULL) fields are changed.
	UpdateGlobalEmbeddingProviderConfig(ctx context.Context, arg UpdateGlobalEmbeddingProviderConfigParams) (EmbeddingProviderConfig, error)
	// In-place partial update of a global LLM config. Only provided (non-NULL) fields are changed.
	UpdateGlobalLLMProviderConfig(ctx context.Context, arg UpdateGlobalLLMProviderConfigParams) (LlmProviderConfig, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProjectMemberRole(ctx context.Context, arg UpdateProjectMemberRoleParams) (ProjectMember, error)
	// =============================================
	// Snapshot ↔ Commit link
	// =============================================
	UpdateSnapshotCommitID(ctx context.Context, arg UpdateSnapshotCommitIDParams) (int64, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	// =============================================
	// File contents
	// =============================================
	UpsertFileContent(ctx context.Context, arg UpsertFileContentParams) (FileContent, error)
	UpsertPlatformRoleByUsername(ctx context.Context, username string) (pgconn.CommandTag, error)
}

var _ Querier = (*Queries)(nil)
