// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ssh_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveAssignmentsByKey = `-- name: CountActiveAssignmentsByKey :one
SELECT COUNT(*)
FROM project_ssh_key_assignments
WHERE ssh_key_id = $1
  AND is_active = TRUE
`

func (q *Queries) CountActiveAssignmentsByKey(ctx context.Context, sshKeyID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAssignmentsByKey, sshKeyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSSHKey = `-- name: CreateSSHKey :one
INSERT INTO ssh_keys (
  name,
  public_key,
  private_key_encrypted,
  key_type,
  fingerprint,
  created_by
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, public_key, private_key_encrypted, key_type, fingerprint, is_active, created_by, created_at, rotated_at
`

type CreateSSHKeyParams struct {
	Name                string      `json:"name"`
	PublicKey           string      `json:"public_key"`
	PrivateKeyEncrypted []byte      `json:"private_key_encrypted"`
	KeyType             string      `json:"key_type"`
	Fingerprint         string      `json:"fingerprint"`
	CreatedBy           pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateSSHKey(ctx context.Context, arg CreateSSHKeyParams) (SshKey, error) {
	row := q.db.QueryRow(ctx, createSSHKey,
		arg.Name,
		arg.PublicKey,
		arg.PrivateKeyEncrypted,
		arg.KeyType,
		arg.Fingerprint,
		arg.CreatedBy,
	)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicKey,
		&i.PrivateKeyEncrypted,
		&i.KeyType,
		&i.Fingerprint,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const getSSHKey = `-- name: GetSSHKey :one
SELECT id, name, public_key, private_key_encrypted, key_type, fingerprint, is_active, created_by, created_at, rotated_at
FROM ssh_keys
WHERE id = $1
  AND created_by = $2
`

type GetSSHKeyParams struct {
	ID        pgtype.UUID `json:"id"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) GetSSHKey(ctx context.Context, arg GetSSHKeyParams) (SshKey, error) {
	row := q.db.QueryRow(ctx, getSSHKey, arg.ID, arg.CreatedBy)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicKey,
		&i.PrivateKeyEncrypted,
		&i.KeyType,
		&i.Fingerprint,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const listProjectsBySSHKey = `-- name: ListProjectsBySSHKey :many
SELECT p.id, p.name, p.repo_url, p.default_branch, p.status, p.created_by, p.created_at, p.updated_at, p.selected_embedding_global_config_id, p.selected_llm_global_config_id
FROM projects p
JOIN project_ssh_key_assignments psa
  ON psa.project_id = p.id
JOIN ssh_keys sk
  ON sk.id = psa.ssh_key_id
WHERE psa.ssh_key_id = $1
  AND psa.is_active = TRUE
  AND sk.created_by = $2
ORDER BY p.created_at DESC
`

type ListProjectsBySSHKeyParams struct {
	SshKeyID  pgtype.UUID `json:"ssh_key_id"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) ListProjectsBySSHKey(ctx context.Context, arg ListProjectsBySSHKeyParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsBySSHKey, arg.SshKeyID, arg.CreatedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepoUrl,
			&i.DefaultBranch,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SelectedEmbeddingGlobalConfigID,
			&i.SelectedLlmGlobalConfigID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSSHKeys = `-- name: ListSSHKeys :many
SELECT id, name, public_key, private_key_encrypted, key_type, fingerprint, is_active, created_by, created_at, rotated_at
FROM ssh_keys
WHERE created_by = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSSHKeys(ctx context.Context, createdBy pgtype.UUID) ([]SshKey, error) {
	rows, err := q.db.Query(ctx, listSSHKeys, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SshKey{}
	for rows.Next() {
		var i SshKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PublicKey,
			&i.PrivateKeyEncrypted,
			&i.KeyType,
			&i.Fingerprint,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RotatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireSSHKey = `-- name: RetireSSHKey :one
UPDATE ssh_keys
SET
  is_active = FALSE,
  rotated_at = NOW()
WHERE id = $1
  AND created_by = $2
RETURNING id, name, public_key, private_key_encrypted, key_type, fingerprint, is_active, created_by, created_at, rotated_at
`

type RetireSSHKeyParams struct {
	ID        pgtype.UUID `json:"id"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) RetireSSHKey(ctx context.Context, arg RetireSSHKeyParams) (SshKey, error) {
	row := q.db.QueryRow(ctx, retireSSHKey, arg.ID, arg.CreatedBy)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicKey,
		&i.PrivateKeyEncrypted,
		&i.KeyType,
		&i.Fingerprint,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const retireSSHKeyIfNoAssignments = `-- name: RetireSSHKeyIfNoAssignments :one
UPDATE ssh_keys
SET
  is_active = FALSE,
  rotated_at = NOW()
WHERE ssh_keys.id = $1
  AND ssh_keys.created_by = $2
  AND NOT EXISTS (
    SELECT 1 FROM project_ssh_key_assignments
    WHERE project_ssh_key_assignments.ssh_key_id = $1
      AND project_ssh_key_assignments.is_active = TRUE
  )
RETURNING id, name, public_key, private_key_encrypted, key_type, fingerprint, is_active, created_by, created_at, rotated_at
`

type RetireSSHKeyIfNoAssignmentsParams struct {
	ID        pgtype.UUID `json:"id"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) RetireSSHKeyIfNoAssignments(ctx context.Context, arg RetireSSHKeyIfNoAssignmentsParams) (SshKey, error) {
	row := q.db.QueryRow(ctx, retireSSHKeyIfNoAssignments, arg.ID, arg.CreatedBy)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicKey,
		&i.PrivateKeyEncrypted,
		&i.KeyType,
		&i.Fingerprint,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}
