// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: symbols.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSymbolByID = `-- name: GetSymbolByID :one
SELECT s.id, s.project_id, s.index_snapshot_id, s.file_id,
       s.name, s.qualified_name, s.kind, s.signature,
       s.start_line, s.end_line, s.doc_text, s.symbol_hash,
       s.parent_symbol_id,
       s.flags, s.modifiers, s.return_type, s.parameter_types,
       s.created_at,
       f.file_path, f.language
FROM symbols s
JOIN files f ON f.id = s.file_id
WHERE s.id = $1
  AND s.project_id = $2
`

type GetSymbolByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

type GetSymbolByIDRow struct {
	ID              pgtype.UUID        `json:"id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	IndexSnapshotID pgtype.UUID        `json:"index_snapshot_id"`
	FileID          pgtype.UUID        `json:"file_id"`
	Name            string             `json:"name"`
	QualifiedName   pgtype.Text        `json:"qualified_name"`
	Kind            string             `json:"kind"`
	Signature       pgtype.Text        `json:"signature"`
	StartLine       pgtype.Int4        `json:"start_line"`
	EndLine         pgtype.Int4        `json:"end_line"`
	DocText         pgtype.Text        `json:"doc_text"`
	SymbolHash      string             `json:"symbol_hash"`
	ParentSymbolID  pgtype.UUID        `json:"parent_symbol_id"`
	Flags           []byte             `json:"flags"`
	Modifiers       []string           `json:"modifiers"`
	ReturnType      pgtype.Text        `json:"return_type"`
	ParameterTypes  []string           `json:"parameter_types"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	FilePath        string             `json:"file_path"`
	Language        pgtype.Text        `json:"language"`
}

// Fetch a single symbol by ID with joined file metadata.
func (q *Queries) GetSymbolByID(ctx context.Context, arg GetSymbolByIDParams) (GetSymbolByIDRow, error) {
	row := q.db.QueryRow(ctx, getSymbolByID, arg.ID, arg.ProjectID)
	var i GetSymbolByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IndexSnapshotID,
		&i.FileID,
		&i.Name,
		&i.QualifiedName,
		&i.Kind,
		&i.Signature,
		&i.StartLine,
		&i.EndLine,
		&i.DocText,
		&i.SymbolHash,
		&i.ParentSymbolID,
		&i.Flags,
		&i.Modifiers,
		&i.ReturnType,
		&i.ParameterTypes,
		&i.CreatedAt,
		&i.FilePath,
		&i.Language,
	)
	return i, err
}

const listSymbolChildren = `-- name: ListSymbolChildren :many
SELECT s.id, s.project_id, s.index_snapshot_id, s.file_id,
       s.name, s.qualified_name, s.kind, s.signature,
       s.start_line, s.end_line, s.doc_text, s.symbol_hash,
       s.parent_symbol_id, s.created_at,
       f.file_path
FROM symbols s
JOIN files f ON f.id = s.file_id
WHERE s.parent_symbol_id = $1
  AND s.project_id = $2
ORDER BY s.start_line, s.id
`

type ListSymbolChildrenParams struct {
	ParentSymbolID pgtype.UUID `json:"parent_symbol_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
}

type ListSymbolChildrenRow struct {
	ID              pgtype.UUID        `json:"id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	IndexSnapshotID pgtype.UUID        `json:"index_snapshot_id"`
	FileID          pgtype.UUID        `json:"file_id"`
	Name            string             `json:"name"`
	QualifiedName   pgtype.Text        `json:"qualified_name"`
	Kind            string             `json:"kind"`
	Signature       pgtype.Text        `json:"signature"`
	StartLine       pgtype.Int4        `json:"start_line"`
	EndLine         pgtype.Int4        `json:"end_line"`
	DocText         pgtype.Text        `json:"doc_text"`
	SymbolHash      string             `json:"symbol_hash"`
	ParentSymbolID  pgtype.UUID        `json:"parent_symbol_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	FilePath        string             `json:"file_path"`
}

// List child symbols (e.g. methods of a class) ordered by source position.
func (q *Queries) ListSymbolChildren(ctx context.Context, arg ListSymbolChildrenParams) ([]ListSymbolChildrenRow, error) {
	rows, err := q.db.Query(ctx, listSymbolChildren, arg.ParentSymbolID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSymbolChildrenRow{}
	for rows.Next() {
		var i ListSymbolChildrenRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IndexSnapshotID,
			&i.FileID,
			&i.Name,
			&i.QualifiedName,
			&i.Kind,
			&i.Signature,
			&i.StartLine,
			&i.EndLine,
			&i.DocText,
			&i.SymbolHash,
			&i.ParentSymbolID,
			&i.CreatedAt,
			&i.FilePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
