// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: symbol_references.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertSymbolReference = `-- name: InsertSymbolReference :one
INSERT INTO symbol_references (
  project_id, index_snapshot_id, file_id, source_symbol_id,
  reference_kind, raw_text, target_name, qualified_target_hint,
  start_line, start_column, end_line, end_column,
  resolution_scope, resolved_target_symbol_id, confidence
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, project_id, index_snapshot_id, file_id, source_symbol_id, reference_kind, raw_text, target_name, qualified_target_hint, start_line, start_column, end_line, end_column, resolution_scope, resolved_target_symbol_id, confidence, created_at
`

type InsertSymbolReferenceParams struct {
	ProjectID              pgtype.UUID `json:"project_id"`
	IndexSnapshotID        pgtype.UUID `json:"index_snapshot_id"`
	FileID                 pgtype.UUID `json:"file_id"`
	SourceSymbolID         pgtype.UUID `json:"source_symbol_id"`
	ReferenceKind          string      `json:"reference_kind"`
	RawText                pgtype.Text `json:"raw_text"`
	TargetName             string      `json:"target_name"`
	QualifiedTargetHint    pgtype.Text `json:"qualified_target_hint"`
	StartLine              int32       `json:"start_line"`
	StartColumn            int32       `json:"start_column"`
	EndLine                int32       `json:"end_line"`
	EndColumn              int32       `json:"end_column"`
	ResolutionScope        pgtype.Text `json:"resolution_scope"`
	ResolvedTargetSymbolID pgtype.UUID `json:"resolved_target_symbol_id"`
	Confidence             pgtype.Text `json:"confidence"`
}

func (q *Queries) InsertSymbolReference(ctx context.Context, arg InsertSymbolReferenceParams) (SymbolReference, error) {
	row := q.db.QueryRow(ctx, insertSymbolReference,
		arg.ProjectID,
		arg.IndexSnapshotID,
		arg.FileID,
		arg.SourceSymbolID,
		arg.ReferenceKind,
		arg.RawText,
		arg.TargetName,
		arg.QualifiedTargetHint,
		arg.StartLine,
		arg.StartColumn,
		arg.EndLine,
		arg.EndColumn,
		arg.ResolutionScope,
		arg.ResolvedTargetSymbolID,
		arg.Confidence,
	)
	var i SymbolReference
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IndexSnapshotID,
		&i.FileID,
		&i.SourceSymbolID,
		&i.ReferenceKind,
		&i.RawText,
		&i.TargetName,
		&i.QualifiedTargetHint,
		&i.StartLine,
		&i.StartColumn,
		&i.EndLine,
		&i.EndColumn,
		&i.ResolutionScope,
		&i.ResolvedTargetSymbolID,
		&i.Confidence,
		&i.CreatedAt,
	)
	return i, err
}

const listSymbolReferencesByFileID = `-- name: ListSymbolReferencesByFileID :many
SELECT id, project_id, index_snapshot_id, file_id, source_symbol_id, reference_kind, raw_text, target_name, qualified_target_hint, start_line, start_column, end_line, end_column, resolution_scope, resolved_target_symbol_id, confidence, created_at FROM symbol_references WHERE file_id = $1 ORDER BY start_line
`

func (q *Queries) ListSymbolReferencesByFileID(ctx context.Context, fileID pgtype.UUID) ([]SymbolReference, error) {
	rows, err := q.db.Query(ctx, listSymbolReferencesByFileID, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SymbolReference{}
	for rows.Next() {
		var i SymbolReference
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IndexSnapshotID,
			&i.FileID,
			&i.SourceSymbolID,
			&i.ReferenceKind,
			&i.RawText,
			&i.TargetName,
			&i.QualifiedTargetHint,
			&i.StartLine,
			&i.StartColumn,
			&i.EndLine,
			&i.EndColumn,
			&i.ResolutionScope,
			&i.ResolvedTargetSymbolID,
			&i.Confidence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
